### ISSUE TITLE
Remove competing product tags from amazondrive

### ISSUE THREAD

**Issue by ferventcoder** [bcurran3/ChocolateyPackages_CCR#10]
Putting tags in for competing products is very bad form for Chocolatey packages - we want relevant results when we are searching for dropbox, not something that is competing and not actually filling that need.

**Comment by bcurran3** [comment]
I think I'm probably "guilty" of doing this a few times. I can also probably point out a 100 examples of this "problem" in the list of Chocolatey packages.

I do it as a way for users to DISCOVER alternative programs that do the same thing. Personally I've forgotten the name of a program before but remember it's similar to something else and then search based on that something else to find it. Anyways, irrelevant as this request is easy to abide by and keywords can be found easily via search when found in the package's description giving the same desired result.

@ferventcoder - https://chocolatey.org/packages/chocolatey, "Tags nuget **_apt-get_** machine repository chocolatey" - Really?

**Comment by bcurran3** [comment]
Oops, hit wrong button!

**Comment by bcurran3** [comment]
Competing program tags removed from nuspec. Will show in next package release.
