### ISSUE TITLE
enhance instchoco to enable better handling of reinstalling Windows from scratch

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#100]
After a new Windows install, instchoco isn't in the path anymore. So, it needs to be in a location known to me that is NOT on my C drive (since I've probably just wiped out my C drive by reinstalling Windows). For me, that location would be in my Google drive. 

So, if instchoco and the choco-package-list-backup.xml file and my current list of packages are all in the same place in my Google drive, then I can simply get everything from there and ideally instchoco would look in the directory the executable was in (in my Google Drive) and get what it needs from there. 

That way, my process is to open my local copy of Google Drive (or download the files and just execute instchoco and all of my packages would be reinstalled.

Of course, since I'm brand new to this, I may have missed one or many key points :-) ... Or there may be a better way to accomplish this.

**Comment by bcurran3** [comment]
Jeff,

It already works that way.

Bullet point number 4 on the features list at https://chocolatey.org/packages/choco-package-list-backup

> CPLB supports copying InstChoco - The ULTIMATE Chocolatey and Chocolatey packages (re)installer! to your PACKAGES.CONFIG backup location(s) for the fastest way ever to reinstall Chocolatey and your Chocolatey packages! (Or migrate!)

**Comment by jeff9315** [comment]
Yep ... Sorry 'bout that. I didn't see it in the root folder of chocoinstall. It's under chocoinstall/ChocolateyPackageListBackup. My bad.
