### ISSUE TITLE
The upgrade of irfanviewplugins was NOT successful.

### ISSUE THREAD

**Issue by basictheprogram** [bcurran3/ChocolateyPackages_CCR#101]
Trying to upgrade irfanviewplugins to 4.53 and it's throwing an error.

```
> choco --version
0.10.15
```
```
irfanview v4.53 is the latest version available based on your source(s).

You have irfanviewplugins v4.52 installed. Version 4.53 is available based on your source(s).
Progress: Downloading irfanviewplugins 4.53... 100%

irfanviewplugins v4.53 [Approved]
irfanviewplugins package files upgrade completed. Performing other installation steps.
Installing 64-bit irfanviewplugins...
irfanviewplugins has been installed.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe: The process cannot access the file 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe' because it is being used by another process.
The upgrade of irfanviewplugins was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\chocolateyInstall.ps1'.
 See log for details.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins]
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins\tools\iview453_plugins_x64_setup.exe]
```

## Logs
  * [choco.summary.log](https://github.com/bcurran3/ChocolateyPackages/files/3365912/choco.summary.log)
  * [chocolatey.log](https://github.com/bcurran3/ChocolateyPackages/files/3365913/chocolatey.log)

**Comment by bcurran3** [comment]
Hi Bob,

Thanks for the detailed info (logs).

I'll do some investigating; I've got a feeling it's an issue just with the upgrade.

In the meantime, please try uninstalling and installing the plugins (not an upgrade) and report back your findings.

**Comment by basictheprogram** [comment]
Install (not upgrade) still having problems.
```
> choco install irfanviewplugins
Chocolatey v0.10.15
Installing the following packages:
irfanviewplugins
By installing you accept licenses for the packages.
Progress: Downloading irfanviewplugins 4.53... 100%

irfanviewplugins v4.53 [Approved]
irfanviewplugins package files install completed. Performing other installation steps.
Installing 64-bit irfanviewplugins...
irfanviewplugins has been installed.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe: The process cannot access the file 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe' because it is being used by another process.
The install of irfanviewplugins was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\chocolateyInstall.ps1'.
 See log for details.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins]
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins\tools\iview453_plugins_x64_setup.exe]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins\tools\iview453_plugins_x64_setup.exe]
Maximum tries of 3 reached. Throwing error.
Could not move bad package to failure directory It will show as installed.
 C:\ProgramData\chocolatey\lib\irfanviewplugins
 The error:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\irfanviewplugins\tools\iview453_plugins_x64_setup.exe]

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanviewplugins (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\chocolateyInstall.ps1'.
 See log for details.
```
## Logs
  * [choco.summary.log](https://github.com/bcurran3/ChocolateyPackages/files/3366370/choco.summary.log)
  * [chocolatey.log](https://github.com/bcurran3/ChocolateyPackages/files/3366379/chocolatey.log)

**Comment by basictheprogram** [comment]
The debug output says it's looking for the installer at 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe'
```
WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe'.
Please use full path for executables.
```
The irfranviewplugin directory is not being created I can only find a Irfanview directory.

<img width="332" alt="chocolatey_test_environment_windows_2016__Running_" src="https://user-images.githubusercontent.com/6723257/60824852-0a233780-a170-11e9-81c7-4f48b84ba516.png">

Which I believe is from the dependency package irfanview.

**Comment by basictheprogram** [comment]
I forked the project and looking at the package and I am really confused how this package passed the validator and QA process.

There's no checksum or checksumType?

I thought the above fields are mandatory for community feed packages?

The url and url64 point to the toolsDir so this package shims the binaries? 

Is there a reason the http://www.irfanview.com/plugins.htm is not scraped and the binaries downloaded or direct urls to the binaries for so they can be downloaded?

Mostly curious.

**Comment by basictheprogram** [comment]
I see the convoluted Urls and the expired/protected stuff on fosshub.com now.

**Comment by bcurran3** [comment]
The package works fine. 

It's a "you thing." :)

This is the problem:

> ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe: The process cannot access the file 'C:\ProgramData\chocolatey\lib\irfanviewplugins\tools\iview453_plugins_x64_setup.exe' because it is being used by another process.
> The install of irfanviewplugins was NOT successful.

"being used by another process." is the key here. I'm confidently guessing your antivirus is interfering. Turn it off and then install to find out.

> There's no checksum or checksumType?

Correct; not needed, the EXEs are embedded.

> I thought the above fields are mandatory for community feed packages?

That's for packages that download binaries.

> The url and url64 point to the toolsDir so this package shims the binaries?

No. The binaries should be deleted before Chocolatey would make shims (post package install).

> Is there a reason the http://www.irfanview.com/plugins.htm is not scraped and the binaries downloaded or direct urls to the binaries for so they can be downloaded?

YES! The binaries are embedded. Embedded binaries are ALWAYS the best way to go - they work forever and don't rely on downloading from a site that may or may not be working. Packages with embedded binaries are the most consistent.

You just have an AV problem, it happens.

**Comment by basictheprogram** [comment]
New computer, trying the install again. Same problem. Can duplicate the problem using vagrant/virtualbox/win10 90 day eval.

  * My new computer does not have AV installed yet
  * No AV on my vagrant/virtualbox/win10 90 day eval 

I think the problem is line [19](https://github.com/bcurran3/ChocolateyPackages/blob/master/irfanviewplugins/tools/chocolateyInstall.ps1) and line [20](https://github.com/bcurran3/ChocolateyPackages/blob/master/irfanviewplugins/tools/chocolateyInstall.ps1) of the chocolateyInstall.ps1

I know you tagged this a "only me problem" but I'm post here again letting you know a brand new computer with no AV and a vagrant test VM also present a "only me problem"

**Comment by bcurran3** [comment]
Hi Bob.

Possibly Defender is hitting a false positive?

RE: line 19 and 20, possibly the installer runs in a background thread and then the files try to get deleted before they're finished being used? (Slow computer?) I usually add a -EA SilentlyContinue when deleting installer files but see I didn't in this package probably due to bad memory. I'll add it on the next release.

I'm guessing that it's one of the two above. It looks like (from your previous posts) that the plug-ins DID install.

I can send you (e-mail) a test package with the -EA SC added to verify if that's it or not. Just let me know....or soon as IrfanView gets a new version out...

**Comment by basictheprogram** [comment]
That is the confusing part. I see the logs showing "installed" so that is why I think the problem is "post installation". User needs their laptop ready by tomorrow morning so I'll just do my work around. But if you can send me an -EA SC package I'll set it in vagrant.

**Comment by bcurran3** [comment]
I sent you an e-mail with a dropbox link.

**Comment by bcurran3** [comment]
@basictheprogram - any update?
