### ISSUE TITLE
Move VNC Viewer back to installer.

### ISSUE THREAD

**Issue by crkinard** [bcurran3/ChocolateyPackages_CCR#104]
VNC Viewer (RealVNC) has MSI packages that install fine silently (unlike the EXE because it asks for a language on running it >.<).

https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.19.325-Windows-msi.zip

The ZIP has the 32 and 64 MSI files in it.

**Comment by bcurran3** [comment]
Done.
https://chocolatey.org/packages/vnc-viewer/6.19.715
