### ISSUE TITLE
Packages using `dependency-windows10` fail to install that dependency on Win 10 under 1903

### ISSUE THREAD

**Issue by Jackenmen** [bcurran3/ChocolateyPackages_CCR#109]
For example `intel-network-drivers-win10` with `dependency-windows10` set to any version of Win 10 (so `≥ 10.0`) will still fail because chocolatey will try to install "the latest" version of that dependency package - `v10.1903`

**Comment by bcurran3** [comment]
choco install dependency-windows10 --version 10.0
will solve the problem - just do it manually
