### ISSUE TITLE
Installed to c:\tools\bcurran3

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#112]
I don't seem to have have anything in my C:\ProgramData\chocolatey\bin folder relating to chocolatey-package-list-backup anymore and I see that there was just a new release.

A couple of items I've noticed in chocolateyInstall.ps1
`$scriptDir        = "$(Get-ToolsLocation)\BCURRAN3"`

` # Setup`
` # New storage location moving forward for all my Chocolatey scripts
if (!(Test-Path "$ENV:ChocolateyToolsLocation\BCURRAN3")) { New-Item -Path "$ENV:ChocolateyToolsLocation" -Name "BCURRAN3" -ItemType "Directory" | Out-Null }
`

**Comment by bcurran3** [comment]
Correct. Did you have a question or concern?
(Or did I forget to update the description?)

**Comment by jeff9315** [comment]
I was confused because I thought it was supposed to be in the C:\ProgramData\chocolatey\bin folder  and I wasn't sure whether the notes in the ps1 file were for your local copy for testing or for us.

Also, in the readme.md file, it says `Edit \ProgramData\chocolatey\bin\choco-package-list-backup.xml to customize your backup(s). It's easy, there are comments.`

I think the readme should have noted that the location was changed from the chocolatey bin folder to the tools folder

**Comment by bcurran3** [comment]
The readme.md on GitHub is out of sync... a bunch of stuff is that I need to get to eventually.

The new package page on chocolatey.org should be current and has this:

Release Notes
INSTRUCTIONS:
**Edit C:\tools\BCURRAN3\choco-package-list-backup.config to customize your backup(s).** It's easy, there are comments.
From PowerShell or the Command Prompt, type CHOCO-PACKAGE-LIST-BACKUP to backup your Chocolatey packages list.
From Windows, click Chocolatey Package List Backup in the Windows Start Menu or Package List Backup inside the Chocolatey folder if Chocolatey Shortcuts is installed.
CHANGELOG:
2019.08.27 - can now put title and summary info into the packages.config file, **new -EditConfig parameter to edit the config file**, Now works from Command Prompt as well as PowerShell, script installation endpoint changed, config file renamed from .xml to .config
