### ISSUE TITLE
Task Scheduler contains %ChocolateyToolsLocation%\bcurran3

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#113]
My Task Scheduler won't run manually and I realized it has %ChocolateyToolsLocation%\bcurran3 as the location of the script. Should that have been expanded prior to being added to Task Scheduler or do I need to investigate why it can't find the environment variable? Am I correct in assuming that the environment variable is only available from within chocolatey itself? 

I'm so new to both Chocolatey and PowerShell that I haven't gotten my head around when the environment variables are available.

**Comment by bcurran3** [comment]
> I'm so new to both Chocolatey and PowerShell that I haven't gotten my head around when the environment variables are available.

Chuckle. Hey, everyone has to start at zero at some point. So welcome to Chocolatey AND Powershell!

> My Task Scheduler won't run manually and I realized it has %ChocolateyToolsLocation%\bcurran3 as the location of the script.

Task Scheduler runs things AUTOMATICALLY. :)

>  Should that have been expanded prior to being added to Task Scheduler or do I need to investigate why it can't find the environment variable?

it should be fine the way it is as cmd.exe is processing/parsing %ChocolateyToolsLocation% to pass to powershell.exe. Unless you've changed the time, I don't think you'd know if it works yet or not....shouldn't kick off until 6 AM tomorrow (Monday) and I don't think we've hit that time and date anywhere in the world as of your post and mine. So check c:\users\public\chocolateypackagelistbackup after 6 AM your local time.

> Am I correct in assuming that the environment variable is only available from within chocolatey itself?

No, but you can easily verify this. Go to Command Prompt and type

`echo %ChocolateyToolsLocation%`

If you haven't changed it, and I'm guessing you haven't, you should get a response of "C:\tools"

If this didn't already exist, it should have been created during install of choco-package-list-backup via:

`if (!(Test-Path "$ENV:ChocolateyToolsLocation\BCURRAN3")) { New-Item -Path "$ENV:ChocolateyToolsLocation" -Name "BCURRAN3" -ItemType "Directory" | Out-Null }`

**Comment by jeff9315** [comment]
No, I had changed it to run daily. In Task Scheduler, I see an error of (0x1) and checking the date/time stamp on the files, it's not creating a new packages.config file. If I change Task Scheduler to point to C:\Tools\bcurran3, it does create a new packages.config file. But you're right, echoing it in CMD does show it. And I can do a dir %ChocolateyToolsLocation%\BCURRAN3\

Thanks ... Jeff

**Comment by bcurran3** [comment]
So it's all good or there's still a problem? 

If a problem exists, I'm going to guess that it's related to the changing of the scheduled task and recommend uninstalling and re-installing to set back to default and then test by looking next week at Monday's 6 AM job.

It is working for me:
![image](https://user-images.githubusercontent.com/14026600/64130848-ccaae700-cd79-11e9-8c9b-2f88b92b1022.png)

**Comment by jeff9315** [comment]
OK ... I've discovered what the problem is and I believe it IS actually a problem. 

%ChocolateyToolsLocation% is an environment variable that's defined for the Current User. However, %ChocolateyInstall% is defined as a System-wide variable. If I move %ChocolateyToolsLocation% to become a System Variable it works. Which makes sense since the user who runs the Scheduled Task is "System". 

So, did I do something wrong that caused it to become defined in the User section instead of the System section?

**Comment by bcurran3** [comment]
ChocolateyToolsLocation is created by the Chocolatey helper Get-ToolsLocation.ps1.  I just took a look at it and it sets the variable based on if you have admin rights or not:

```
  if (-not($env:ChocolateyToolsLocation -eq $toolsLocation)) {
    try {
      Set-EnvironmentVariable -Name "ChocolateyToolsLocation" -Value $toolsLocation -Scope User
    } catch {
      if (Test-ProcessAdminRights) {
        # sometimes User scope may not exist (such as with core)
        Set-EnvironmentVariable -Name "ChocolateyToolsLocation" -Value $toolsLocation -Scope Machine
```

So I'm guessing when you installed, you weren't admin. 

![image](https://user-images.githubusercontent.com/14026600/64369533-6cae7d80-cfd1-11e9-958c-00d7b31c3c77.png)
