### ISSUE TITLE
choco-package-list-backup: options for installer

### ISSUE THREAD

**Issue by kintrupf** [bcurran3/ChocolateyPackages_CCR#114]
It would be great if you could add two options to the installer of this package.

1. Option to NOT create a scheduled task for this script. I have my own scheduled tasks which upgrade chocolatey packages and also call this backup script, so a separate task is not necessary.
2. Option to NOT call the backup script immediately after installation. This way we have a chance to configure the save locations before the script will backup the list to unwanted locations.

Thank you very much!

**Comment by fabiorzfreitas** [comment]
I'd like to suggest that if "1." gets implemented, it could be in a way that the user could not only choose to create or not a task, but also contemplates the task's settings as in #48 and #69 

Thank you!

Edit: It came to mind that one way this could be done is by generating a few different "task presets" (by using third-party software or not) and giving the user an option to point to which one will be applied via config file.

**Comment by bcurran3** [comment]
Wish no. 1 came true today: https://github.com/bcurran3/ChocolateyPackages/commit/3c01913be4a48881824bbd8d73587912f509d691

Wish no. 2 is easy enough and I'll add it in the future.

**Comment by bcurran3** [comment]
Wish no. 2 just came true: https://github.com/bcurran3/ChocolateyPackages/commit/b180ebbb1070d57c7bce1b7e2c904c2a7fb0d144
