### ISSUE TITLE
choco-upgrade-all-at-startup: The remote name could not be resolved: 'chocolatey.org'

### ISSUE THREAD

**Issue by collinbarrett** [bcurran3/ChocolateyPackages_CCR#117]
I'm brand new to chocolatey (don't know why it took me so long to discover/try it). And, I am trying to use `choco-upgrade-all-at-startup`.

I see the task running successfully on startup via the logs, but it appears my network connection may not yet be established. Here's a sample from `choco.summary.log` where the timestamps line up with exactly when my box was booting up. Any suggestions for ensuring that the network connection is established before this script is run? Thanks.

```
2019-09-21 12:45:36,159 3424 [INFO ] - ============================================================
2019-09-21 12:45:36,763 3424 [INFO ] - Chocolatey v0.10.15
2019-09-21 12:45:36,948 3424 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2019-09-21 12:45:36,966 3424 [INFO ] - Upgrading the following packages:
2019-09-21 12:45:36,966 3424 [INFO ] - all
2019-09-21 12:45:36,970 3424 [INFO ] - By upgrading you accept licenses for the packages.
2019-09-21 12:45:37,352 3424 [WARN ] - Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 The remote name could not be resolved: 'chocolatey.org'
2019-09-21 12:45:37,352 3424 [WARN ] - 
arq was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
2019-09-21 12:45:37,352 3424 [WARN ] - Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 The remote name could not be resolved: 'chocolatey.org'
2019-09-21 12:45:37,352 3424 [WARN ] - 
authy-desktop was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
```

...similar errors are logged for each of my installed choco packages.

```
Chocolatey upgraded 0/37 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-09-21 12:45:37,871 3424 [INFO ] - 
2019-09-21 12:45:37,871 3424 [WARN ] - Warnings:
2019-09-21 12:45:37,872 3424 [WARN ] -  - git.install - git.install was not found with the source(s) listed.
2019-09-21 12:45:37,872 3424 [WARN ] -  - slack - slack was not found with the source(s) listed.
2019-09-21 12:45:37,872 3424 [WARN ] -  - dotnet4.6.1 - dotnet4.6.1 was not found with the source(s) listed.
...
```

Thanks for the great collection of packages!

**Comment by bcurran3** [comment]
YW.

Not that it matters, but I'm guessing you're on WiFi and that's why there's no connectivity at that point. 

You can fix this easily. Just run Task Scheduler, find the choco-upgrade-all-at-startup task, go to the Conditions tab and click Start only if the following network connection is available (and choose your network connection). 

That should fix the problem. Let me know how it works out.

If you want, you can add this to the list at https://github.com/bcurran3/ChocolateyPackages/issues/69 to add that as an option in the future. Just not sure how feasible it is as I don't think it will be easy to choose the network connection on the infinite amount of network choices there will be out there.

**Comment by collinbarrett** [comment]
Thanks. I just tried a few different things.

**1. Selecting "Start only if the following network connection is available.": "Any Connection"**

![Untitled](https://user-images.githubusercontent.com/6483057/65378193-caff7f80-dca4-11e9-9add-adaadd6764fa.png)

Result: Logs show that it tried running, but had the same errors as originally stated.

**2. Selecting "Start only if the following network connection is available.": [My WiFi SSID]**

Result: Logs show that the upgrade script didn't run at all.

**3. Deselecting "Start only if the following network connection is available." and changing the "At startup" trigger to "Delay task for:" "30 seconds"**

Result: This works!

I haven't used Windows Task Scheduler a ton, but I noticed at the top of the Conditions tab, it says "The task will not run if any condition specified here is not true." It doesn't say anything like it'll try to wait until the condition is met. So, if the choco upgrade script tries to run before my WiFi is connected, I'm guessing it just cancels running. Delaying for 30 seconds seems to give it time to connect before trying to run the upgrade.

Maybe worth adding the delay to your chocolatey package? I dunno. Your call there. But, I think I'm good now.

Thanks again!

**Comment by bcurran3** [comment]
I've thought about adding the delay for just this purpose. Glad to see you verified it works for you. I might implement it as a 5 minute delay or so to make sure everything is up and running. A lot of these parameters can't be handled by schtasks.exe, so a complete re-write on creating the task is in order. :( It's on the back-burner until time allows. (The constant install, test, remove, install, test, remove kills a lot of time!)
