### ISSUE TITLE
VMware Tools 10.3.x installation can fail on certain OSes

### ISSUE THREAD

**Issue by dtrac** [bcurran3/ChocolateyPackages_CCR#118]
Hi Guys, 

As per VMware KB:

https://kb.vmware.com/s/article/55798 

Some OSes require Microsoft Visual C++ 2017 Redistributable installed prior to VMware Tools.

Should this package be added as a dependency?  

I can confirm the issue is present on 2008 R2 and 2012 R2 - resulting in an exit code of 1603

Dan

**Comment by bcurran3** [comment]
Possibly add https://chocolatey.org/packages/KB2919355 as dependency.

**Comment by bcurran3** [comment]
@dtrac is this still an issue with newer releases or just that specific version?

**Comment by bcurran3** [comment]
Closing as there's been no response and the package has been updated at least twice since the issue.
