### ISSUE TITLE
google-backup-and-sync - needs update / Hash mismatch for v3.45.5545.5747

### ISSUE THREAD

**Issue by zakaluka** [bcurran3/ChocolateyPackages_CCR#119]
Here is the error message:

```
Error - hashes do not match. Actual value was '27F364E0E7461BE3154BE9A48DA3802951E2E81F806091C1C64B8AEEA3365682'.
```

**Comment by bcurran3** [comment]
You're going to have to give me more to work with than that, like what package you're talking about that needs an update!

**Comment by zakaluka** [comment]
Oh, sorry!  I didn't realize that this is a general project (I thought it was specific to the one I was installing).

The package is `google-backup-and-sync`.

The command I ran was: `choco install google-backup-and-sync`.  After the hash mismatch, using `--ignore-checksums` allowed the installation to proceed.

**Comment by jpmahowald** [comment]
My copy of  gsync_enterprise64.msi has size 59,363,328 bytes and checksum of  '2189EC06FAF5D0AE194797C202A01CD6651BE510983E90E4DE7537F7D6BDD099'. 

The signature was OK, signing time of  ‎Thursday, ‎October ‎10, ‎2019 09:21:53.

**Comment by bcurran3** [comment]
Done!
