### ISSUE TITLE
Package "google-backup-and-sync" is out of date

### ISSUE THREAD

**Issue by hexaholic** [bcurran3/ChocolateyPackages_CCR#12]
Hash value check fails when installing google-backup-and-sync:

    Error - hashes do not match. Actual value was 'F289DDCCAFB7B0EAB59255C620D280E3B99EEB2B9114C51848B6B5A6D9923FB4'.
    ERROR: Checksum for 'C:\Users\Foo\AppData\Local\Temp\chocolatey\google-backup-and-sync\3.36.6884.5911\installbackupandsync.exe' did not meet '2C2EA0D23D37AB0A5511D4F926EF961493CB55210FBDDC5899607FD9788B7854' for checksum type 'sha256'.

Thanks for maintaining this package!

**Comment by bcurran3** [comment]
Thanks.

I put up a new version two weeks ago, unfortunately it's still under moderation.

https://chocolatey.org/packages/google-backup-and-sync/3.38.7642.3857
