### ISSUE TITLE
Resilio Install As Service Flag

### ISSUE THREAD

**Issue by EricM81** [bcurran3/ChocolateyPackages_CCR#120]
Forgive me if you can already do this, but it would be great if there was a flag to install as a service.  I have choco managing all of my clients now but have to manually upgrade the server to install as service.

**Comment by bcurran3** [comment]
Eric,
I looked into doing so in the past and there was no install option for that from the program installer. If that has changed, let me know the details please.

**Comment by bcurran3** [comment]
Looks possible with a package parameter which kicks off an AHK script...

https://help.resilio.com/hc/en-us/articles/207701296-Running-Sync-as-a-service-on-Windows

**Comment by bcurran3** [comment]
I'm not going to be maintaining this package any longer as I nor anyone I "look after" are still using it.

If you'd like to be added as a maintainer, just let me know your Chocolatey ID.
