### ISSUE TITLE
Jellyfin new version + Windows installer

### ISSUE THREAD

**Issue by laedit** [bcurran3/ChocolateyPackages_CCR#121]
The v10.4.0 of Jellyfin is out and provides a real windows installer (only x64 though).
The stable version can be found at https://repo.jellyfin.org/releases/server/windows/stable/

Is it possible to update the version of jellyfin embedded in the package and for x64 to use directly the installer?

**Comment by bcurran3** [comment]
Thanks. Looks like it's a standard installer so it should be easy to update. Will do soon as I can.

**Comment by bcurran3** [comment]
Done!

**Comment by laedit** [comment]
Thanks!
