### ISSUE TITLE
choco-cleaner: files in "\ProgramData\chocolatey\.chocolatey\"

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#124]
Is it possible to start cleaning the Chocolatey package installation files in `\ProgramData\chocolatey\.chocolatey\`? Because I have over a hundred folders for one application, I assume that the location is never cleared by Chocolatey. 

On my system only the overall size is only 25 MB after years of Chocolatey use, but the folder names can clutter system-wide searches.

**Comment by bcurran3** [comment]
Hi. Yes. This has been planned for a long time and is stated in the roadmap. It'll happen eventually.

> ###ROADMAP:
> * Clean up C:\ProgramData\chocolatey\.chocolatey
> * Clean up C:\ProgramData\chocolatey\lib-synced (licensed versions)

**Comment by opusforlife2** [comment]
@bcurran3 Any updates for this functionality?

**Comment by bcurran3** [comment]
Still only planning stages. Real life is VERY busy right now.

**Comment by bcurran3** [comment]
TBH: implementing this feature scares the hell out of me.

For the most part parsing out the packages and then deleting all but the newest directory is fairly straight forward. BUT what stops me from doing this is mixing up and handling the similarly named meta packages incorrectly; i.e. 7zip, 7zip.install, and 7zip.portable.  I have to up my RegEx game to make it work... and I've really been hoping someone else would contribute that RegEx comparison. :-)

My life is less hectic right now, I'm hoping to print up a RegEx cheat sheet to stare at and get to it.

**Comment by bcurran3** [comment]
Guess what? I pounded through it today and it's done. 

I've pushed it up as v1.0 pre-release. I'll let it soak a few days, hope for comments, and then push the official release.

`choco install choco-cleaner --version=1.0-pre --pre `

PLEASE try and give feedback.

p.s. Didn't even need to use RegEx(!) - though Remove-Item * -Exclude $string doesn't work and really had me steaming for awhile... then went a different route.

**Comment by bcurran3** [comment]
choco install choco-cleaner --version=1.0-pre2 --pre 

With a LOT more logging.

**Comment by bcurran3** [comment]
Pre3 is out. 

This should be final. 

Later in the week I'll probably do some description re-writes and then push v1.0 offical
