### ISSUE TITLE
Error installing intel-proset-drivers

### ISSUE THREAD

**Issue by h-v-r** [bcurran3/ChocolateyPackages_CCR#127]
When installing intel-proset-drivers (choco install intel-proset-drivers --ignore-checksums) I get the following warning/error:

> WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\intel-proset-drivers\tools\unzippedfiles\Setup.exe'. Please use full path for executables.
> ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"

**Comment by bcurran3** [comment]
Thanks, will investigate soon as I can.

**Comment by bcurran3** [comment]
Updated with new version:
https://chocolatey.org/packages/intel-proset-drivers/21.40.2
