### ISSUE TITLE
YakYak package checksum incorrect

### ISSUE THREAD

**Issue by gbrks** [bcurran3/ChocolateyPackages_CCR#13]
Appears the 'pre-release' versions of YakYak can change without the revision numbers changing.
Latest version (1.4.4) now currently has a sha256 checksum of: 050692e070912ce1c86a54cf717118f5d4f37d5dcac4d11d90b148bef379cd67

This is causing choco to fail.

**Comment by bcurran3** [comment]
Yeah. I hate it when developers do this!

I put this comment up on the YakYak package Disqus area:
v1.4.4 files got updated on 12/21/2017 but no new version. I'll put out a new package when a new release hits. Use --ignore-checksums until then
