### ISSUE TITLE
advancedrun: new version

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#133]
> Version 1.10
> - Added option to run as specified user name/password.
> - Be aware that the password is not saved inside the .cfg file. If you want to run as the specified user from command-line, you should specify the password using the /RunAsPassword command-line option. 

Reference: #128

**Comment by bcurran3** [comment]
Hi. Thanks. It's been sitting awaiting moderation since 11/24:
https://chocolatey.org/packages/advancedrun/1.10
