### ISSUE TITLE
choco-package-list-backup: should check if run as admin

### ISSUE THREAD

**Issue by BananaAcid** [bcurran3/ChocolateyPackages_CCR#137]
Since it needs admin privilidges, it should check and pop up uac in case it needs it.

**Comment by bcurran3** [comment]
Hi Nabil. CPLB doesn't require admin permissions.
It's possible you have destinations that do though.

**Comment by BananaAcid** [comment]
Thanks - Destinations!

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/70677627-90263b80-1c44-11ea-8cef-0b28cab43de7.png)
