### ISSUE TITLE
choco-font-extensions cannot call method on null-valued expression

### ISSUE THREAD

**Issue by cprivitere** [bcurran3/ChocolateyPackages_CCR#139]
Ok, so I use this for the inconsolata package on chocolatey. When I submitted the newer version using this module a few months ago it worked great. Now when I try to uninstall using Uninstall-ChocolateyFont I get the following error:

> WARNING: An error occured removing 'Inconsolata-Regular.ttf'.
> ERROR: You cannot call a method on a null-valued expression.
> inconsolata uninstall not successful.
> Error while running 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1'.
>  See log for details.
> inconsolata not uninstalled. An error occurred during uninstall:
>  inconsolata uninstall not successful.
> 
> Chocolatey uninstalled 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - inconsolata (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1'.
>  See log for details.

The chocolatey.log adds:

```
2019-12-13 19:42:35,632 3272 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2019-12-13 19:42:35,642 3272 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2019-12-13 19:42:35,703 3272 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'

```

Have you seen this before? I don't understand what's going on.

**Comment by cprivitere** [comment]
Ugh. This was due to trying to uninstall an already uninstalled font. Nevermind.

**Comment by cprivitere** [comment]
Nope, I take that back, while the above error was from an uninstall on a non-existant font. I'm also getting the same error trying to upgrade an existing font. Is there a particular methodology you're supposed to used during upgrades that I'm not following? 

Here's my entire chocolateyInstall.ps1 for the inconsolata package:
```
$ErrorActionPreference = 'Stop'; # stop on all errors
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$url1 = 'https://github.com/googlefonts/Inconsolata/raw/v3.000/fonts/ttf/Inconsolata-Regular.ttf'
$url2 = 'https://github.com/googlefonts/Inconsolata/raw/v3.000/fonts/ttf/Inconsolata-Bold.ttf'

Get-ChocolateyWebFile `
  -PackageName $env:ChocolateyPackageName `
  -FileFullPath $toolsDir\Inconsolata-Regular.ttf `
  -Url $url1 `
  -Checksum '127875D255D4C5973CA57267A43BB9D1C04397E6C7D236984A595B6CDCB12B7C' `
  -ChecksumType SHA256 `

Get-ChocolateyWebFile `
  -PackageName $env:ChocolateyPackageName `
  -FileFullPath $toolsDir\Inconsolata-Bold.ttf `
  -Url $url2 `
  -Checksum '263FAA57F6C00C43A04E77DF7ABD5CB5CD4AAE9F93507002C1217E02641FC7E6' `
  -ChecksumType SHA256 `


Install-ChocolateyFont $toolsDir -multiple
```

I've tried changing the last bit to the following but that just uninstalls the fonts and still errors out trying to install the new one:

```
Uninstall-ChocolateyFont Inconsolata-Regular.ttf
Uninstall-ChocolateyFont Inconsolata-Bold.ttf
Install-ChocolateyFont $toolsDir -multiple
```

What am I missing?

**Comment by bcurran3** [comment]
v0.0.2 was reworked by @teknowledgist 

Please open an issue over at https://github.com/teknowledgist/Chocolatey-packages/issues

I'm going to close this. 

If I can help out in any way, let me know. But he's the expert on v0.0.2
