### ISSUE TITLE
update every other wsl distro with wsl-fedoraremix's ChocolateyInstall.ps1, also wsl-fedoraremix is outdated (1.31.15 vs v 1.0.28.0)

### ISSUE THREAD

**Issue by drogga3** [bcurran3/ChocolateyPackages_CCR#146]
wsl-fedoraremix's ChocolateyInstall.ps1 is considerably more mature than all the other wsl distro. Why this Installer hasn't been backported?

**Comment by bcurran3** [comment]
There are a couple reasons:
1> That was the last distro packaged
2> Not all distro executables work the same; i.e. some you can run with parameters to install and some you can't (leaving the program running).
3> There haven't been updates (known to me)
4> For the most part, once you've got a distro installed, the latest version is just an apt, yum, or dnf away. Even on a latest distro of anything, there are always updates.

Now on number 3, that's only partially correct. There is a new Ubuntu 16.04.6 out and I've made a new package which is based off the latest "mature" script, but there are seemingly some issues with Chocolatey processing hashes for all the Linux files afterwards. I might be up against a bug. Waiting to find out.

I'll update the fedoraremix package next.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
