### ISSUE TITLE
CNC recurse, limit output, and ignore AU update scripts

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#147]
I have a couple of suggestions for CNC.

1. Add a recurse flag, so you can do something like `cnc -r` in the root of a packages repository and it will recurse to find `.nupec`s and run CNC for them. The one-liners in the readme are not ideal to remember. 
2. The recursion one-liners in the readme are not working for me. First, I needed to change `$.` to `$_.` Second, after that change, it does not show the output from CNC, it blanks the screen except for a press enter prompt. Running PS 5.1 on win 10
 ![image](https://user-images.githubusercontent.com/38865330/73794928-0dff5280-476f-11ea-832f-0dd607973540.png)

3. Especially if running on a repository of packages, it would be nice if there was a switch to limit the output. Suppress the suggestions, maybe FYIs, the donation message, the CNC version message, copyright. Show only warnings and required changes. Also if it is run recursed, it would be automatically limited.
 
4. It would be nice to be able to ignore `update.ps1` scripts from https://github.com/majkinetor/au
I don't necessarily want the check/changes made to those.

Anyway, thanks for the awesome tool. CNC has caught a bunch of stuff before it gets pushed. It has been especially useful when taking over an abandoned package.

**Comment by bcurran3** [comment]
I'm glad you like it. I find it useful too :), that's why I share.
Recursion is something that it really needs. It used to work the way I documented it, but then later stopped. I'm not even sure why. I need to re-write the parameters and opening files routines from scratch. If you're capable of helping, please do! 

Ignoring update.ps1 is simple and I can knock that one out easily in the near future.

**Comment by TheCakeIsNaOH** [comment]
Would you prefer the recursion to be a separate one-liner command or to be a switch that tells CNC to recurse?

**Comment by bcurran3** [comment]
Switch would be my preference, easier and more intuitive.

**Comment by TheCakeIsNaOH** [comment]
I have a working prototype here for recurse-
https://github.com/TheCakeIsNaOH/ChocolateyPackages-1/commit/8e29301c29fa9be89fc53ebf7af0ff17e80c3468

It is kind of ugly code, but it works.

Adds a recurse switch to the params. Moved the global variable definitions down into the foreach loop, since those need to be reset for each package. Moved all of the functions up so they are not re-imported for every loop. Added an if ($recurse) { then get childitems filtered to nuspec } else { use path as only folder }, then wrapped pretty much the rest of the script in a foreach loop. 

You may want to do formatting, such as indenting stuff inside the foreach loop. But that would make the difference too hard to read and understand the changes.

**Comment by bcurran3** [comment]
Update.ps1 is now ignored as of today.

**Comment by bcurran3** [comment]
Closing old issue.

Thanks for the help @TheCakeIsNaOH !

Done.
