### ISSUE TITLE
Remove ahk dependency in Irfanview

### ISSUE THREAD

**Issue by mrichards42** [bcurran3/ChocolateyPackages_CCR#15]
Irfanview can be uninstalled silently without the ahk script, if `$silentArgs` is changed to just `'/silent'`

See the last part of http://www.irfanview.com/faq.htm#Q69

Thanks for hosting all these packages!

**Comment by bcurran3** [comment]
I'm pretty sure I tried removing the AHK file and letting the Chocolatey AutoUninstaller do it's job, but it failed. I will revisit soon as I have a chance.

I would much prefer to have AHK not needed as well. If AutoUninstaller doesn't work, I'll script a normal chocolateyuninstall script to do it.

**Comment by bcurran3** [comment]
Done with the package release of v4.51
