### ISSUE TITLE
[ntlite-free] package is outdated

### ISSUE THREAD

**Issue by DJCrashdummy** [bcurran3/ChocolateyPackages_CCR#150]
just a heads up, that `ntlite-free` 1.9.x is out now for about 2 months.

**Comment by DJCrashdummy** [comment]
although the package `ntlite-free` is still not completely up to date, it now has at least a 1.9.x release...
it seems that the packaging is done manually... so there is nothing really which must be fixed, hence i'm going to close this issue.

@bcurran3 do you think it is possible to automize the packaging, that you have less work and the users get quicker updates?

**Comment by DJCrashdummy** [comment]
btw: i get a checksum error for `NTLite_setup_x64.exe`. :unamused:

**Comment by DJCrashdummy** [comment]
i just saw the "package notes": https://github.com/bcurran3/ChocolateyPackages/blob/master/ntlite-free/readme.md
...so i reopen this issue as requested by it.

**Comment by bcurran3** [comment]
Would you like to be added as a maintainer?

**Comment by bcurran3** [comment]
v1.9.0.7330 was packaged and pushed on 4/4 so I'm going to close this. 
(Though there may be a newer version yet.)

**Comment by DJCrashdummy** [comment]
sorry @bcurran3 for the late reply, i was pretty busy the last months.

i feel honored that you trust me enough to ask!
but to be honest i use windows (and therefore chocolatey) very occasionally and just for testing purposes. and on top of that i have no clue about packaging for chocolatey...

but sure, why not give you a hand every now and then, to speed things up... but to do so, please answer my questions which rose while i was looking into your repo:
- it seems that the `<version>` at `ntlite-free.nuspec` is more or less irrelevant?
https://github.com/bcurran3/ChocolateyPackages/blob/b23096a69941bb77c65e28f45ace7740e0f73c37/ntlite-free/ntlite-free.nuspec#L6
- but at `chocolateyinstall.ps1` and `ChocolateyInstall.ps1` i'm anything else but sure:
  1. why these 2 similar files in general?
  2. why there are 2 files with identical URLs (i know they are perma-links for the latest version), but different checksums?
  3. are the checksums taken from the vendor or generated somewhere else? - if taken from the vendor (which i hope), why is `sha256` specified in these files although the vendor provides only `SHA-1`?

**Comment by bcurran3** [comment]
Ignore the repo, it's completely out of whack.

If you want to help maintain, it's as simple as download the current nupkg from chocolatey.org, extract it (it's a .ZIP), edit the version and edit the checksum, run cpack, and then cpush. It's that simple.

**Comment by DJCrashdummy** [comment]
> Ignore the repo, it's completely out of whack.

ok... that explains a lot. :wink: 

> If you want to help maintain, it's as simple as download the current nupkg from chocolatey.org, extract it (it's a .ZIP), edit the version and edit the checksum, run cpack, and then cpush.

thanks a lot for pointing me at [`choco pack`](https://chocolatey.org/docs/commands-pack) and [`choco push`](https://chocolatey.org/docs/commands-push)!
it would be kind, if you can still confirm/answer the folowing:
1. ok, so `<version>` at `ntlite-free.nuspec` is not irrelevant and must be changed.
2. why aren't the checksums at `chocolateyinstall.ps1` taken from the vendor? - that would make the process easily comprehensible and completely transparent... :thinking: 
3. last but not least: is there also a possibility to contribute without having a windows running? - as said, i'm running windows just every now and then for testing... but i sometimes notice outdated choco-packages at other users machines. :expressionless:

**Comment by bcurran3** [comment]
- version in the nuspec is where you put the package version which is usually same as the program version; it is 100% relevant.
- checksums from the vendor are fine to use, just need to change the checksumtype to match. I always use and create my own SHA2565 checksums. Rob/FerventCoder has a checksum program that I use with an alias to make it simple for me (don't have to remember all the damn parameters!).
- cpack and cpush run under Windows Command Prompt, they are needed. They may/may not work with mono.

**Comment by TheCakeIsNaOH** [comment]
> last but not least: is there also a possibility to contribute without having a windows running? - as said, i'm running windows just every now and then for testing... but i sometimes notice outdated choco-packages at other users machines. 😑

Yes, it is possible @DJCrashdummy.

You can [build the docker container with it yourself](https://github.com/chocolatey/choco/tree/master/docker), or [build with mono](https://github.com/chocolatey/choco#other-platforms). There is also this [customized prebuilt container](https://hub.docker.com/r/linuturk/mono-choco), although it has a bit of weird behavior. 

I would suggest at least mono 5.20, and the mono 6.8 is working just fine personally. 

If you are building it outside of the docker container, [here are some more steps](https://github.com/chocolatey/choco/issues/2025) to get everything working properly. 

`choco pack` and `choco push` are working fine.  `cpack` and `cpush` are windows only aliases, though there is no reason you cannot recreate them in your shell if wanted. `choco install` also "works", but it only unpacks the files and does not run the powershell scripts, kind of like `nuget install`. The other commands such as `feature` and `source` are working as well, at least as far as I have tested.

**Comment by DJCrashdummy** [comment]
> I always use and create my own SHA2565 checksums. Rob/FerventCoder has a checksum program that I use with an alias to make it simple for me (don't have to remember all the damn parameters!).

i still don't get it how downloading, "verifying" the downloaded file with the vendors checksum and then creating a SHA256 of the download is easier, than just copy&pasting the vendors checksum... :thinking: but anyhow, as i hardly ever use windows i also have no clue how easy/hard it is to generate a checksum there; i'm happy with `md5sum`, `sha1sum`, `sha256sum` etc. on nearly all *nix, which usually don't need any parameter. :wink: 

> You can build the docker container with it yourself, or build with mono. There is also this customized prebuilt container, although it has a bit of weird behavior.

@TheCakeIsNaOH thanks for pointing me far down the readme... i haven't looked there so far (yet).

i'm not using docker on my everyday notebook and also try to avoid mono... but lets see if i'll start fiddling around with mono (once again), end with occasionally firing up a VM or nevertheless use docker. :expressionless: 

> cpack and cpush are windows only aliases, though there is no reason you cannot recreate them in your shell if wanted.

alias are the least issues and pretty easy to solve... if only this were the biggest issues, i'd be happy. :stuck_out_tongue_winking_eye:
