### ISSUE TITLE
choco-cleaner - add parameter to customize trigger time

### ISSUE THREAD

**Issue by collinbarrett** [bcurran3/ChocolateyPackages_CCR#151]
As some of your other choco maintenance packages (such as `choco-optimize-at`) seem to support, I would love to have access to a `/TIME` parameter to customize the `choco-cleaner` run time. My computer is usually not awake on Sunday at 11pm. I can certainly tweak it via Task Scheduler after the fact, but this would be a nice feature to add as a parameter.

I think the hard-coded `23:00` [here](https://github.com/bcurran3/ChocolateyPackages/blob/58b09568c3a7733b0f7eced74859ca9414d5b6f4/choco-cleaner/tools/chocolateyinstall.ps1#L58) would have to be substituted with a parameter somehow.

**Comment by DJCrashdummy** [comment]
fixing #48 would at least be some kind of a workaround...

**Comment by DJCrashdummy** [comment]
btw: this is a duplicate of #46.

**Comment by bcurran3** [comment]
Closing since it's a dupe.
