### ISSUE TITLE
intel-dsa new version

### ISSUE THREAD

**Issue by jacktose** [bcurran3/ChocolateyPackages_CCR#152]
According to [Intel page](https://downloadcenter.intel.com/download/28425/Intel-Driver-Support-Assistant?product=128824):
> Version: 20.2.9.6 (Latest) Date: 3/3/2020

Package is currently at 20.1.5.6 and failing checksum.

**Comment by bcurran3** [comment]
v20.2.9.6 pushed around 04/01/20
