### ISSUE TITLE
choco-cleaner uninstall leaves behind choco-cleaner.bat

### ISSUE THREAD

**Issue by jacktose** [bcurran3/ChocolateyPackages_CCR#153]
To replicate:
`choco install choco-cleaner`
`choco uninstall choco-cleaner`

Expected:
No choco-cleaner files remain.

Actual:
At least one file remains: C:\ProgramData\chocolatey\bin\choco-cleaner.bat

**Comment by bcurran3** [comment]
HA! Ironic 'eh?
Easy enough to take care of in a future version. Thanks for letting me know.

I've actually wanted to have choco-cleaner clean up the shims in bin, but I don't know a way to test the shims without running the program...

**Comment by TheCakeIsNaOH** [comment]
> I've actually wanted to have choco-cleaner clean up the shims in bin, but I don't know a way to test the shims without running the program...

This would require running the shim but does not execute the program the shim is pointing too. 
((shim_name.exe --shimgen-help) -split "`n" | sls -pattern "Target Exists").tostring() -split "'" | select -first 1 -skip 1

Returns string `true` if the target exists, `false` if the target does not exist.

**Comment by bcurran3** [comment]
Well hot diggity damn! I'll have to test that and get it into CC in the future! Thanks.

**Comment by bcurran3** [comment]
Tested. 
You da man Noah!

**Comment by bcurran3** [comment]
This issue has been resolved via https://github.com/bcurran3/ChocolateyPackages/commit/3ed8298f9aa17b6967add73c2b593809f3a173ef coming in a future release.

I'm closing this and moving the other issue of deleting shims to a new issue.
