### ISSUE TITLE
jellyfin package is out of date - latest version is 10.5.4

### ISSUE THREAD

**Issue by K900** [bcurran3/ChocolateyPackages_CCR#156]
Please let me know if there's a way I can help with getting the latest version packaged - it contains a lot of bug fixes.

**Comment by bcurran3** [comment]
I can add you as a maintainer if you want. I'm not using it, sticking to Plex.

**Comment by K900** [comment]
I'm not too familiar with the packaging process, but I can look into it and submit a PR.

**Comment by bcurran3** [comment]
No PR please.

Download package, extracted, edit files. choco pack. choco push.

easy.

**Comment by K900** [comment]
Whatever you prefer.

**Comment by bcurran3** [comment]
I'll be putting it up for a request for a new maintainer.
If you're interested, you've got first shot now.

**Comment by bcurran3** [comment]
I got a message with your id, just added you as a maintainer.
