### ISSUE TITLE
uTorrent checksum mismatch

### ISSUE THREAD

**Issue by ShowMeBillyJo** [bcurran3/ChocolateyPackages_CCR#159]
Despite the version and build information staying the same, it looks like the installer was redeployed on 10 April. Checksum verification fails.

![image](https://user-images.githubusercontent.com/179590/80854129-3fb37880-8bfb-11ea-8e9f-ff3101e92443.png)

**Comment by bcurran3** [comment]
Not really much I can do except make a non-matching package version.
Better to wait till a new version comes out.
I'm going to give step to the side on maintaining this. You want to pick it up?

**Comment by bcurran3** [comment]
I packaged up 3.5.5.45660 a few days ago/last week. So, yay, this is solved.
