### ISSUE TITLE
Prep repository for AU and to make PRs easier 

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#160]
Right now, this repository is very big(~4gb) and has a fair number of files that have the same name but different capitalization. I see from #116 that you want to start using AU.

---
The large repository size is not good for a number of reasons. The first is that it makes git slower to do things. The second is that it eats disk space and bandwidth for anyone wanting to download a copy of this repository to make changes. The third is that it is not good for AU, if you want to run AU with appveyor or another similar service. This is because appveyor downloads the entire repo every run, which takes a very long time currently. 

This large size is because of the history of all of the `.exe`s, `.nupkg`s, `.zip`s, and `.msi`s uploaded over time. Even if they are deleted in their folder they are permanently kept as history in the .git folder. This history can be cleaned out by the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/).
Posible usage example-
```
choco install bfg-repo-cleaner
git clone --mirror https://github.com/bcurran3/ChocolateyPackages.git
cd ChocolateyPackages
bfg -D '*.nupkg' .
bfg -D '*.zip' .
bfg -D '*.msi' .
bfg -D '*.exe' .
bfg -D '*.msu' .
git reflog expire --expire=now --all
git gc --prune=now --aggressive
git push
```
---
In regards to the duplicate file names with different cases, and example is [3dmark](https://github.com/bcurran3/ChocolateyPackages/tree/master/3dmark/tools) where you have both `ChocolateyInstall.ps1` and `chocolateyinstall.ps1` 

This is a pain to deal with if you download on windows because the combination of  windows+git+files with different cases does not play nicely together. Windows by default is case insensitive so git gets confused and thinks there are changes when there are not changes. The only workaround is to manually add the correct files to the commit rather then just adding everything. This is an extra setup on for normal users. And for AU, it is not really workable since AU on appveyor just commits all changes. 

This can be fixed by deleting all extra copies of files with different cases. It should be pretty easy, just delete the file with the older date and leave the file with the newer date. 
<details>
<summary>list of duplicate files with different cases</summary>

```
/3dmark/tools/chocolateyinstallps1
/8gadgetpack/tools/chocolateyinstallps1
/8x8virtualoffice/tools/chocolateyinstallps1
/advanced-codecs/tools/chocolateyinstallps1
/advanced-codecs/tools/chocolateyuninstallps1
/allway-sync/tools/chocolateyinstallps1
/allwemo/tools/chocolateyinstallps1
/amazondrive/tools/chocolateyinstallps1
/ammyy-admin/tools/chocolateyinstallps1
/ammyy-admin/tools/chocolateyuninstallps1
/angryip/tools/chocolateyinstallps1
/arq/tools/chocolateyinstallps1
/backupper-server/tools/chocolateyinstallps1
/backupper-standard/tools/chocolateyinstallps1
/choco-cleaner/tools/choco-cleaner-manualbat
/choco-cleaner/tools/choco-cleanerps1
/choco-cleaner/tools/choco-cleanerxml
/choco-cleaner/tools/chocolateyinstallps1
/choco-cleaner/tools/chocolateyuninstallps1
/choco-optimize-at/tools/chocolateyinstallps1
/choco-optimize-at/tools/chocolateyuninstallps1
/choco-upgrade-all-at-startup/tools/chocolateyinstallps1
/choco-upgrade-all-at-startup/tools/chocolateyuninstallps1
/cms-magic-series/tools/chocolateyinstallps1
/dell-platform-tags-utility/tools/chocolateyinstallps1
/dokany/tools/chocolateyinstallps1
/drivermax/tools/chocolateyinstallps1
/drivermax/tools/chocolateyuninstallps1
/dsinternals-psmodule/tools/chocolateyinstallps1
/dsinternals-psmodule/tools/chocolateyuninstallps1
/dual-monitor-tools/tools/chocolateyinstallps1
/duplicatiportable/readmemd
/duplicati/readmemd
/duplicati/tools/chocolateyinstallps1
/ellp/tools/chocolateyinstallps1
/font-awesome-font/tools/chocolateyinstallps1
/futuremark-systeminfo/tools/chocolateyinstallps1
/getdataback-simple/tools/chocolateyinstallps1
/go-contact-sync-mod/tools/chocolateyinstallps1
/google-play-music-manager/tools/chocolateyinstallps1
/google-web-designer/tools/chocolateyinstallps1
/gptgen/tools/chocolateyinstallps1
/gpu-z/tools/chocolateyinstallps1
/gpu-z/tools/chocolateyuninstallps1
/grub2win/tools/chocolateyinstallps1
/grub2win/tools/g2winstallahk
/gsuite-sync-outlook/tools/chocolateyinstallps1
/hdhomerun-view/tools/chocolateyinstallps1
/intel-dsa/tools/chocolateyinstallps1
/intel-network-drivers-win10/tools/chocolateyInstallps1
/kmttg/tools/chocolateyinstallps1
/kmttg/tools/chocolateyuninstallps1
/lanbench/tools/chocolateyinstallps1
/lanbench/tools/chocolateyuninstallps1
/logitech-options/tools/chocolateyinstallps1
/logitech-options/tools/chocolateyUninstallps1
/mame/tools/chocolateyinstallps1
/mame/tools/chocolateyuninstallps1
/netdrive/tools/chocolateyinstallps1
/netstat-viewer/tools/chocolateyinstallps1
/netstat-viewer/tools/chocolateyuninstallps1
/nfopadportable/tools/chocolateyInstallps1
/nfopad/tools/chocolateyInstallps1
/ntfssecurity-psmodule/tools/chocolateyinstallps1
/ntfssecurity-psmodule/tools/chocolateyuninstallps1
/ntlite-free/tools/chocolateyinstallps1
/openhab/tools/chocolateyinstallps1
/openhab/tools/chocolateyuninstallps1
/open-visual-traceroute/tools/chocolateyinstallps1
/pcmark8/tools/chocolateyinstallps1
/plexmediaplayer/tools/chocolateyinstallps1
/pytivo-desktop/tools/chocolateyinstallps1
/pytivo-wmcbrine/tools/chocolateyinstallps1
/pytivo-wmcbrine/tools/chocolateyuninstallps1
/qdir/tools/chocolateyInstallps1
/qdir/tools/chocolateyUninstallps1
/raidar/raidar_iconpng
/raidar/tools/chocolateyinstallps1
/raidar/tools/chocolateyuninstallps1
/rdpguard/tools/chocolateyinstallps1
/realtek-hd-audio-driver/tools/chocolateyinstallps1
/resilio-sync-business/tools/chocolateyinstallps1
/resilio-sync-home/tools/chocolateyinstallps1
/rocketdock/tools/chocolateyInstallps1
/roost-desktop-notifier-for-nest/tools/chocolateyinstallps1
/sardu/tools/chocolateyinstallps1
/sardu/tools/chocolateyuninstallps1
/seagate-drive-detect/tools/chocolateyinstallps1
/seagate-drive-detect/tools/chocolateyuninstallps1
/seatools/tools/chocolateyinstallps1
/setpoint/tools/chocolateyinstallps1
/simple-sticky-notes/tools/chocolateyinstallps1
/siv/tools/chocolateyinstallps1
/siv/tools/chocolateyuninstallps1
/stinger/tools/chocolateyinstallps1
/stinger/tools/chocolateyuninstallps1
/take-command/tools/chocolateyinstallps1
/taskbar-winconfig/tools/chocolateyinstallps1
/taskschedulerview/tools/chocolateyinstallps1
/taskschedulerview/tools/chocolateyuninstallps1
/tautulli/tools/chocolateyinstallps1
/tautulli/tools/chocolateyuninstallps1
/teamspeak-server/tools/chocolateyinstallps1
/teamspeak-server/tools/chocolateyuninstallps1
/trafficlight-firefox/tools/chocolateyInstallps1
/trafficlight-firefox/tools/chocolateyUninstallps1
/trojan-remover/tools/chocolateyinstallps1
/utorrent/tools/chocolateyinstallps1
/utorrent/tools/chocolateyuninstallps1
/vboxguestadditionsinstall/vboxguestadditionsinstallnuspec
/vmware-powercli-psmodule/tools/chocolateyinstallps1
/vmware-powercli-psmodule/tools/chocolateyuninstallps1
/vnc-connect/tools/chocolateyinstallps1
/vnc-viewer/tools/chocolateyinstallps1
/vnc-viewer/tools/chocolateyuninstallps1
/winaero-tweaker/tools/chocolateyinstallps1
/windows-10-update-assistant/tools/chocolateyinstallps1
/windows-iso-downloader/tools/chocolateyinstallps1
/windows-iso-downloader/tools/chocolateyuninstallps1
/winflector-client/tools/chocolateyinstallps1
/winflector-client/tools/chocolateyuninstallps1
/winflector/tools/chocolateyinstallps1
/winhue/tools/chocolateyinstallps1
/yakyak/tools/chocolateyinstallps1
/yakyak/tools/chocolateyuninstallps1
```

</details>

**Comment by TheCakeIsNaOH** [comment]
Perhaps if you are wanting to nuke this repository, you could archive it instead to keep a history of changes.

At the same time making a new repository for AU packages, and as you go through packages and make AU scripts you can move them to the new repository. Then for packages that you are no longer wanting to maintain, you can put them up for adoption a the packages requests repository.

**Comment by bcurran3** [comment]
Thanks for all the great advice.
I will look into it and do SOMETHING hopefully in the near future.

**Comment by bcurran3** [comment]
This scares me:
git clone --mirror https://github.com/bcurran3/ChocolateyPackages.git

Isn't that going to pull down from GH the files there and overwrite my local ones?

What I really need is the command to force my local files to upload and replace anything on GH.

**Comment by TheCakeIsNaOH** [comment]
> Isn't that going to pull down from GH the files there and overwrite my local ones?

It could if you did it in the same directory as your local one. I was assuming doing it in a different location. You keep your local repository, and clone a separate copy in a different directory. 

> What I really need is the command to force my local files to upload and replace anything on GH.

`git push --force $remoteRepoName` 
You will need to first configure git to have the remote repository if not already set up by doing a `git remote add $remoteRepoName $remoteRepoURL`

**Comment by bcurran3** [comment]
Hmmmmmmmm. I have multiple backups of the local repo zipped up from these situations. I've deleted the GH repo probably twice and repushed everything back up. It's basically the way I planned to do it unless there was an easier way.

I like the idea of forcing my current repo back up and over the remote one (this one right here)... but still leaves the cleanup on it to be done. The duplicate files with different case being the biggest PITA to deal with.

**Comment by bcurran3** [comment]
--force didn't work so well. I know I tried this in the past, don't know if I got the same error back then or not.
EDIT: Yeah, the remote end hung up seems familiar. I'm sure this is the problem I've constantly had.

> PS S:\dev\GitHub\ChocolateyPackages> git push --force
> Enumerating objects: 20105, done.
> Counting objects: 100% (20105/20105), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (8056/8056), done.
> error: RPC failed; curl 18 transfer closed with outstanding read data remaining
> fatal: the remote end hung up unexpectedly
> Writing objects: 100% (20105/20105), 4.02 GiB | 11.32 MiB/s, done.
> Total 20105 (delta 11538), reused 19701 (delta 11322), pack-reused 0
> fatal: the remote end hung up unexpectedly
> Everything up-to-date
> PS S:\dev\GitHub\ChocolateyPackages>

**Comment by TheCakeIsNaOH** [comment]
Hmm. Maybe try cleaning your local repository first? Zip a backup first.
It seems to be related to large repositories.
 https://stackoverflow.com/questions/15240815/git-fatal-the-remote-end-hung-up-unexpectedly

**Comment by bcurran3** [comment]
I THINK I've got it synced again and up to date. Not ready to "announce" it, but I think I'm good. Hell, have to remember how to use git again. 👍 

I ran this: https://chocolatey.org/packages/bfg-repo-cleaner
and I cleaned up all the files locally that didn't need to sync (zip/exe/msi/nupkg - where I had already excluded but not excluded at the beginning of git-time.)

I'll run with it for a bit and see how things go.

**Comment by TheCakeIsNaOH** [comment]
> Hell, have to remember how to use git again

I found (and still find) Github desktop to be really nice for picking which things to commit. I still use the CLI for other things, but a GUI is nice for seeing and picking changes.
https://desktop.github.com/

For making sure binaries don't get committed, you might want to add a `.gitignore` file.
My repo gitignore: https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/.gitignore

**Comment by bcurran3** [comment]
I've had GitHub Desktop installed for years, but I think I've run it once. Easier for me to use the CLI.

.gitignore edited and all the exclusions added long ago (years) - problem is stuff in the repo pushed before that still exists and causes problems. Think I really need to delete and re-push the whole repo to dump all the extraneous crap!

**Comment by koolhand** [comment]
> and has a fair number of files that have the same name but different capitalization

I submitted pull request #191 to deal with _most_ of those duplicates. Five remaining which I thought needed your eyes over them to work out which duplicate was the right one to keep - I'll leave those in your hands.

For easy editing in your browser, The Final Five...

![The Final Five](https://media0.giphy.com/media/h80oJHFzlKO4IsVCJE/giphy.gif)

1. [dell-platform-tags-utility](https://github.com/bcurran3/ChocolateyPackages/tree/master/dell-platform-tags-utility/tools)
2. [gptgen](https://github.com/bcurran3/ChocolateyPackages/tree/master/gptgen/tools)
3. [rocketdock](https://github.com/bcurran3/ChocolateyPackages/tree/master/rocketdock/tools)
4. [roost-desktop-notifier-for-nest](https://github.com/bcurran3/ChocolateyPackages/tree/master/roost-desktop-notifier-for-nest/tools)
5. [seatools](https://github.com/bcurran3/ChocolateyPackages/tree/master/seatools/tools)

Beers donated ;)

**Comment by TheCakeIsNaOH** [comment]
Thanks, @koolhand, git is no longer complaining about changed files.


The repository history is quite large still, about 4.74gb with a fresh `git pull`

I tested this command sequence in cmd on a windows 10 machine, and it brought the repository size down to about 35mb. You would need to force push up to GitHub, but I have used BFG a number of times with no problems, and it keeps the latest HEAD commit intact, so you would not lose the current state of your files when you pull again.
```
choco install bfg-repo-cleaner
git clone --mirror https://github.com/bcurran3/ChocolateyPackages.git
cd ChocolateyPackages.git
bfg -D *.nupkg .
bfg -D *.zip .
bfg -D *.msi .
bfg -D *.exe .
bfg -D *.msu .
bfg -D *.rar .
git reflog expire --expire=now --all
git gc --prune=now --aggressive
```

**Comment by bcurran3** [comment]
Are you saying there are still nupkg, zip, etc files in the repo? They're all in my exclusion list (but weren't two or three years ago). I deleted them locally a long time ago and pushed the changes. 

I just ran bfg and cleaned it up. Funny as I thought all those files were deleted long ago.

Thanks!

![image](https://user-images.githubusercontent.com/14026600/94627437-5de8d780-0272-11eb-8115-f09e1d012d45.png)

**Comment by TheCakeIsNaOH** [comment]
That won't work. You have to force push before you pull. `git push --force`

The repository still has the nupkg, zip, etc files in it , both in Github and in your local repository because you pulled the changes before force pushing.

**Comment by bcurran3** [comment]
Something's disconnected between what your saying and I'm seeing.

Example:
In my local repo I have the 7 .ZIP files from the 4 packages I have recently updated. My GH repo has 0 of those ZIPs. (mrboom, qdir, siv, and taskschedulerview)

In the screenshot above you'll see I did a git push and it complained saying I needed to do a git pull.

**Comment by bcurran3** [comment]
In case this helps:
(What happened before the screenshot)


> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.nupkg .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> 
> Found 2291 objects to protect
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
>  * commit f5db7a0c (protected by 'HEAD')
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 6,171 ms.
> 
> Updating 2 Refs
> ---------------
> 
>         Ref                          Before     After
>         ------------------------------------------------
>         refs/heads/master          | f5db7a0c | c63bf66e
>         refs/remotes/origin/master | f5db7a0c | c63bf66e
> 
> Updating references:    100% (2/2)
> ...Ref update completed in 61 ms.
> 
> Commit Tree-Dirt History
> ------------------------
> 
>         Earliest                                              Latest
>         |                                                          |
>         ........................................................Dmmm
> 
>         D = dirty commits (file tree fixed)
>         m = modified commits (commit message or parents changed)
>         . = clean commits (no changes to file tree)
> 
>                                 Before     After
>         -------------------------------------------
> 
> Deleted files
> -------------
> 
>         Filename                                           Git id
>         --------------------------------------------------------------------
>         8x8virtualoffice.6.2.4.4.nupkg                   | eb34d093 (4.8 KB)
>         siv.5.40.nupkg                                   | bfce4296 (6.6 MB)
>         stinger.12.1.0.3231.nupkg                        | 9f76288e (5.6 KB)
>         windows-10-update-assistant.1.4.9200.22808.nupkg | bdfe152d (4.4 KB)
>         windows-sandbox.0.0.1.nupkg                      | 6be4c469 (4.8 KB)
> 
> 
> In total, 111 object ids were changed. Full details are logged here:
> 
>         S:\dev\GitHub\ChocolateyPackages\..bfg-report\2020-09-29\16-24-11
> 
> BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://github.com/bkeepers/stop-trump
> --
> 
> 
> PS S:\dev\GitHub\ChocolateyPackages>
> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.zip .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> 
> Found 2291 objects to protect
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
>  * commit c63bf66e (protected by 'HEAD')
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 52,459 ms.
> 
> Updating 2 Refs
> ---------------
> 
>         Ref                          Before     After
>         ------------------------------------------------
>         refs/heads/master          | c63bf66e | 3eed0cb0
>         refs/remotes/origin/master | c63bf66e | 3eed0cb0
> 
> Updating references:    100% (2/2)
> ...Ref update completed in 87 ms.
> 
> Commit Tree-Dirt History
> ------------------------
> 
>         Earliest                                              Latest
>         |                                                          |
>         DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDmmmm
> 
>         D = dirty commits (file tree fixed)
>         m = modified commits (commit message or parents changed)
>         . = clean commits (no changes to file tree)
> 
>                                 Before     After
>         -------------------------------------------
>         First modified commit | 5d06fa7b | 916fe633
>         Last dirty commit     | f7baf8b8 | bfb0a60a
> 
> Deleted files
> -------------
> 
>         Filename                                     Git id
>         -------------------------------------------------------------------------------------------------------
>         ADPhotoEditSetup.zip                       | 2b3f81e0 (804.4 KB)
>         AtomicParsley-0.9.6-hg109.9183fff907bf.zip | 29f3f168 (179.8 KB)
>         AtomicParsley-win32-0.9.0.zip              | e2f7c758 (438.9 KB)
>         Q-Dir_Installer.zip                        | 377d0dfc (623.4 KB), 5e62ffa6 (644.3 KB), ...
>         Q-Dir_Installer_x64.zip                    | c779115e (1.0 MB), b57fe900 (1010.3 KB), ...
>         Reprofiler2.zip                            | 412b35ef (1.7 MB)
>         VLCSkinEditor_w32.zip                      | b164a069 (800.3 KB)
>         asteroids.zip                              | 70dc8d60 (1.5 MB)
>         blinky.zip                                 | baa12056 (1.8 MB)
>         blitz.zip                                  | 47c9da02 (1.4 MB)
>         bunnyhop.zip                               | c45a405c (903.4 KB)
>         burgertime.zip                             | 1bd3a498 (4.7 MB)
>         centipede.zip                              | 39170759 (2.8 MB)
>         command.zip                                | 58057f45 (2.1 MB)
>         ...
> 
> 
> In total, 3950 object ids were changed. Full details are logged here:
> 
>         S:\dev\GitHub\ChocolateyPackages\..bfg-report\2020-09-29\16-24-55
> 
> BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://github.com/bkeepers/stop-trump
> --
> 
> 
> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.msi .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> 
> Found 2291 objects to protect
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
>  * commit 3eed0cb0 (protected by 'HEAD')
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 56,905 ms.
> 
> Updating 2 Refs
> ---------------
> 
>         Ref                          Before     After
>         ------------------------------------------------
>         refs/heads/master          | 3eed0cb0 | c94ad5ca
>         refs/remotes/origin/master | 3eed0cb0 | c94ad5ca
> 
> Updating references:    100% (2/2)
> ...Ref update completed in 67 ms.
> 
> Commit Tree-Dirt History
> ------------------------
> 
>         Earliest                                              Latest
>         |                                                          |
>         ....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDmmmmmmDmmmmmmm
> 
>         D = dirty commits (file tree fixed)
>         m = modified commits (commit message or parents changed)
>         . = clean commits (no changes to file tree)
> 
>                                 Before     After
>         -------------------------------------------
>         First modified commit | b7c05fad | c985c912
>         Last dirty commit     | b52c9a21 | 7bd02eca
> 
> Deleted files
> 
>         Filename                Git id
>         -----------------------------------------------------------------
>         AllWemo.msi           | d97ed57d (1.6 MB), c9eaf6d1 (1.5 MB), ...
>         AllWemoSetup.msi      | 16d7c6e8 (1.4 MB)
>         FileBot_4.7.9_x86.msi | e9dafec1 (25.0 MB)
>         SetupGCSM-3.10.21.msi | 2b505b0a (3.7 MB)
>         SetupGCSM-3.10.22.msi | 379b20b3 (3.7 MB)
>         SetupGCSM-3.10.23.msi | 71cd293e (3.7 MB)
>         SetupGCSM-3.10.26.msi | 2c53f059 (3.7 MB)
>         SetupGCSM-3.10.38.msi | 77172fc9 (3.8 MB)
>         SetupGCSM-3.10.40.msi | 18bfd5bd (3.8 MB)
> 
> 
> In total, 3125 object ids were changed. Full details are logged here:
> 
>         S:\dev\GitHub\ChocolateyPackages\..bfg-report\2020-09-29\16-26-13
> 
> BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://www.aclu.org/
> --
> 
> 
> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.exe .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> 
> Found 2291 objects to protect
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
>  * commit c94ad5ca (protected by 'HEAD')
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 65,682 ms.
> 
> Updating 2 Refs
> ---------------
> 
>         Ref                          Before     After
>         ------------------------------------------------
>         refs/heads/master          | c94ad5ca | 75dd8239
>         refs/remotes/origin/master | c94ad5ca | 75dd8239
> 
> Updating references:    100% (2/2)
> ...Ref update completed in 67 ms.
> 
> Commit Tree-Dirt History
> ------------------------
> 
>         Earliest                                              Latest
>         |                                                          |
>         DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDmmmm
> 
>         D = dirty commits (file tree fixed)
>         m = modified commits (commit message or parents changed)
>         . = clean commits (no changes to file tree)
> 
>                                 Before     After
>         -------------------------------------------
>         First modified commit | 82d8750a | cff871b6
>         Last dirty commit     | 4feae813 | 06bd02bc
> 
> Deleted files
> -------------
> 
>         Filename                              Git id
>         ---------------------------------------------------------------------------------------------------
>         AA_v3.exe                           | b1d56a1f (774.1 KB), 322211e3 (755.5 KB), 0f02cfea (762.1 KB)
>         ADVANCED_Codecs_v1062.exe           | b22bd1bb (73.3 MB)
>         ADVANCED_Codecs_v1067.exe           | 731df32b (65.0 MB)
>         ADVANCED_Codecs_v1076.exe           | 36b26c89 (65.1 MB)
>         ADVANCED_Codecs_v1083.exe           | 853233d0 (65.1 MB)
>         ADVANCED_Codecs_v1084.exe           | 00c4b007 (65.3 MB)
>         ADVANCED_Codecs_v1086.exe           | 6b1f74a5 (65.2 MB)
>         ADVANCED_Codecs_v1090.exe           | 09e9b702 (65.1 MB)
>         ADVANCED_Codecs_v1092.exe           | 6b4d0a99 (65.1 MB)
>         ADVANCED_Codecs_v1094.exe           | 2e63f5f0 (65.3 MB)
>         ADVANCED_Codecs_v1095.exe           | 7a8dc72b (65.2 MB)
>         ADVANCED_Codecs_v1096.exe           | 84d50a75 (65.1 MB)
>         ADVANCED_Codecs_v1097.exe           | 4fa44d2d (65.3 MB)
>         ForcePS.exe                         | e1be92a8 (81.1 KB), d6f545cd (153.2 KB), 330163d5 (153.2 KB)
>         ...
> 
> 
> In total, 4034 object ids were changed. Full details are logged here:
> 
>         S:\dev\GitHub\ChocolateyPackages\..bfg-report\2020-09-29\16-27-36
> 
> BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://www.aclu.org/
> --
> 
> 
> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.msu .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> Found 2291 objects to protect
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
>  * commit 75dd8239 (protected by 'HEAD')
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 8,943 ms.
> 
> BFG aborting: No refs to update - no dirty commits found??
> 
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://www.rescue.org/topic/refugees-america
> --
> 
> 
> PS S:\dev\GitHub\ChocolateyPackages> bfg -D *.appx .
> 
> Using repo : S:\dev\GitHub\ChocolateyPackages\.\.git
> Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master
> 
> Protected commits
> -----------------
> 
> These are your protected commits, and so their contents will NOT be altered:
> 
> 
> Cleaning
> --------
> 
> Found 1983 commits
> Cleaning commits:       100% (1983/1983)
> Cleaning commits completed in 10,056 ms.
> 
> 
> 
> 
> --
> You can rewrite history in Git - don't let Trump do it for real!
> Trump's administration has lied consistently, to make people give up on ever
> being told the truth. Don't give up: https://www.aclu.org/
> --
>

**Comment by TheCakeIsNaOH** [comment]
Hmm, let me reword/re-explain.

I just did a fresh git clone of the GH repository. It was about 1.7gb, which is still big.
I ran `bfg -D '*.exe' .` on the fresh clone, and here are the results. 
```
Found 2291 objects to protect
Found 4 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, refs/remotes/origin/master

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 4f91323e (protected by 'HEAD')

Cleaning
--------

Found 3967 commits
Cleaning commits:       100% (3967/3967)
Cleaning commits completed in 8,160 ms.

Updating 2 Refs
---------------

        Ref                          Before     After
        ------------------------------------------------
        refs/heads/master          | 4f91323e | 47030f5a
        refs/remotes/origin/master | 4f91323e | 47030f5a

Updating references:    100% (2/2)
...Ref update completed in 48 ms.

Commit Tree-Dirt History
------------------------

        Earliest                                              Latest
        |                                                          |
        DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDmmmm

        D = dirty commits (file tree fixed)
        m = modified commits (commit message or parents changed)
        . = clean commits (no changes to file tree)

                                Before     After
        -------------------------------------------
        First modified commit | 48da2147 | 99a273b0
        Last dirty commit     | 3c30e1cf | 376c0650

Deleted files
-------------

        Filename                              Git id
        ---------------------------------------------------------------------------------------------------
        AA_v3.exe                           | b1d56a1f (774.1 KB), 322211e3 (755.5 KB), 0f02cfea (762.1 KB)
        ADVANCED_Codecs_v1062.exe           | b22bd1bb (73.3 MB)
        ADVANCED_Codecs_v1067.exe           | 731df32b (65.0 MB)
        ADVANCED_Codecs_v1074.exe           | b08ac153 (65.0 MB)
        ADVANCED_Codecs_v1076.exe           | 36b26c89 (65.1 MB)
        ADVANCED_Codecs_v1083.exe           | 853233d0 (65.1 MB)
        ADVANCED_Codecs_v1084.exe           | 00c4b007 (65.3 MB)
        ADVANCED_Codecs_v1086.exe           | 6b1f74a5 (65.2 MB)
        ADVANCED_Codecs_v1090.exe           | 09e9b702 (65.1 MB)
        ADVANCED_Codecs_v1092.exe           | 6b4d0a99 (65.1 MB)
        ADVANCED_Codecs_v1094.exe           | 2e63f5f0 (65.3 MB)
        ADVANCED_Codecs_v1095.exe           | 7a8dc72b (65.2 MB)
        ADVANCED_Codecs_v1096.exe           | 84d50a75 (65.1 MB)
        ADVANCED_Codecs_v1097.exe           | 4fa44d2d (65.3 MB)
        ForcePS.exe                         | e1be92a8 (81.1 KB), d6f545cd (153.2 KB), 330163d5 (153.2 KB)
        ...


In total, 4036 object ids were changed. Full details are logged here:

       ChocolateyPackages/..bfg-report/2020-09-30/08-34-41

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

That shows that there are still `.exe` files in the GH repository history. The files are not visible in the normal folders, but are in the git history, still taking up space. I also saw `.nupkg`s , `.msi`s, and `.zips`, in the history as well. Running `bfg -D *.filetype .` will will set it up to remove it from history on the local repository, and the `git reflog expire` and `git gc` commands will do the actual cleanup. That part is fine.

Then, the rewritten git history needs to be pushed to Github. To remove the unwanted files from the history on GH, the rewritten history from your local repository needs to be pushed to GH to overwrite the old history. What actually happened was that `git push` detected that the history on the local repository was different from the history on the GH repository, and tried to protect you from overwriting things on the remote. To actually push the rewritten history, you need to use `git push --force`.
![image](https://user-images.githubusercontent.com/38865330/94693334-32f59680-02f9-11eb-80f3-9d8b063a0a98.png)

What you actually did was run a git pull first. 
![image](https://user-images.githubusercontent.com/38865330/94694145-2291eb80-02fa-11eb-8bf9-ec1037b81365.png)

This did something called a merge. It pulled the old history from GH, and combined that history with the rewritten history in your local repository. 
![image](https://user-images.githubusercontent.com/38865330/94694300-4ead6c80-02fa-11eb-9266-6a9fb52fcce3.png)

Then you ran git push. The problem is that the history on your local repository is combined of the original history, and of your rewritten history. 
![image](https://user-images.githubusercontent.com/38865330/94694443-76043980-02fa-11eb-8aaf-34bafd2e4c27.png)


So both your local repository and GH still have the original history that includes the unwanted files.

**Comment by bcurran3** [comment]
Thanks. That helped a lot.

I just bfg -d'd exes, msis, and nupkgs. Did the other commands and pushed, So hopefully all better now!

**Comment by TheCakeIsNaOH** [comment]
Looks good to me 😄 
![image](https://user-images.githubusercontent.com/38865330/99337845-b38c3a00-2848-11eb-9f72-08dbe2a47677.png)

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/99341403-a5d1b700-283e-11eb-904a-30dd26cd2782.png)

**Comment by bcurran3** [comment]
BFG -D just saved my butt again.
(I didn't have .7z excluded and commit a large file on accident. I've been on "hold" about two weeks because of it.)

**Comment by koolhand** [comment]
BFG is great.
