### ISSUE TITLE
Please add options for the Java dependancy in the Angry IP Scanner Chocolatey package

### ISSUE THREAD

**Issue by ctminime** [bcurran3/ChocolateyPackages_CCR#161]
Angry IP Scanner works just fine with AdoptOpenJDK 11 openj9 or Hotspot. Since Oracle Java is no longer free, these are much better alternatives.

I am sure any of these chocolatey packages would work:
openjdk8
openjdk11
adoptopenjdk11
adoptopenjdk11openj9
adoptopenjdk11jre
adoptopenjdk11openj9jre
adoptopenjdk8
adoptopenjdk8openj9
adoptopenjdk8jre
adoptopenjdk8openj9jre

I personally use AdoptOpenJDK11openj9 and I have no issues.

Using AdoptOpenJDK is supported by Angry IP but requires enabling "JavaSoft (Oracle) registry keys".

https://angryip.org/download/#windows

The real question is, which one should be default? In my personal opinion, it should definitely not be Oracle Java (javaruntime).

**Comment by TheCakeIsNaOH** [comment]
Duplicate of #142

**Comment by ctminime** [comment]
Whoops, sorry about the dupe. I thought I looked but apparently not.

**Comment by bcurran3** [comment]
closing as dupe
