### ISSUE TITLE
[choco-cleaner] Log file

### ISSUE THREAD

**Issue by rnc** [bcurran3/ChocolateyPackages_CCR#162]
Does it create a log file upon running ? (ideally in a configurable location ? )

**Comment by bcurran3** [comment]
Nopers, only the info displayed to the console.

I'm not against logging (and I'm lazy), but it's just a tiny script that can be run again in 30 seconds for the info. I really don't see the need for any logging. With that said, I'd welcome it if someone wants to add that into the code.
