### ISSUE TITLE
[choco-cleaner] Installation

### ISSUE THREAD

**Issue by rnc** [bcurran3/ChocolateyPackages_CCR#163]
Hi. Is the installation / configuration configurable ? For instance, I would like to install but not create a scheduled task, but just to run on demand. This is especially useful if I am setting up a machine via Ansible scripts and want to cleanup at end (but not leave a task running).

**Comment by bcurran3** [comment]
Not at the moment. It wouldn't be an unreasonable enhancement. For the meantime I'd suggest just removing the task from the list of scheduled tasks. I'm willing to add a -noschedule or similar switch if you really want it... wouldn't be that hard.
