### ISSUE TITLE
HFSExplorer missing dependency

### ISSUE THREAD

**Issue by moomoohk** [bcurran3/ChocolateyPackages_CCR#166]
[HFSExplorer](https://chocolatey.org/packages/hfsexplorer) depends on [Java Runtime](https://chocolatey.org/packages/javaruntime) however the dependency is not specified by the package.
Ran into this issue when installing hfsexplorer on a clean OS with no javaruntime. Tried running HFSExplorer and got an error indicating the missing Java Runtime. I installed javaruntime and then tried again and it worked.

**Comment by bcurran3** [comment]
Good find. Thanks @moomoohk . Where were you four years ago? :)

**Comment by moomoohk** [comment]
Using a Mac :D

**Comment by bcurran3** [comment]
I pushed a new version with the javaruntime dependency. I did ya one better too, the binary is now included in the package. Overhauled the whole thing to my "modern standard."
Done
You can test with choco install --version 0.23.1.20200909

BE SURE TO READ THE PACKAGE NOTES; e.g. will not "upgrade" silently.
