### ISSUE TITLE
No new updates for YakYak?

### ISSUE THREAD

**Issue by kix2902** [bcurran3/ChocolateyPackages_CCR#167]
Hello BIll,

I installed YakYak from your chocolatey package but now it's not working because Google changed the server response and broke the app.

I've made a research and it seems that in the 1.5.7 version that bug is fixed but in chocolatey is available the 1.5.4 version so I updated your script for the app in this gist for you to copy directly if you want https://gist.github.com/kix2902/21678b03ad8eae0bbcba7a3ab33d28f3

**Comment by bcurran3** [comment]
Thanks for making it easy for me.

I don't use this or plan to maintain it any longer.  If you'd like to maintain it, let me know your Chocolatey ID.

**Comment by kix2902** [comment]
I haven't uploaded any package to chocolatey before, and I have almost no available time. I will research a bit about the process and if I think I could maintain it I will contact you.

**Comment by bcurran3** [comment]
You've already done most of it... just after you edited the file; e.g. your gist, you do a cpack and a cpush. (Need to edit the .nuspec with the new version # as well, and one time set your API key.) Very easy to maintain.

**Comment by kix2902** [comment]
Hmmm, I'll give a try... my username in Chocolatey is kix2902

**Comment by bcurran3** [comment]
Done.
(Really, it IS easy.)
