### ISSUE TITLE
Package resilio-sync-home is outdated, new version info

### ISSUE THREAD

**Issue by fraencko** [bcurran3/ChocolateyPackages_CCR#169]
Package: https://chocolatey.org/packages/resilio-sync-home

Version in Repository: 2.6.3.1340
Latest version: 2.7.1.1370

32-bit version: https://download-cdn.resilio.com/stable/windows/Resilio-Sync.exe
SHA-256: 7C00F67FDB170602B5103E193FB2F79F6C909AA74661F063B28F67665F7785B9

64-bit version: https://download-cdn.resilio.com/stable/windows64/Resilio-Sync_x64.exe
SHA-256: E3BD30BC0860061970EECFEB51E4088C5074B769E9EA0151F757E731930B5E56

Hope this helps. If there's anything I can do to improve this GitHub issue, please let me know.

**Comment by bcurran3** [comment]
I don't use this program and don't plan on maintaining the package anymore. If you'd like to become the maintainer, let me know your Chocolatey ID and I'll make it so.

With that said, you made it soooooooo easy for me to update, I did.

RE: GitHub - much appreciated. It's on the back burner for the moment.
