### ISSUE TITLE
Suggestion: choco-list-backup: export date (and time?) as part of the packages export file

### ISSUE THREAD

**Issue by SeanKilleen** [bcurran3/ChocolateyPackages_CCR#17]
Love your script -- was a much more robust version of one I'd written some time ago. Thanks for putting it on Nuget.

I'd love to be able to prepend the date or possibly the date/time to the `$ConfigFile`.

I updated the script to do this for myself. If you're open to the change, let me know here and I'll do a PR to implement and set behind an option that defaults to `false` so that existing users don't have something change on them.

The idea is that with `$PrependDate` set to `true`, the output would be `2018-02-07_packages.config`.

**Comment by bcurran3** [comment]
Glad you like it and happy to get feedback.

Weird that you opened this five days ago and I just found it on accident. For whatever reason I'm not getting e-mail notifications on my own repo though I get them from others.

I'm all in. Let's make it that one step better!

**Comment by bcurran3** [comment]
@SeanKilleen - just wondering if you were still up for this or should I move forward with it when I have time?

**Comment by bcurran3** [comment]
Done!

It only took 5 new lines of code. :)

https://chocolatey.org/packages/choco-package-list-backup/2018.04.24.01

**Comment by SeanKilleen** [comment]
Ah sorry, I missed the prior notification! I appreciate you taking it on. :)

**Comment by bcurran3** [comment]
@SeanKilleen 

Just an FYI on small handling change of this request.

REF: https://chocolatey.org/packages/choco-package-list-backup/2018.06.21
