### ISSUE TITLE
[choco-package-list-backup] [Feature Request] Allow nesting the backup in cloud under "tools" folder

### ISSUE THREAD

**Issue by fabiorzfreitas** [bcurran3/ChocolateyPackages_CCR#170]
Following your default "C:\tools" naming scheme, I use "__GoogleDrive__\tools" for everything program-related, such as Notepad++ config folder, qBittorrent monitored folder etc. It helps uncluttering the main drive folder and it would be useful if I could put choco-package-list-backup in there as well!

**Comment by bcurran3** [comment]
If you're talking about the backup files (which I don't think you are), they already default to be saved in GoogleDrive if it exists.
If you're talking about the CPLB config files, they go to wherever you have ChocolateyToolsLocation set. So if you set ChocolateyToolsLocation to point there, they will go there (after a re-install). NOTE: ChocolateyToolsLocation is a local users environmental variable.

**Comment by fabiorzfreitas** [comment]
I'm talking about the backup files, not the config files. I'm referring to the fact that the CPLB folder is created on my Google Drive's root and how it would be better if I could nest it properly. On my case, I created a "tools" folder where I keep my cloud N++, my qBittorrent monitored folder and, ideally, my backup files. This separates these from my documents, lessons and other general files I have on Google Drive.

**Comment by bcurran3** [comment]
Then you should disable backing up to Google Drive and then define and use the custom location of your choice option.

**Comment by fabiorzfreitas** [comment]
Yes, except I already use that for a local folder on another drive... I commented this on #97. That would also resolve this issue!
