### ISSUE TITLE
choco-upgrade-all/choco-upgrade-all-at: delete newly installed desktop icons option

### ISSUE THREAD

**Issue by carsten-engelke** [bcurran3/ChocolateyPackages_CCR#171]
It would be great to have the option to suppress desktop icon creation (or delete the created icons after upgrading process). Is this feature planned?

**Comment by bcurran3** [comment]
Yes!

Not sure where it's documented though....

But it is definitely on the TDL. Needs a lot of cautionary testing that's why it's on the back-burner until I have enough free time to do it all at once.

**Comment by bcurran3** [comment]
Found it: https://github.com/chocolatey/choco/issues/344

> bcurran3 commented on Jan 14 • 
> I'm monitoring to see when/if this gets implemented in a new version of Chocolatey. Milestone keeps pushing forward, so far for 4 releases. I'd like to know this issue's (real) priority on the roadmap.
> 
> Sometime in the future I plan an upgrade to choco-upgrade-all-at which will kludge the ability to delete icon additions post install. Basically I'm going to have the task run a batch file that anyone can add pre or post processing into manually. I'll build in an option to either get a list of existing icons and delete the delta or simply moving existing icons to a temporary directory, delete the new icons, and move back the pre-existing icons. When I find the time...

**Comment by carsten-engelke** [comment]
pre and post upgrade script calls seems a very flexible way. Good thinking imo.

**Comment by bcurran3** [comment]
REF: https://github.com/bcurran3/ChocolateyPackages/commit/37a2e499472aba7ae65c754cfc47ca54979dc865

This is 99% done. I'll have it ready for testing later this week. Feel brave?

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/choco-upgrade-all-at/0.0.6-pre is up for testing. You can install via:
`choco install choco-upgrade-all-at --version=0.0.6-pre --pre `

You'll need to edit the config file to enable the new features.

Deletion of new desktop icons is well tested. I haven't tested the deletion of Start Menu items or the new /NOTASK install parameter.

As a bonus you can use choco-install (in path) to install packages using the same settings; i.e. no new desktop icons.

Appreciate it if you can give it a whirl and provide feedback.

**Comment by bcurran3** [comment]
Final was pushed a few days ago, currently sitting moderation queue. choco-upgrade-all-at-startup got the same treatment.
