### ISSUE TITLE
Intel XTU out of date (new version 6.5.2.40)

### ISSUE THREAD

**Issue by Kurre** [bcurran3/ChocolateyPackages_CCR#173]
Hi,

Intel XTU package seems to be out of date. I made and tested the changes, which should be ok.

https://github.com/bcurran3/ChocolateyPackages/compare/master...Kurre:update-intel-xtu

Update of the official package would be much appreciated. Thanks! 👍

**Comment by bcurran3** [comment]
Done:
https://chocolatey.org/packages/intel-xtu/6.5.2.40
