### ISSUE TITLE
Negative value for cleaned up KB

### ISSUE THREAD

**Issue by hl2guide** [bcurran3/ChocolateyPackages_CCR#174]
![a](https://user-images.githubusercontent.com/17044982/86529167-cd5c5e80-bef1-11ea-8e10-043e4c95b185.PNG)

May be a simple fix could be if negative make it zero?

**Comment by bcurran3** [comment]
Yep. # is based on free space before and after. 

Sometimes other things are happening/changing files on the system.

If I got the size for each file deleted and added up for a total, it would add a lot of overhead. I'm not actually against it... just not very important to be that precise in a little script.

NOTE: It does display a tilde in front of the number exactly for that reason. :)

**Comment by bcurran3** [comment]
Maybe I'll change it in the future to "undetermined" when the value is found negative...

**Comment by hl2guide** [comment]
sounds good :D

**Comment by hl2guide** [comment]
For me I replaced:

`Write-Host Choco-Cleaner finished deleting unnecessary Chocolatey files and saved you $freedspace.ToString('N0') KB! -Foreground Magenta`

with:

```
     if($FreedSpace -gt 0)
     {
        Write-Host Choco-Cleaner finished deleting unnecessary Chocolatey files and saved you $freedspace.ToString('N0') KB! -Foreground Magenta
     }
     else
     {
        Write-Host Choco-Cleaner finished checking for unnecessary Chocolatey files. -Foreground Magenta
     }
```

**Comment by bcurran3** [comment]
So I completely forgot to address this in v.0.0.8.1 that I put out yesterday. Guilt set in and I just added it to v0.0.8.2 today. REF: https://github.com/bcurran3/ChocolateyPackages/commit/642dbf122717c84b4f3156d939caa94834f4154e

I'm going to close this as it's done. But note that I do still plan to " Accurately track and report reclaimed space per bullet point and total" at some point in the future.
