### ISSUE TITLE
Open-Shell installer installs too much

### ISSUE THREAD

**Issue by bobberb** [bcurran3/ChocolateyPackages_CCR#175]
Dear @bcurran3 

Thank you for your choco package for Open-Shell.

At the moment, Open-Shell will silently also install ClassicIE and ClassicExplorer. I imagine most people want the start menu and only the start menu being changed. 

The flag "ADDLOCAL" should be added to the choco package to limit installer to *just* openshell. 

OpenShellSetup_4_4_142.exe /qn ADDLOCAL=StartMenu

**Comment by bcurran3** [comment]
YW.

I'll take this under consideration when there's a new release out.
Is there a new release out?

**Comment by bobberb** [comment]
I will alert when there is a new release.

**Comment by bobberb** [comment]
@bcurran3 
After 10 months, we have a new release of Open-Shell today Sept 2 2020
https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.152

**Comment by bcurran3** [comment]
@bobberb, thanks for the update.

I've updated the package.

I did  not add your request. Sorry. There's no real need as you can use choco's --installarguments parameter. 

If you want to do a PR and add the feature as a package parameter, I'll accept it.
If you want to become the maintainer of this package, I'll make you the maintainer as I don't really have a use for it personally anymore. (Upgraded the last of the 2012 R2 servers to 2019 finally)

**Comment by TheCakeIsNaOH** [comment]
Hey, @bobberb I added package parameters to select components, see the current package version description:
https://chocolatey.org/packages/open-shell/4.4.160#description

**Comment by bobberb** [comment]
Thank you!
