### ISSUE TITLE
intel-dsa package outdated, fails checksum verification

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#176]
New version (20.7.26) is available, current package fails to install with a checksum error

Download link: https://downloadcenter.intel.com/download/28425/Intel-Driver-Support-Assistant
Direct download: https://downloadmirror.intel.com/28425/a08/Intel-Driver-and-Support-Assistant-Installer.exe
Release Notes: https://www.intel.com/content/www/us/en/support/articles/000056693/software/software-applications.html

**Comment by bcurran3** [comment]
Done!
