### ISSUE TITLE
[Choco-cleaner] add installation paramater to not create task

### ISSUE THREAD

**Issue by oninoshiko** [bcurran3/ChocolateyPackages_CCR#177]
Would it be possible to add a parameter to not create the task?

I'm installing packages on virtual desktop images, so manually cleaning things before declaring an image the master works just fine for me. The users aren't likely to run choco much themselves, so once I clean it after an update, it should stay fairly clean until I update packages again.

**Comment by bcurran3** [comment]
There might already be an issue for this, but  it seems reasonable to add a /NOTASK parameter to all my packages that create tasks.

In the meantime, it's just a normal Scheduled Task that you can delete via normal means for your image.

**Comment by bcurran3** [comment]
This has been added to 0.0.8, https://github.com/bcurran3/ChocolateyPackages/commit/16645d262d92d8f57edd8d440752916a2295019b

Please test and report if any problems.

**Comment by bcurran3** [comment]
This has been added to choco-update-all-at v.0.06 as well

REF: https://github.com/bcurran3/ChocolateyPackages/commit/7b19fe3c58dc4fb9c3e205829de2389b0e3db379

**Comment by bcurran3** [comment]
This has been added to choco-package-list-backup v2021.03.14 as well

REF: https://github.com/bcurran3/ChocolateyPackages/commit/3c01913be4a48881824bbd8d73587912f509d691
