### ISSUE TITLE
[wsl-ubuntu-1604] checksum fails when installing v16.04.3.020181002

### ISSUE THREAD

**Issue by artic92** [bcurran3/ChocolateyPackages_CCR#178]
Steps to reproduce the issue:

1. `choco install wsl-ubuntu-1604`

Reproducibility: **always**

Tried to execute also without checksum control:

`choco install --ignore-checksums wsl-ubuntu-1604`

But got the following error:

```text
ERROR: This command cannot be run due to the error: The system cannot find the file specified.
The install of wsl-ubuntu-1604 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\wsl-ubuntu-1604\tools\ChocolateyInstall.ps1'.
```

Log attached [chocolatey.log](https://github.com/bcurran3/ChocolateyPackages/files/4947090/chocolatey.log).

**Comment by bcurran3** [comment]
Thanks. Appears there is a new version out (1604.2019.523.0) and it launches with ubuntu1604.exe instead of ubuntu.exe. Time to update the package...

**Comment by bcurran3** [comment]
I've been working on this, but run into a snag which might be a bug with Chocolatey; waiting to find out.

**Comment by bcurran3** [comment]
Evidently no snag, just some unnecessary choco warnings involved. Will get back to when time allows.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
