### ISSUE TITLE
[Choco-Dokany] Package out of date

### ISSUE THREAD

**Issue by AIVAS001** [bcurran3/ChocolateyPackages_CCR#188]
Current package is 1.3.0.1000. Current version of Dokany is 1.4.0.1000.
Dependency for Cryptomator and causes Cryptomator package to fail.

(No response to Discus messages)

**Comment by chrissv** [comment]
Current version is now 1.5.1.1000

**Comment by bcurran3** [comment]
This package is still looking for a new maintainer (note: label). I do not use it and have no desire to maintain it anymore. If you wish to take on maintenance let me know you're Chocolatey ID.
I'm happy to tutor you on how to do it if you don't know.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
