### ISSUE TITLE
[Question] choco-cleaner - create CCleaner Chocolatey extension

### ISSUE THREAD

**Issue by zero77** [bcurran3/ChocolateyPackages_CCR#19]
@bcurran3 
You choco-cleaner is really nice and does a great job.

Although, have you considered creating a CCleaner entry alongside choco-cleaner for users who want to clean Chocolatey through CCleaner instead.

Thanks

https://github.com/MoscaDotTo/Winapp2

https://forum.piriform.com/topic/32310-winapp2ini-additions/?page=1

**Comment by bcurran3** [comment]
I didn't know that was even possible. Thanks for the info. I will look into it.

BTW: Rob didn't like the defaults I choose for the package so it never got published/past moderation/went live. I created a v.0.0.2 version months ago but need to find time to go back and test and tweak it so it'll get past his moderation.

If you are a Chocolatey licensed user, I just put this out a few minutes ago:
https://chocolatey.org/packages/choco-optimize-at/0.0.1

**Comment by zero77** [comment]
Yes, its possible but, I don’t know how widely known it is, but its all explained in the [reed me](https://github.com/MoscaDotTo/Winapp2#winapp2).

I created a [PR](https://github.com/MoscaDotTo/Winapp2/pull/256/files) but I don’t know if I covered everything. 

I am not a licenced user but thanks any way, yes, I noticed that it sadly never got published.

**Comment by bcurran3** [comment]
@zero77 FYI: There might still be some changes enforced by ferventcoder, but I'm close to releasing a new "sanctified" version of choco-cleaner. 
https://chocolatey.org/packages/choco-cleaner/0.0.3-pre
