### ISSUE TITLE
irfanviewplugins v. 4.54 32-bit package failing to install

### ISSUE THREAD

**Issue by kkeiichi** [bcurran3/ChocolateyPackages_CCR#192]
There is en error in installation script for 32-bit version of irfanviewplugins v. 4.54.
Setup archive is named iview454**a**_plugins_setup.exe, but the script is looking for name iview454_plugins_setup.exe

[log.txt](https://github.com/bcurran3/ChocolateyPackages/files/5154587/log.txt)

**Comment by bcurran3** [comment]
Thanks. I just pushed a fix. Please test and let me know if there are any problems.
