### ISSUE TITLE
forticlientvpn: use the online installer

### ISSUE THREAD

**Issue by felipecrs** [bcurran3/ChocolateyPackages_CCR#199]
Fortinet does not seem to want to provide offline installers for the Windows version of FortiClient VPN anymore.

I contacted the support, they first told me that offline installers are available for the buyers, in other words, companies which have a license of the Fortinet VPN server are allowed to distribute the offline installers, but unregistered users can only get the online installer through public means.

I kindly made a feature suggestion to one of their "Account Managers" to revert this decision, but I doubt I will even receive a reply.

So this is about making this Chocolatey package use the online installer rather than the offline installer.

All the downloads for FortiClient VPN can be found here: https://www.forticlient.com/downloads

**Comment by bcurran3** [comment]
Yup. They're not really playing nice with this. 

I can do AHK on it but (don't want to). I think I'm going to:
download installer
force quit installer
run the downloaded MSI with silent install parameters

That way it can be more controlled...

Takes time and a lot of testing.

To be honest, not a high priority but I am willing to get it done.

**Comment by felipecrs** [comment]
Sounds like a plan!

But perhaps the initial installer already provides all the flags we need to make it silent? I'll try to figure out tomorrow.

**Comment by bcurran3** [comment]
It doesn't. Been there. Done that....way back when they started hiding the offline installer direct download URLs. It's just a stub to download the MSI and the stub passes nothing at all to the actual installer. :(

**Comment by bcurran3** [comment]
I've switched away from Fortinet and don't plan to maintain this any longer. New maintainer wanted. If you want to take it on, please send me your Chocolatey ID.
(Fortinet F80E for sale now -hahaha!)

**Comment by JWilliam-H** [comment]
> I've switched away from Fortinet and don't plan to maintain this any longer. New maintainer wanted. If you want to take it on, please send me your Chocolatey ID.
> (Fortinet F80E for sale now -hahaha!)

I would like to take over maintaining Fortinet client via Chocolatey.

**Comment by bcurran3** [comment]
Send me your Chocolatey ID

**Comment by bcurran3** [comment]
This was passed off to BJD1997 for maintaining last year.
