### ISSUE TITLE
Incorrect quotes in main powershell script

### ISSUE THREAD

**Issue by gunr2171** [bcurran3/ChocolateyPackages_CCR#20]
Giving how you made a commit 10 minutes ago, I think you're already on this, but just in case you don't see it.

I've got this line in my choco-package-list-backup.ps1 script at line 84 (I just installed `choco-package-list-backup 2018.04.24`):

```
Write-Host "choco-package-list-backup.ps1 v$CPLBver" - backup Chocolatey package list(s) locally and to the cloud -ForegroundColor white
```

This produces a powershell syntax error because of the lack of quotes.

```
s : The term 's' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\ProgramData\chocolatey\bin\choco-package-list-backup.ps1:84 char:87
+ ... list-backup.ps1 v$CPLBver" - backup Chocolatey package list(s) locall ...
+                                                                 ~
    + CategoryInfo          : ObjectNotFound: (s:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

This _might_ still be an issue with a very recent commit.

https://github.com/bcurran3/ChocolateyPackages/blob/3bff5e67b27547cdfd75f16c99e9d4e2eef050cc/choco-package-list-backup/tools/choco-package-list-backup.ps1#L89

**Comment by bcurran3** [comment]
Yes, this was fixed in https://chocolatey.org/packages/choco-package-list-backup/2018.04.24.01 :)
