### ISSUE TITLE
forticlientvpn: automate the package update

### ISSUE THREAD

**Issue by felipecrs** [bcurran3/ChocolateyPackages_CCR#200]
In order to automate the package update, I can not think of a better way than:

1. Find the download URL in the download page
2. Download it
3. Inspect the file, it has the full version in its properties: 
    
    ![image](https://user-images.githubusercontent.com/29582865/93654668-12723600-f9f5-11ea-8ec6-11f2bafa499b.png)

However, this depends on #199.

**Comment by bcurran3** [comment]
Bom dia.

That's exactly how it's normally done. 

PROBLEM is that the download URL is not static; i.e. it changes with each release. So unlike a lot of other programs that have http://somedomain.com/download/latest or filename.exe, the filename changes every time. It can be done, it's just harder as the page needs to be scraped, the download link found, the download link compared to the last check, etc. Not impossible, just not something high enough up on the priority list for me to take on in the foreseeable future.  I just want to be honest about this. There are a lot of other easier packages for me to setup auto-updates for first. :) So I tagged a Help_Wanted on this incase you or someone else wants to put the effort into making an update.ps1 file for AU.

**Comment by BJD1997** [comment]
Hi, I'm looking into updating the package but it's my first time taking a crack at it.
So far i've found the URL which lists all versions [here](https://filestore.fortinet.com/forticlient/)
And there is also a static URL which downloads just the latest version [here](https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller.exe)

Does this solve the issue of scraping the page? If not there are zip files on the page with a slightly older version that contains a MSI file (that's the route I've opted for to try and build a package).

**Comment by bcurran3** [comment]
That latest version installer is just the stub installer to download the real installer.

**Comment by BJD1997** [comment]
I've noticed indeed, went digging and seems like it drops a .msi file in the temp folder.
Also it contacts http://forticlient.fortinet.net/fdsupdate with a post request but can't seem to replicate it using powershell (HTTP code 400)
