### ISSUE TITLE
[ChocolateyPowershell] Tries to import chocolatey-core.extension even when it is not installed.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#201]
ChocolateyPowershell tries to cd to and import the `chocolatey-core` module, which fails if `chocolatey-core.extension` package is not installed. It still works with other functions but leaves a large, nasty looking error every time it is opened.

I have two suggestions for how to go about fixing this. 
1. Take a dependency on `chocolatey-core.extension` 
2. Check if `chocolatey-core.extension`  is installed, and if it not, then do not try to import the module. In this case, maybe also provide an informational message that it was not found, and how to install it.

**Comment by bcurran3** [comment]
The latter is the most logical to me.

Probably want to put in some logic to check for any extensions that are installed and load all of their psm's...

Maybe some statements saying their being loaded to to point out that they might be installed on that user's instance of Chocolatey, but not necessarily on everyone's instance of Chocolatey.

**Comment by bcurran3** [comment]
Since this was a 30 second fix, I'm pushing the new version now. Thanks for pointing that out!
I'm going to leave the issue open until I later check for and load all extentions.

**Comment by bcurran3** [comment]
Actually no need to load any extensions as the Chocolatey PSM will do it automatically....

Done:
https://chocolatey.org/packages/chocolateypowershell/0.0.2.2

**Comment by TheCakeIsNaOH** [comment]
Perfect, thanks.
