### ISSUE TITLE
Rename tools folder in C Drive to ChocoPackageListBackupTools

### ISSUE THREAD

**Issue by sakibarifin** [bcurran3/ChocolateyPackages_CCR#204]
The tools folder in the c drive makes it a little ambiguous. Hence I suggest making it ChocoPackageListBackupTools so that people can easily identify why it is there. Though I would prefer to see it in the user public directory or in C:\Users\ directory. Generally, almost no program leaves leftover or data in the system C:\ folder.

Also, after uninstall, C:\Users\MyPC\Documents\ChocolateyPackageListBackup was still there. Is this an expected behavior?

**Comment by TheCakeIsNaOH** [comment]
It actually installs to the folder returned by `Get-ToolsLocation`, which is the recommended location to put portable software if you do not want to use `$env:ChocolateyInstall\lib\<packageName`. It defaults to a location of `C:\tools`
https://chocolatey.org/docs/helpers-get-tools-location

If you want to change where the `Get-ToolsLocation` is, you can change the environment variable `ChocolateyToolsLocation`

**Comment by sakibarifin** [comment]
Since the issue is related to chocolatey itself, I am closing it.
