### ISSUE TITLE
[wsl-ubuntu-1804] checksum errors before and during install

### ISSUE THREAD

**Issue by whitis** [bcurran3/ChocolateyPackages_CCR#209]
Had to override checksum to install package

During installation, there were also hundreds of error messages of the form:
2020-10-09 20:25:50,186 13100 [WARN ] - Error computing hash for 'C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\unzipped\rootfs\var\spool\mail'
 Hash will be special code for locked file or file too big instead.
 Captured error:
  The file cannot be accessed by the system.

This is a regression as these problems didn't exist earlier.

This was on a toshiba satellite c655-S5082 that was upgraded from win 7 to win 10 2004 (erase everything) yesterday.

Installed packages (a few weren't installed at time of error):
Chocolatey 7zip 7zip.install adobereader audacity avastfreeantivirus belarcadvisor bleachbit bleachbit.install calibre chocolatey chocolatey-core.extension chocolatey-fastanswers.extension chocolatey-windowsupdate.extension curl cutepdf ffmpeg gedit Ghostscript.app gimp GoogleChrome InfraRecorder InkScape jitsi jre8 KB2919355 KB2919442 KB2999226 KB3033929 KB3035131 keepassxc krita libreoffice libreoffice-fresh malwarebytes okular openssh peazip peazip.install sgt-puzzles thunderbird vcredist140 vlc Wget windirstat wsl wsl-ubuntu-1804 wsl-ubuntu-2004 wumgr zoom

No programs were installed outside of chocolatey, except windows updates.

**Comment by bcurran3** [comment]
So you've probably got some more gray hairs by now...

I just pushed this. I haven't even tested it yet. Feel free to try and give feedback.

https://community.chocolatey.org/packages/wsl-ubuntu-1804/18.04.5-pre

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
