### ISSUE TITLE
Question: Will the main powershell script get overridden when I update this choco package?

### ISSUE THREAD

**Issue by gunr2171** [bcurran3/ChocolateyPackages_CCR#21]
I'm referring to the Choco Package List Backup chocolatey package.

choco-package-list-backup.ps1 contains backup logic _and_ configuration. What happens when I update the package? Does this file get overridden? Do I lose what customization I have made?

**Comment by bcurran3** [comment]
Currently it overwrites the old script.
I've been meaning to rename the old file during install if it exists, but keep forgetting. 
Thanks for adding the issue so I don't forget. Will add soon!

**Comment by gunr2171** [comment]
If that's the way you want to do it, ok, but may I make a suggestion:

As an end user, I want to do the minimal amount of work possible to upgrade a choco package. Ideally, running `choco upgrade <package>` should do everything required for the application's upgrade, automatically.

By renaming the main script file, you're forcing me to:

1. Wait for the choco upgrade task to finish
2. Find where the script is located (remember, I'm stupid, I'll forget where it is located)
3. Open the latest date-formatted file and get my custom configurations from it (it might not even be the latest version, I could have forgotten to migrate the settings in the last upgrade)
4. Merge those changes into the new master script.

Note: you've also published the [upgrade-all-at](https://chocolatey.org/packages/choco-upgrade-all-at/) package. If I use both packages in tandem, I'm not going to know when the Backup package is updated, so I'll need to manually verify that my backups are sent to the correct location each time I run this. That kills my ability to run this package from a Scheduled Task.

I'm an end user. I'm dumb and _really_ lazy. I don't want to do those steps if I don't want to.

Instead, I'd suggest making a dedicated configuration file. When an install or upgrade in choco is performed, and the file does not exist, create the file with all the defaults set. However, if the file already exists, do not modify it.

This way, choco is free to modify the main script file without fear that it will overwrite a user's configuration, and the user is not required to do extra steps after an upgrade to keep their settings.

**Comment by bcurran3** [comment]
I understand and agree wholeheartedly. 
If you've got the time to help make it better, make a PR.
If you don't have the time, and want to protect your config, consider pinning the package.

https://chocolatey.org/packages/choco-package-list-backup/2018.04.25

ROADMAP:
* Move configuration data to a seperate file

CHANGELOG:
* 2018.04.25 - removed run as admin requirement, now makes a backup of previous choco-packages-list-backup.ps1 (appended date), fixed minor text output error, added compatibility with [choco-shortcuts-winconfig](https://chocolatey.org/packages/choco-shortcuts-winconfig)

**Comment by bcurran3** [comment]
Hey @gunr2171, checkout https://chocolatey.org/packages/choco-package-list-backup/2018.05.09
