### ISSUE TITLE
choco-package-list-backup: run on every startup (in background)

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#210]
If you make this listing run on every startup it will be very helpful, as we don't have to manually run it after every week to backup our apps list.

The thing is that we can also add it to startup apps, but then, it doesn't  run in "background", it shows the program running on screen.

**Comment by ghost** [comment]
I created this task to run on every time I login, working perfectly and in background

![image](https://user-images.githubusercontent.com/58593523/96114662-5a568100-0eff-11eb-9dea-d54c68b1b875.png)

![image](https://user-images.githubusercontent.com/58593523/96114707-693d3380-0eff-11eb-8ff0-ec4012164999.png)

![image](https://user-images.githubusercontent.com/58593523/96114903-a30e3a00-0eff-11eb-9c2d-e10b6e6359fd.png)

**Comment by bcurran3** [comment]
I just added a /NOTASK option to the new release today.
I think it'll be easy enough to add a /ATSTARTUP option to configure a scheduled task to run a startup.
On the TDL.

**Comment by ghost** [comment]
> I just added a /NOTASK option to the new release today.
> I think it'll be easy enough to add a /ATSTARTUP option to configure a scheduled task to run a startup.
> On the TDL.

Can you tell how exactly use /ATSTARTUP option for this package?

**Comment by bcurran3** [comment]
> Can you tell how exactly use /ATSTARTUP option for this package?

It doesn't exist yet; i.e. On the TDL (To Do List)

**Comment by bcurran3** [comment]
ONSTART and ATSTARTUP options added to 09/22/21 release.

See the OPTIONAL INSTALLATION INSTRUCTIONS for use.
