### ISSUE TITLE
I'll just apologize right away...but how can I add your awesome repo as a source in chocolatey?

### ISSUE THREAD

**Issue by CynicalWilson** [bcurran3/ChocolateyPackages_CCR#212]
I'm sure it's way easy, and it's certainly not an "issue", but could you let me know how to add your git repo/chocolatey profile as a source in chocolatey?

**Comment by TheCakeIsNaOH** [comment]
The packages are uploaded to the chocolatey.org repository that is built into `choco`.

See:
https://chocolatey.org/profiles/bcurran3

So you can just run `choco install <packageIDhere>` to install any of the packages.

**Comment by bcurran3** [comment]
@maxwinkler13, in other words - github is not a nuget server. To do what you asked you'd need to have a nuget server and then put the downloaded packages on it. If you simply want a copy of the package sources you can fork the repo.
