### ISSUE TITLE
Multiple choco font package installs via Boxstarter - FontResource.AddRemoveFonts

### ISSUE THREAD

**Issue by KZeronimo** [bcurran3/ChocolateyPackages_CCR#215]
### What You Are Seeing?

Strange error when installing font choco packages via Boxtarter

### What Is Expected?

Both choco packages install successfully which is what happens when executing outside of Boxstarter

### How Did You Get This To Happen? (Steps to Reproduce)

Install-BoxstarterPackage -PackageName "https://gist.githubusercontent.com/KZeronimo/c3f9466f6c620fc39c9506ee36f2ac37/raw/font-install.txt" -DisableReboots

### Output Log

https://gist.github.com/KZeronimo/98ba0e89047a06c8034adc91dde1e06f # #

[Reported in Boxstarter repo](https://github.com/chocolatey/boxstarter/issues/455)

**Comment by bcurran3** [comment]
All the log links are blank.

You should probably go to https://github.com/teknowledgist/Chocolatey-packages/tree/master/extensions/chocolatey-font-helpers.extension if you think it's related to the font helper extension.
