### ISSUE TITLE
SUMo (lite) 5.11.5.464: Hash mismatch when upgrading

### ISSUE THREAD

**Issue by CypherNL** [bcurran3/ChocolateyPackages_CCR#217]
See gist here: https://gist.github.com/CypherNL/3014df8ba9c23b542fe43d309c26ca20

**Comment by bcurran3** [comment]
Chocolatey v0.10.15 Professional
Attempting to push sumo.5.11.7.466.nupkg to https://push.chocolatey.org/
sumo 5.11.7.466 was pushed successfully to https://push.chocolatey.org/
