### ISSUE TITLE
[Suggestion] choco-package-list-backup: Updated Dropbox and Google FS handling

### ISSUE THREAD

**Issue by ebbek** [bcurran3/ChocolateyPackages_CCR#22]
I have made the following updated versions of how copying to Dropbox and Google FS is handled. The reasons for this is that:
- On one of my PCs the dropbox folder is located in a non-default position which choco-package-list-backup did not find. While I was at it I added support for both personal and business Dropbox accounts.
- Google Drive has been deprecated so I have replaced it with support for Google Drive File Stream.

## Dropbox
The current Dropbox handling is replaced with the following:
```powershell
# Check for Dropbox paths
if (Test-Path $Env:AppData\Dropbox\info.json)
{
    $DropboxPersonal = ((get-content $Env:AppData\Dropbox\info.json) -join '`n' | ConvertFrom-json).personal.path
    $DropboxBusiness = ((get-content $Env:AppData\Dropbox\info.json) -join '`n' | ConvertFrom-json).business.path
}
elseif (Test-Path $Env:LocalAppData\Dropbox\info.json)
{
    $DropboxPersonal = ((get-content $Env:LocalAppData\Dropbox\info.json) -join '`n' | ConvertFrom-json).personal.path
    $DropboxBusiness = ((get-content $Env:LocalAppData\Dropbox\info.json) -join '`n' | ConvertFrom-json).business.path
}

# Backup Chocolatey package names on local computer to packages.config file in Personal Dropbox directory if it exists
if ($UseDropbox -match "True" -and ($DropboxPersonal) -and (Test-Path $DropboxPersonal))
   {
    $SavePath = "$DropboxPersonal\$SaveFolderName\$Env:ComputerName"
    Write-PackageConfig
   }
   
# Backup Chocolatey package names on local computer to packages.config file in Business Dropbox directory if it exists
if ($UseDropbox -match "True" -and ($DropboxBusiness) -and (Test-Path $DropboxBusiness))
   {
    $SavePath = "$DropboxBusiness\$SaveFolderName\$Env:ComputerName"
    Write-PackageConfig
   }
```
I have based the code on the information found here:
https://www.dropbox.com/help/desktop-web/locate-dropbox-folder#programmatically

## Google Drive File Stream
The current Google Drive handling is replaced with the following:
```powershell
# Backup Chocolatey package names on local computer to packages.config file in Google Drive FS "My Drive" directory if it exists
$GoogleFSmountpoint = (Get-ItemProperty -path Registry::HKEY_CURRENT_USER\Software\Google\DriveFS\Share).MountPoint
if ($UseGoogleDrive -match "True" -and ($GoogleFSmountpoint) -and (Test-Path "${GoogleFSmountpoint}:\My Drive"))
{
    $SavePath = "${GoogleFSmountpoint}:\My Drive\$SaveFolderName\$Env:ComputerName"
    Write-PackageConfig
   }
```
I have based the code on the information found here:
https://support.google.com/a/answer/7644837?hl=en

You are free to use/change/discard this code as you please. As for tests, well, "It works on my machine..."

**Comment by ebbek** [comment]
The comment "It works on my machine" turned out to be more true than I like. Here is an amended version of the Google Drive File Stream handling that is a bit more robust:

```powershell
# Backup Chocolatey package names on local computer to packages.config file in Google FS Drive directory if it exists
$ErrorActionPreference = "stop"
Try
{
    $GoogleFSmountpoint = (Get-ItemProperty -path Registry::HKEY_CURRENT_USER\Software\Google\DriveFS\Share).MountPoint
    if ($UseGoogleDrive -match "True" -and ($GoogleFSmountpoint) -and (Test-Path "${GoogleFSmountpoint}:\My Drive"))
    {
        $SavePath = "${GoogleFSmountpoint}:\My Drive\$SaveFolderName\$Env:ComputerName"
        Write-PackageConfig
       }
    }
Catch [System.Management.Automation.PSArgumentException] { }
Catch [System.Management.Automation.ItemNotFoundException] { }
Catch [System.Management.Automation.CommandNotFoundException] { }
Finally { $ErrorActionPreference = "Continue" }
```

**Comment by bcurran3** [comment]
Thanks @ebbek I will check it out and probably have an updated version out later this week.

**Comment by bcurran3** [comment]
The Dropbox additions look good and I've added them.

AFAIK Google Drive has been deprecated but replaced by Backup and Sync. Google Drive File System is only for G Suite business users.

I've added the GFS code but simplified the check to see if it's installed or not:

# Backup Chocolatey package names on local computer to packages.config file in Google Drive FS "My Drive" directory if it exists  (Thanks ebbek!)
$GFSInstalled=(test-path -path HKCU:Software\Google\DriveFS\Share)
if ($GFSInstalled)
   {
    $GoogleFSmountpoint = (Get-ItemProperty -path Registry::HKEY_CURRENT_USER\Software\Google\DriveFS\Share).MountPoint
    if ($UseGoogleDrive -match "True" -and ($GoogleFSmountpoint) -and (Test-Path "${GoogleFSmountpoint}:\My Drive"))
       {
        $SavePath = "${GoogleFSmountpoint}:\My Drive\$SaveFolderName\$Env:ComputerName"
        Write-PackageConfig
       }
	}

Thanks again for your help in making this better!

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/choco-package-list-backup/2018.05.06
