### ISSUE TITLE
CNC -  does not handle SVG iconURLs

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#222]
CNC errors out if the icon is an SVG.

Since SVG is a vector format, it does not have a specific resolution.
So it should just skip the resolution check and give an ok.

Example package and iconURL:
https://chocolatey.org/packages/maven
https://upload.wikimedia.org/wikipedia/commons/0/0b/Maven_logo.svg

Error:
```
New-Object : Exception calling ".ctor" with "1" argument(s): "Parameter is not valid."
At C:\tools\BCURRAN3\CNC.ps1:260 char:14
+     $image = New-Object System.Drawing.Bitmap "$pwd\iconURL.image"
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\tools\BCURRAN3\CNC.ps1:263 char:5
+     $image.dispose()
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by bcurran3** [comment]
I've seen that error, Exception calling ".ctor", and never got around to investigating it.
Now I know! (Kinda knew and forgot - # Supports BMP, GIF, EXIF, JPG, PNG and TIFF)
This makes perfect sense to me. 
Thanks for pointing it out.

**Comment by bcurran3** [comment]
unrelated memory jogger for self: add "FYI:" to (currently) line 1204 (			Write-Host "           ** <iconUrl> - URL updated to: `n              $NuspecIconURL" -Foreground Green)

**Comment by bcurran3** [comment]
Fixed with https://github.com/bcurran3/ChocolateyPackages/commit/19bbd2e9fd3e3ced9ae38915d5781383d98954ae

I had fun with this one.
