### ISSUE TITLE
InstChoco does not handle double quotes in a package summary description

### ISSUE THREAD

**Issue by aam-dvansevenant** [bcurran3/ChocolateyPackages_CCR#230]
Using InstChoco to test re-installing to a "bare metal" machine inside Windows Sandbox.

Created a backup using CPLB, opened packages.config with Notepad++, selected all text and copied it.

In Windows Sandbox opened Notepad and pasted the contents. Saved and renamed to "packages.config"

Downloaded InstChoco to the Windows Sandbox instance into the same folder.

Opened a command prompt in that folder.

Ran ".\instchoco -y"

Processing happened, and then an error about invalid XML (33, 107).

Checked the packages.config file and found this line:

   `<package id="notepadplusplus.install" title="Notepad++ (Install)" summary="Notepad++ is a free (as in "free speech" and also as in "free beer") source code editor and Notepad replacement that supports several languages."/>`

Note the double quotes around free speech and free beer in the summary. These messed up the processing of he packages.config file.

I manually changed the double quotes to a single hyphen each, and InstChoco successfully processed the file and everything was good.

I suspect regardless of the Windows Sandbox that this problem will occur elsewhere.

**Comment by bcurran3** [comment]
Hi @ccc-dvansevenant.

This is not a InstChoco thing. This is a choco.exe thing. InstChoco is just shelling out to run choco packages.config. 

I'm sure you've already done this, but to move forward in your current state just run CPLB without saving the package descriptions.

Long term solution would be open an issue for Chocolatey to have choco.exe parse quotes in descriptions or for choco-package-list-backup to parse quotes in descriptions and not write them out to the packages.config file.

I'm going to close this since the ball is really in one of those other courts.

**Comment by aam-dvansevenant** [comment]
Gotcha. Done. Thanks for the quick response!


Dion Vansevenant
CanCclear
dvansevenant@cancclear.com<mailto:dvansevenant@cancclear.com>

[cid:image001.png@01D6E9BA.C7375750]
This information is intended for the use of the individual to whom it is addressed. It may contain information that is privileged and confidential.
Copying, disclosure and distribution to others is strictly prohibited. If received in error, please notify us immediately and return the original to the sender.

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/104506773-b0889e00-559a-11eb-914c-abb78d6bc73e.png)

**Comment by bcurran3** [comment]
After some related issues with an update to choco-package-list-back I came back to look at this again. I think CPLB can be fairly easily modified to escape ([System.Security.SecurityElement]::Escape()) all the problems with the title and/or description.

REF: https://github.com/bcurran3/ChocolateyPackages/pull/235

```
A (working) mock up test for moving title and summary into comments:

Function Write-PackagesConfig{

        $body=choco list -lo -r -y | % { 
		'<!--' + "`ntitle: " + 
		(get-nuspecinfo "$($_.SubString(0, $_.IndexOf("|")))" "title") 
		"`nsummary: " + 
        (get-nuspecinfo "$($_.SubString(0, $_.IndexOf("|")))" "summary") + "`n"
		'-->' + "`n"
		"   <package id=`"$($_.SubString(0, $_.IndexOf("|")))`" />`n"
		}
		Write-Host $body

	   }
Gives results like this:

Choco Package List Backup Summary:
<!--
title: 7-Zip
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip" />
 <!--
title: [Deprecated] 7-Zip (Portable, CommandLine)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.commandline" />
 <!--
title: 7-Zip (Install)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.install" />
 <!--
title: 7-Zip (Portable, CommandLine)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.portable" />
This creates a very "busy" packages.config, but I kind of like it.

Just fishing for comments. I was wondering if the SavedArguments might be good to put in the comments, but it'd be a bear to pull them out of the comments if I want to use the SavedArguments in something like InstChoco.

```

The above is another way to take care of the problem. Curious as to your thoughts?

**Comment by bcurran3** [comment]
Never mind. After properly looking at the updated code.... You're original problem has been fixed!

**Comment by aam-dvansevenant** [comment]
Thanks for the updates!


Dion Vansevenant
CanCclear
***@***.******@***.***>

***@***.***D71FC0.F4319130]
This information is intended for the use of the individual to whom it is addressed. It may contain information that is privileged and confidential.
Copying, disclosure and distribution to others is strictly prohibited. If received in error, please notify us immediately and return the original to the sender.
