### ISSUE TITLE
Chocolatey Preinstaller Checks Extension: keeps warning about pending reboot

### ISSUE THREAD

**Issue by jrfnl** [bcurran3/ChocolateyPackages_CCR#231]
... even when the computer has literally just been rebooted....

Tried hard reboot (complete shutdown and cold restart), soft reboot (restart from menu) and no matter what I do, I still get a `WARNING: Pending reboot found`.

Any recommendations ? Any debug information or logs which would help to resolve this ? Please let me know and I'll try to provide as much information as I can.

**Comment by bcurran3** [comment]
There's a good chance that your computer has a pending file rename that for some reason even after rebooting it hasn't happened. I want to say that this happens to me sometime with HP printer drivers.  You can look at Get-PendingRebootStatus.ps1 to see what registry keys are being checked. There's a reference link in there too that might have more detail.

**Comment by bcurran3** [comment]
Me in Amsterdam 2002. :) 
![image](https://user-images.githubusercontent.com/14026600/104532636-86000a80-55c5-11eb-8775-dae710e29d97.png)

**Comment by jrfnl** [comment]
>  You can look at Get-PendingRebootStatus.ps1 to see what registry keys are being checked.

Sorry, I'm a dev, but not for Windows. Is this a file which is already installed with choco ? or with the plugin ? Do I need to run it somehow ? Will the output just display or do I need to go to logs somewhere ?

**Comment by jrfnl** [comment]
Ok, so I found the file in the `ProgramData\chocolatey\extensions\chocolatey-preinstaller-checks` directory and looked at the source. Then used `regedit` to go through the registry keys to see if I could find them.

Found the `PendingFileRenameOperations` key in `HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager` with a value of:
```
\??\C:\WINDOWS\system32\spool\DRIVERS\x64\3\New\PrintConfig.dll
\??\C:\WINDOWS\system32\spool\DRIVERS\x64\3\PrintConfig.dll
\??\C:\WINDOWS\system32\spool\drivers\x64\3\Old\1\PrintConfig.dll
```

Can I safely remove that key ? Or should I edit it to fix it and then try a reboot again ? And if so, edit it to what ?

**Comment by jrfnl** [comment]
Note: of the file names referenced above: the last two files exist, the first one doesn't.

**Comment by bcurran3** [comment]
Seems you have the same problem that I do now and then.

Yes, you can safely delete the registry keys. Understand though that the files for the printer will not be updated so there could be print issues. With that said, the files aren't updating automatically like they are supposed to anyways....

The safest thing to do would be - delete the reg key. Delete the printer drivers and re-install them.

I'm going to close this now as it's not a issue related to the script.
