### ISSUE TITLE
(choco-cleaner) - delete abandoned shims

### ISSUE THREAD

**Issue by bcurran3** [bcurran3/ChocolateyPackages_CCR#232]
(moved from https://github.com/bcurran3/ChocolateyPackages/issues/153)

TheCakeIsNaOH commented on May 5, 2020
I've actually wanted to have choco-cleaner clean up the shims in bin, but I don't know a way to test the shims without running the program...

This would require running the shim but does not execute the program the shim is pointing too.
((shim_name.exe --shimgen-help) -split "`n" | sls -pattern "Target Exists").tostring() -split "'" | select -first 1 -skip 1

Returns string true if the target exists, false if the target does not exist.

**Comment by bcurran3** [comment]
Basically this but I need to inject the deletions...

Get-ChildItem $ENV:ChocolateyInstall\bin\*.exe | ForEach-Object -Process {
((iex "$PSItem --shimgen-help") -split "`n" | sls -pattern "Target Exists").tostring() -split "'" | select -first 1 -skip 1}

**Comment by TheCakeIsNaOH** [comment]
This should work without having to use `iex`:
`(& "$PSItem" "--shimgen-help")`

**Comment by bcurran3** [comment]
Close but need to escape this shim command correctly:

Get-ChildItem $ENV:ChocolateyInstall\bin\*.exe | ForEach-Object -Process { if (!((iex "$PSItem --shimgen-help") -split "`n" | sls -pattern "Target Exists").tostring() -split "'" | select -first 1 -skip 1 ) {Write-Host "$PSItem Looks like a bad shim."}}

**Comment by bcurran3** [comment]
We were typing at the same time!

Should work either way - problem is that if the shim.exe has spaces in it, it fails.

i.e.

```
C:\ProgramData\chocolatey\bin\Windows : The term 'C:\ProgramData\chocolatey\bin\Windows' is not recognized as the name
of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ C:\ProgramData\chocolatey\bin\Windows ISO Downloader.exe --shimgen-he ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\chocolatey\bin\Windows:String) [], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException

You cannot call a method on a null-valued expression.
At line:1 char:80
+ ... ocess { if (!((iex "$PSItem --shimgen-help") -split "`n" | sls -patte ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by bcurran3** [comment]
> This should work without having to use `iex`:
> `(& "$PSItem" "--shimgen-help")`

That's it! I just need to create a bad shim scenario to finish testing.

**Comment by bcurran3** [comment]
This just got added with https://github.com/bcurran3/ChocolateyPackages/commit/132595809fc464bb3c916f3896e8196a56a3283a - I'll push the new version after I also add https://github.com/bcurran3/ChocolateyPackages/issues/177

Thanks for the assist @TheCakeIsNaOH!
