### ISSUE TITLE
Feature request for choco-cleaner and choco-package-list-backup packages

### ISSUE THREAD

**Issue by Valtarien** [bcurran3/ChocolateyPackages_CCR#239]
@bcurran3 Would you consider **implementing parameters/install arguments** for your **choco-cleaner** and **choco-package-list-backup** packages to **specify the time and days scheduled to run**, as you do in some of your other scheduled task packages? I believe you did so with all the others already. Thanks!

**Comment by bcurran3** [comment]
Yepper depper, already on the list. Just not high priority.
https://github.com/bcurran3/ChocolateyPackages/issues/46
