### ISSUE TITLE
SUMo (lite) - request package update

### ISSUE THREAD

**Issue by J-Arx** [bcurran3/ChocolateyPackages_CCR#242]
Opening this issue according [PACKAGE NOTES](https://github.com/bcurran3/ChocolateyPackages/blob/master/sumo/readme.md) as checksum fails due to a new SUMo (lite) version.

Suggested changes based on [commit](https://github.com/bcurran3/ChocolateyPackages/commit/ff95a5daa37a3d6bb498f1ff1ea0c41e2ff85bb5):
https://github.com/bcurran3/ChocolateyPackages/blob/master/sumo/sumo.nuspec
line 6 ` <version>5.12.7.479</version>`
https://github.com/bcurran3/ChocolateyPackages/blob/master/sumo/tools/ChocolateyInstall.ps1
line 7 `$checksum = 'a61fc95e4ab792cb1604a913c420771b3ece2f9357d24bbea24232a6a27e5544'`

Version 5.12.7.479 is released on 2021-02-20 according [changelog](https://www.kcsoftwares.com/bugs/changelog_page.php?project_id=11) and [announced](https://www.kcsoftwares.com) on February 20th 2021.

Checksum of new version found with command:
`certutil -hashfile sumo_lite.exe sha256`

@bcurran3, thanks for the information and maintaining the chocolatey packages.

Have a nice day.

**Comment by bcurran3** [comment]
You're welcome. Got this pushed out for you earlier today.

**Comment by J-Arx** [comment]
> You're welcome. Got this pushed out for you earlier today.

Checksum for `choco install sumo` seems resolved now for me. Hopefully also for the others. ;)
Thanks @bcurran3.
Only in the [Chocolatey SUMo (lite) Gallery](https://chocolatey.org/packages/sumo), the [Package Source](https://github.com/bcurran3/ChocolateyPackages/tree/master/sumo) link shows files till [commit sumo.5.12.6.478](https://github.com/bcurran3/ChocolateyPackages/commit/ff95a5daa37a3d6bb498f1ff1ea0c41e2ff85bb5) and not yet version 5.12.7.479.
If we can be of further assistance in this, please let us know. Then we can have a look to the possibilities.
All the best. 👍
