### ISSUE TITLE
choco-continuous-upgrader - new script package to update packages continuously throughout the day

### ISSUE THREAD

**Issue by bcurran3** [bcurran3/ChocolateyPackages_CCR#243]
REMINDER TO SELF:
 I have had it in my head to make a choco-instant-upgrades script at some point in the future. It'll watch the Feedburner RSS and then do upgrades based on comparing what you have installed and what has been recently pushed. Simple concept, but will take me a lot of time that I don't currently have to actually implement. One day....
p.s. I never thought about instigating a notification and a prompt for choco-instant-upgrades - I'll try to remember to work that in when it becomes time.

**Comment by bcurran3** [comment]
Not that same as I intended, but ChocoButler is pretty close:
https://community.chocolatey.org/packages/chocobutler

**Comment by silopolis** [comment]
With both we'd have choice of both controlled and unattended :+1:

**Comment by bcurran3** [comment]
I've actually started on this. 

I think "instant" is too ambitious and possibly too resource intensive/abusive. 

Current idea is check for and execute updates every 15 or 30 minutes (configurable).

https://github.com/bcurran3/ChocolateyPackages/tree/master/choco-continuous-upgrader

**Comment by bcurran3** [comment]
This is beta right now if anyone wants to try it. 
I'm pretty happy with it feature-wise and functionally.

The logic related to the config file overrides is buggy. I need to still go through and test the Notify, NoUpgrades, and # Minutes options related to it. But I'm hoping everything else is flawless and would love feedback if anyone's up to it.

https://community.chocolatey.org/packages/choco-continuous-upgrader
choco install choco-continuous-upgrader --version=0.1.0-beta1 --pre

**Comment by bcurran3** [comment]
I think this is done. I just pushed a release candidate to let it soak a bit.

https://community.chocolatey.org/packages/choco-continuous-upgrader/1.0.0-RC1
choco install choco-continuous-upgrader --version=1.0.0-RC1 --pre 

Would love to see feedback.
