### ISSUE TITLE
[choco-cleaner] not finding temp directory of ansible user

### ISSUE THREAD

**Issue by drdamour** [bcurran3/ChocolateyPackages_CCR#247]
we use ansible to execute chocolatey via https://docs.ansible.com/ansible/2.6/modules/win_chocolatey_module.html

this executes with user sssansibleopsys

we've found a bunch of older files at C:\Users\sssansibleopsys\AppData\Local\Temp\chocolatey

but the scheduled run of choco cleaner doesn't seem to find them.  I didnt' see a config setting to turn detection of this location on, please advise?

**Comment by bcurran3** [comment]
What version of the script are you running? 

If you're running v0.0.8.1+ and running as sssansibleopsys it should be working.

As sssansibleopsys you should check $env:temp / %temp% and verify it points to C:\Users\sssansibleopsys \AppData\Local\Temp.

Sometime in the near future I'm going to update it to find C:\Users\xxxxxx\AppData\Local\Temp\chocolatey under all userdirs and this should go away if the above didn't help.

**Comment by drdamour** [comment]
Im running the lattest version from chocolatey. 

Im unable to run as the sss account other than the nightly ansible process.

so based on your comments the scheduled task will never find user temp dirs.  

So i guess i need to add a call to the batch file at towards the end of my ansible script then

**Comment by bcurran3** [comment]
Calling from your batch file towards the end sounds like the best bet for now.

Again, all the users will be cleaned up in the near future.

**Comment by bcurran3** [comment]
Did I say "near" future? I meant "sometime in the future." 

It's high up on the priority to actually do this with the package.... I just need to find the time.

**Comment by bcurran3** [comment]
Finally done! v0.9.0.0

choco install choco-cleaner --pre 

Verify it works for you and I'll move it out of pre-release and into official release.
