### ISSUE TITLE
a GitHub Issue requesting winaero-tweaker to be updated

### ISSUE THREAD

**Issue by jesseklm** [bcurran3/ChocolateyPackages_CCR#25]
would be nice :-)

**Comment by bcurran3** [comment]
@jesseklm you've got me at a loss. What package are you talking about?

**Comment by jesseklm** [comment]
ah sorry, winaero-tweaker

**Comment by bcurran3** [comment]
Thanks.
Duplicate of https://github.com/bcurran3/ChocolateyPackages/issues/26
Already taken care of.
