### ISSUE TITLE
choco-package-list-backup - Weird bug (pseudo-solved) - set variable defaults / validate .config import

### ISSUE THREAD

**Issue by brian6932** [bcurran3/ChocolateyPackages_CCR#257]
I tried to upgrade choco-package-list-backup today and I was getting an error, so I tried removing it and reinstalling it, but I still kept getting the same error. When I install the package, the package is created and despite the errors, and Chocolatey saying that the package didn't install, I can run the command from terminal. However, I still get a post install error, this occurs no matter the version of choco-package-list-backup installed.

Chocolatey.log Error:
```
2021-05-11 17:18:29,116 25664 [ERROR] - The install of choco-package-list-backup was NOT successful.
2021-05-11 17:18:29,118 25664 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\choco-package-list-backup\tools\ChocolateyInstall.ps1'.
 See log for details.
2021-05-11 17:18:29,120 25664 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\choco-package-list-backup'
 to 'C:\ProgramData\chocolatey\lib-bad\choco-package-list-backup'
2021-05-11 17:18:31,128 25664 [DEBUG] - Attempting to delete file "C:\Users\brian\AppData\Local\NuGet\Cache\choco-package-list-backup.2021.05.10.nupkg".
2021-05-11 17:18:31,135 25664 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2021-05-11 17:18:31,136 25664 [INFO ] - 
2021-05-11 17:18:31,137 25664 [ERROR] - Failures
2021-05-11 17:18:31,138 25664 [ERROR] -  - choco-package-list-backup (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\choco-package-list-backup\tools\ChocolateyInstall.ps1'.
 See log for details.
2021-05-11 17:18:31,139 25664 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2021-05-11 17:18:31,142 25664 [DEBUG] - Exiting with -1
```
Terminal Error:
```
Choco Package List Backup Summary:
% : Exception calling "Substring" with "2" argument(s): "Length cannot be less than zero.
Parameter name: length"
At C:\tools\BCURRAN3\choco-package-list-backup.ps1:289 char:43
+ $PackagesConfigBody = $localPackageInfo | % {
+                                           ~~~
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,Microsoft.PowerShell.Commands.ForEachObjectCommand
```

**Comment by bcurran3** [comment]
Hi. The install error is related to the running of CPLB during install; same as when you ran it manually.

Now the question is why is it choking for you? And you're getting it for all versions, so this is something weird in your environment I'm guessing. PowerShell ver maybe? What version are you running?

**Comment by brian6932** [comment]
I used PowerShell 7.1.3, and also tried cmd, got the same error

**Comment by bcurran3** [comment]
This has not been tested with Core, please see if you have a problem when using non-Core, 3+ (5.1 preferred).

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/118197232-8a75ec00-b41c-11eb-8fb1-918296871351.png)
It happens regardless of shell, I tested cmd, poweshell core, and native Powershell, and still get the same error

**Comment by brian6932** [comment]
Any update on this?

**Comment by bcurran3** [comment]
in choco-package-list-backup.config, how do you have these set? Also try toggling them.
```
    <SaveTitleSummary>false</SaveTitleSummary>
    <SaveArguments>false</SaveArguments>
```

@TheCakeIsNaOH have you seen this problem?

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 No, I have not.

@brian6932 would you mind pasting the output of `choco list -lo -r -y`?

The reason is the result of that command is stored in a variable and then run through a foreach (`%`), and the individual elements all get `substring()` called on them, which is what is failing.

So, I'm thinking that there might be something going on with your list of packages perhaps.

**Comment by brian6932** [comment]
@TheCakeIsNaOH Here you go

```
PS C:\Windows\System32> choco list -lo -r -y
7zip.install|19.0
adb|31.0.1
aegisub|3.2.2.20161107
alacritty|0.8.0
alacritty.install|0.8.0
amd-ryzen-chipset|2021.2.4
anydesk.install|6.3.1
asio4all|2.14
audacity|3.0.2
audacity-ffmpeg|2.2.2.20181007
audacity-lame|3.100.0.20190331
autohotkey.install|1.1.33.09
autohotkey.portable|1.1.33.09
avidemux|2.7.8
bandizip|7.16
bulk-crap-uninstaller|5.0
CentBrowser|4.3.9.248
choco-cleaner|0.0.8.3
choco-upgrade-all-at-startup|2021.03.15
chocolatey|0.10.16-beta-20200806
chocolatey-core.extension|1.3.5.1
chocolatey-dotnetfx.extension|1.0.1
chocolatey-misc-helpers.extension|0.0.4
chocolatey-npm.extension|1.0.0
chocolatey-visualstudio.extension|1.9.0
chocolatey-windowsupdate.extension|1.0.4
ChocolateyPackageUpdater|0.6.13.0
cmake|3.20.2
cmake.install|3.20.2
ConEmu|21.3.14.0
cpu-z.install|1.96.0.20210512
ddu|18.0.3.9
dependency-windows10|10.2105
ditto|3.23.124.0
dns-benchmark|1.3.6668.20190425
dnscrypt-proxy|2.0.45
DotNet3.5|3.5.20160716
DotNet4.5.2|4.5.2.20140902
DotNet4.6.1|4.6.01055.20170308
dotnetcore-sdk|3.1.409
dotnetcore3-desktop-runtime|3.1.15
dotnetfx|4.8.0.20190930
eac|1.6
eartrumpet|2.1.8.0
epicgameslauncher|1.1.298.0
Everything|1.4.11005
exiftool|12.26
ffmpeg|4.4
FiraCode|5.2
fluent-terminal|0.7.1.0
freac|1.1.4
freac.portable|1.1.4
furmark|1.26.0.0
gimagereader|3.3.1
git|2.31.1
git.install|2.31.1
gitkraken|7.3.2
gmkvextractgui|2.5.2
goggalaxy|2.0.37.384
gpu-z|2.39.0
gulp-cli|2.3.0.20201126
hackfont|3.003
handbrake.install|1.3.3
hourglass.install|1.10
hwinfo.install|7.04
hwmonitor|1.44.0.20210421
icecat|78.10.1
instanteyedropper|1.75
javaruntime|8.0.231
jdk8|8.0.211
jre8|8.0.291
k-litecodecpackmega|16.2.0
KB2533623|2.0.0
KB2919355|1.0.20160915
KB2919442|1.0.20160915
KB2999226|1.0.20181019
KB3033929|1.0.5
KB3035131|1.0.3
KB3063858|1.0.0
KB3118401|1.0.5
ketarin|1.8.11
lame|3.100.20200409
libre-hardware-monitor|1.0.223
Listary|5.00.2843
lockhunter|3.3.4.20210409
lossless-cut|3.36.0
make|4.3
mkvtoolnix|56.1.0
mp3directcut|2.32
mp3tag|3.07
musicbee|3.4.7805
nodejs.install|16.2.0
nordvpn|6.36.6
notepadplusplus.install|7.9.5
obs-studio.install|26.1.1
openal|2.07.0.20170623
openjdk|16.0.1
OpenSSL.Light|1.1.1.20181020
origin|10.5.98.47688
patchcleaner|1.4.2.0
poshgit|0.7.3.1
powershell-core|7.1.3.20210315
powertoys|0.37.2
PSWindowsUpdate|2.2.0.2
python|3.9.5
python3|3.9.5
qbittorrent-enhanced|4.3.5.10
qttabbar|1038.0
quicklook|3.6.11
Recuva|1.53.1087
reshack|5.1.8
rufus|3.14
rust|1.52.1
screentogif|2.30.0
sdformatter|5.0.1
shexview|2.01
shmnview|1.41
shutup10|1.8.1420
simplewall|3.3.3
speccy|1.32.740.20200817
speedtest|1.0.0.1
steam-cleaner|2.4
steam-client|2.10.91.91
streamlink|2.1.0
streamlink-twitch-gui|1.11.0.20201229
syncthing|1.16.1
sysinternals|2021.4.23
taiga|1.4.0-beta2
testdisk-photorec|7.1
tidal|2.27.6.0
twitch|8.0.0.20201028
unchecky|1.2
vb-cable|43.0
vcredist140|14.28.29914
vcredist2010|10.0.40219.32503
vcredist2013|12.0.40660.20180427
vcredist2015|14.0.24215.20170201
vcredist2017|14.16.27033
visualstudio-installer|2.0.1
Waterfox|21053.2.1
winaero-tweaker.install|0.19.1.0
wincdemu|4.1.0.20171221
winscp.install|5.17.10
wiztree|3.41
wpd|1.4.1834
yarn|1.22.5
youtube-dl|2021.05.16
zoom|5.6.5.823
```

**Comment by TheCakeIsNaOH** [comment]
Hmm, that packages list is working for me.

Try running this, 
```
$localPackageInfo = & choco list -lo -r -y
$localPackageInfo | % {
  $_
  $($_.SubString(0, $_.IndexOf("|"))) 
}
```

If it fails, what is the last thing it printed out before failing.

If it does not fail, then I have no idea what is going on.

**Comment by brian6932** [comment]
@TheCakeIsNaOH Do I just enter this directly into a shell?

Cause if so, this is what I got:
```
PS C:\Windows\System32> $localPackageInfo = & choco list -lo -r -y
PS C:\Windows\System32> $localPackageInfo | % {
>>   $_
>>   $($_.SubString(0, $_.IndexOf("|")))
>> }
7zip.install|19.0
7zip.install
adb|31.0.1
adb
aegisub|3.2.2.20161107
aegisub
alacritty|0.8.0
alacritty
alacritty.install|0.8.0
alacritty.install
amd-ryzen-chipset|2021.2.4
amd-ryzen-chipset
anydesk.install|6.3.1
anydesk.install
asio4all|2.14
asio4all
audacity|3.0.2
audacity
audacity-ffmpeg|2.2.2.20181007
audacity-ffmpeg
audacity-lame|3.100.0.20190331
audacity-lame
autohotkey.install|1.1.33.09
autohotkey.install
autohotkey.portable|1.1.33.09
autohotkey.portable
avidemux|2.7.8
avidemux
bandizip|7.16
bandizip
bulk-crap-uninstaller|5.0
bulk-crap-uninstaller
CentBrowser|4.3.9.248
CentBrowser
choco-cleaner|0.0.8.3
choco-cleaner
choco-upgrade-all-at-startup|2021.03.15
choco-upgrade-all-at-startup
chocolatey|0.10.16-beta-20200806
chocolatey
chocolatey-core.extension|1.3.5.1
chocolatey-core.extension
chocolatey-dotnetfx.extension|1.0.1
chocolatey-dotnetfx.extension
chocolatey-misc-helpers.extension|0.0.4
chocolatey-misc-helpers.extension
chocolatey-npm.extension|1.0.0
chocolatey-npm.extension
chocolatey-visualstudio.extension|1.9.0
chocolatey-visualstudio.extension
chocolatey-windowsupdate.extension|1.0.4
chocolatey-windowsupdate.extension
ChocolateyPackageUpdater|0.6.13.0
ChocolateyPackageUpdater
cmake|3.20.2
cmake
cmake.install|3.20.2
cmake.install
ConEmu|21.3.14.0
ConEmu
cpu-z.install|1.96.0.20210512
cpu-z.install
ddu|18.0.3.9
ddu
dependency-windows10|10.2105
dependency-windows10
ditto|3.23.124.0
ditto
dns-benchmark|1.3.6668.20190425
dns-benchmark
dnscrypt-proxy|2.0.45
dnscrypt-proxy
DotNet3.5|3.5.20160716
DotNet3.5
DotNet4.5.2|4.5.2.20140902
DotNet4.5.2
DotNet4.6.1|4.6.01055.20170308
DotNet4.6.1
dotnetcore-sdk|3.1.409
dotnetcore-sdk
dotnetcore3-desktop-runtime|3.1.15
dotnetcore3-desktop-runtime
dotnetfx|4.8.0.20190930
dotnetfx
eac|1.6
eac
eartrumpet|2.1.8.0
eartrumpet
epicgameslauncher|1.1.298.0
epicgameslauncher
Everything|1.4.11005
Everything
exiftool|12.26
exiftool
ffmpeg|4.4
ffmpeg
FiraCode|5.2
FiraCode
fluent-terminal|0.7.1.0
fluent-terminal
freac|1.1.4
freac
freac.portable|1.1.4
freac.portable
furmark|1.26.0.0
furmark
gimagereader|3.3.1
gimagereader
git|2.31.1
git
git.install|2.31.1
git.install
gitkraken|7.3.2
gitkraken
gmkvextractgui|2.5.2
gmkvextractgui
goggalaxy|2.0.37.384
goggalaxy
gpu-z|2.39.0
gpu-z
gulp-cli|2.3.0.20201126
gulp-cli
hackfont|3.003
hackfont
handbrake.install|1.3.3
handbrake.install
hourglass.install|1.10
hourglass.install
hwinfo.install|7.04
hwinfo.install
hwmonitor|1.44.0.20210421
hwmonitor
icecat|78.10.1
icecat
instanteyedropper|1.75
instanteyedropper
javaruntime|8.0.231
javaruntime
jdk8|8.0.211
jdk8
jre8|8.0.291
jre8
k-litecodecpackmega|16.2.0
k-litecodecpackmega
KB2533623|2.0.0
KB2533623
KB2919355|1.0.20160915
KB2919355
KB2919442|1.0.20160915
KB2919442
KB2999226|1.0.20181019
KB2999226
KB3033929|1.0.5
KB3033929
KB3035131|1.0.3
KB3035131
KB3063858|1.0.0
KB3063858
KB3118401|1.0.5
KB3118401
ketarin|1.8.11
ketarin
lame|3.100.20200409
lame
libre-hardware-monitor|1.0.223
libre-hardware-monitor
Listary|5.00.2843
Listary
lockhunter|3.3.4.20210409
lockhunter
lossless-cut|3.36.0
lossless-cut
make|4.3
make
mkvtoolnix|57.0.0
mkvtoolnix
mp3directcut|2.32
mp3directcut
mp3tag|3.07
mp3tag
musicbee|3.4.7805
musicbee
nodejs.install|16.2.0
nodejs.install
nordvpn|6.36.6
nordvpn
notepadplusplus.install|7.9.5
notepadplusplus.install
obs-studio.install|26.1.1
obs-studio.install
openal|2.07.0.20170623
openal
openjdk|16.0.1
openjdk
OpenSSL.Light|1.1.1.20181020
OpenSSL.Light
origin|10.5.98.47688
origin
patchcleaner|1.4.2.0
patchcleaner
poshgit|0.7.3.1
poshgit
powershell-core|7.1.3.20210315
powershell-core
powertoys|0.37.2
powertoys
PSWindowsUpdate|2.2.0.2
PSWindowsUpdate
python|3.9.5
python
python3|3.9.5
python3
qbittorrent-enhanced|4.3.5.10
qbittorrent-enhanced
qttabbar|1038.0
qttabbar
quicklook|3.6.11
quicklook
Recuva|1.53.1087
Recuva
reshack|5.1.8
reshack
rufus|3.14
rufus
rust|1.52.1
rust
screentogif|2.30.0
screentogif
sdformatter|5.0.1
sdformatter
shexview|2.01
shexview
shmnview|1.41
shmnview
shutup10|1.8.1420
shutup10
simplewall|3.3.3
simplewall
speccy|1.32.740.20200817
speccy
speedtest|1.0.0.1
speedtest
steam-cleaner|2.4
steam-cleaner
steam-client|2.10.91.91
steam-client
streamlink|2.1.2
streamlink
streamlink-twitch-gui|1.11.0.20201229
streamlink-twitch-gui
syncthing|1.16.1
syncthing
sysinternals|2021.4.23
sysinternals
taiga|1.4.0-beta2
taiga
testdisk-photorec|7.1
testdisk-photorec
tidal|2.27.6.0
tidal
twitch|8.0.0.20201028
twitch
unchecky|1.2
unchecky
vb-cable|43.0
vb-cable
vcredist140|14.28.29914
vcredist140
vcredist2010|10.0.40219.32503
vcredist2010
vcredist2013|12.0.40660.20180427
vcredist2013
vcredist2015|14.0.24215.20170201
vcredist2015
vcredist2017|14.16.27033
vcredist2017
visualstudio-installer|2.0.1
visualstudio-installer
Waterfox|21053.2.1
Waterfox
winaero-tweaker.install|0.19.1.0
winaero-tweaker.install
wincdemu|4.1.0.20171221
wincdemu
winscp.install|5.17.10
winscp.install
wiztree|3.41
wiztree
wpd|1.4.1834
wpd
yarn|1.22.5
yarn
youtube-dl|2021.05.16
youtube-dl
zoom|5.6.5.823
zoom
```

**Comment by TheCakeIsNaOH** [comment]
@brian6932 Yes, enter it directly into a PowerShell window.

I'm out of ideas now. I have no idea why that would work but CPLB would fail.

**Comment by bcurran3** [comment]
@brian6932 go back to my previous comment about the variables in in choco-package-list-backup.config.... and verify that you do have a choco-package-list-backup.config.

I'm thinking that maybe choco-package-list-backup.config is not being loaded and that's the problem, though it should throw an error if not (pointing to line 47).

**Comment by brian6932** [comment]
@bcurran3 I haven't changed any of these values, so they should be default
This is what it says under my config:
```
<SaveTitleSummary>false</SaveTitleSummary>
<SaveArguments>false</SaveArguments>
```

**Comment by bcurran3** [comment]
...but I'm waiting to know what happens when you toggle those; i.e. set them to true. (Probably same result, but curious.)

**Comment by brian6932** [comment]
Oh ok, I'll try it, sry I misread what you said

**Comment by brian6932** [comment]
@bcurran3 Things is that this file has 3 paths I can see, which one of the them is the correct one?
`C:\Users\Public\Documents\ChocolateyPackageListBackup\choco-package-list-backup.config`
`C:\Users\username\Documents\ChocolateyPackageListBackup\choco-package-list-backup.config`
`C:\tools\BCURRAN3\choco-package-list-backup.config`

**Comment by bcurran3** [comment]
C:\tools\BCURRAN3\choco-package-list-backup.config. The others are backups.
Just run choco-package-list-backup -EditConfig

**Comment by brian6932** [comment]
Ok, I toggled both of them, it seems to fix it, and I toggled them back, and it seems to still stay fixed. I have no idea what happened lol.

**Comment by bcurran3** [comment]
Yeah now that's weird. 

My guess was that SaveTitleSummary and SaveArguments weren't getting set to false and were null and that caused the problem. Why? I don't know. 

The weird part is that I would THINK that setting them to true would continue the problem if the values weren't being imported and assigned. 

So we figured out what the problem was and where it was, but not why the problem happened. Corrupt or bad .config file? Maybe. Dunno. 

The problem isn't the overall logic of the script. Since noone else has bumped into this, it's not common, but maybe I'll add some basic checking to make sure each imported variable actually gets imported in the future or set all the variables to false as default before importing them in the config. I think I'm going to implement the latter and leave this issue open until I do it...

**Comment by bcurran3** [comment]
NOTE TO SELF:

Set all the following to default values before importing from config:
$PackagesListFile    = $ConfigFile.Settings.Preferences.PackagesListFile
$SaveFolderName      = $ConfigFile.Settings.Preferences.SaveFolderName
$SaveArguments       = $ConfigFile.Settings.Preferences.SaveArguments
$SaveTitleSummary    = $ConfigFile.Settings.Preferences.SaveTitleSummary
$SaveVersions        = $ConfigFile.Settings.Preferences.SaveVersions
$AppendDate          = $ConfigFile.Settings.Preferences.AppendDate
$CustomPath          = $ConfigFile.Settings.Preferences.CustomPath
$CustomPath2         = $ConfigFile.Settings.Preferences.CustomPath2
$SaveAllProgramsList = $ConfigFile.Settings.Preferences.SaveAllProgramsList
$AllProgramsListFile = $ConfigFile.Settings.Preferences.AllProgramsListFile
$DefaultUserProfile  = $ConfigFile.Settings.Preferences.DefaultUserProfile
$PreProcessScript    = $ConfigFile.Settings.Preferences.PreProcessScript
$PostProcessScript   = $ConfigFile.Settings.Preferences.PostProcessScript
$SaveArguments       = $ConfigFile.Settings.Preferences.SaveArguments

$UseCustomPath  = $ConfigFile.Settings.Preferences.UseCustomPath
$UseCustomPath2 = $ConfigFile.Settings.Preferences.UseCustomPath2
$UseDocuments   = $ConfigFile.Settings.Preferences.UseDocuments
$UseHomeShare   = $ConfigFile.Settings.Preferences.UseHomeShare 
$UseBox         = $ConfigFile.Settings.Preferences.UseBox
$UseDropbox     = $ConfigFile.Settings.Preferences.UseDropbox
$UseGoogleDrive = $ConfigFile.Settings.Preferences.UseGoogleDrive
$UseiCloudDrive = $ConfigFile.Settings.Preferences.UseiCloudDrive
$UseNextcloud   = $ConfigFile.Settings.Preferences.UseNextcloud
$UseOneDrive    = $ConfigFile.Settings.Preferences.UseOneDrive
$UseownCloud    = $ConfigFile.Settings.Preferences.UseownCloud
$UseReadyCLOUD  = $ConfigFile.Settings.Preferences.UseReadyCLOUD
$UseResilioSync = $ConfigFile.Settings.Preferences.UseResilioSync
$UseSeafile     = $ConfigFile.Settings.Preferences.UseSeafile
$UseTonidoSync  = $ConfigFile.Settings.Preferences.UseTonidoSync
$UseDefaultUserProfile = $ConfigFile.Settings.Preferences.UseDefaultUserProfile

**Comment by bcurran3** [comment]
Default config settings added to the 09-22-2021 release.
