### ISSUE TITLE
Update intel-dsa checksum

### ISSUE THREAD

**Issue by tjames37** [bcurran3/ChocolateyPackages_CCR#258]
Hello,

Can you please update the checksum on:
https://github.com/bcurran3/ChocolateyPackages/blob/master/intel-dsa/tools/chocolateyinstall.ps1

To:
350c6a4ecb33ee2260865ba65a42eb18a2ea31d3f0c2ee6ff814954647bbd52e

Thanks!

**Comment by bcurran3** [comment]
Updated!
