### ISSUE TITLE
[choco-cleaner] Merge conflict separators present in choco-cleaner.ps1

### ISSUE THREAD

**Issue by Rohaq** [bcurran3/ChocolateyPackages_CCR#259]
Looks like somebody merged into master without fixing their commits! Doh! 🤦🏻‍♂️

L318 to L326: https://github.com/bcurran3/ChocolateyPackages/blob/375d6b717b988d21df759c4f83104900e7027b78/choco-cleaner/tools/choco-cleaner.ps1#L318-L326

**Comment by bcurran3** [comment]
Thanks. I just manually fixed it.

I fake my way through GH! :)
