### ISSUE TITLE
Choco Upgrade All task failed to upgrade Signal and Spotify, running "choco upgrade all" in powershell succeeded 

### ISSUE THREAD

**Issue by nixsee** [bcurran3/ChocolateyPackages_CCR#260]
Not sure what to make of this. Are there particular logs I can share with you?

**Comment by bcurran3** [comment]
A copy and paste of what you saw is a good start. FYI: choco-upgrade-all runs in PowerShell.

**Comment by bcurran3** [comment]
I'm going to close this as my best guess there was a problem with the computer not the script.
