### ISSUE TITLE
Personal Folder information created by Installation

### ISSUE THREAD

**Issue by Jarli01** [bcurran3/ChocolateyPackages_CCR#262]
While I would love to use this package, I can't possibly recommend using it to schedule this process since your package creates numerous custom folders with your name on it at the root level of the computer.

Please use the default installation paths provided `C:\ProgramData\chocolatey` and if needed create a simple discreetly named folder within here for this and your other packages.

I think this discreet folder should be added under the `extensions` folder and contain everything required in a folder titled `choco-upgrade-all-at` or if you wanted to abbreviate it `cuaa`. 

Please consider making these proposed changes

**Comment by bcurran3** [comment]
Dustin - You're homework assignment is to do research and discovery on $env:ChocolateyToolsLocation.
