### ISSUE TITLE
backupper-standard - Checksum error on Win 10

### ISSUE THREAD

**Issue by stalsma-palmetto** [bcurran3/ChocolateyPackages_CCR#264]
Chocolatey v0.10.15
Installing the following packages:
backupper-standard
By installing you accept licenses for the packages.
Progress: Downloading backupper-standard 6.3.0... 100%

backupper-standard v6.3.0 [Approved]
backupper-standard package files install completed. Performing other installation steps.
The package backupper-standard wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '3693170769DC0D750792DBDCB48D6E9B54C80D2C92381DE1E19A36954ADC4995'.
Downloading backupper-standard
  from 'https://www2.aomeisoftware.com/download/adb/AOMEIBackupperStd.exe'
Progress: 100% - Completed download of C:\Users\xxxxxxxxxxx\AppData\Local\Temp\chocolatey\backupper-standard\6.3.0\AOMEIBackupperStd.exe (113.26 MB).
Download of AOMEIBackupperStd.exe (113.26 MB) completed.
Error - hashes do not match. Actual value was '3693170769DC0D750792DBDCB48D6E9B54C80D2C92381DE1E19A36954ADC4995'.
ERROR: Checksum for 'C:\Users\xxxxxxxxxxx\AppData\Local\Temp\chocolatey\backupper-standard\6.3.0\AOMEIBackupperStd.exe' did not meet '15F7687F8EEA678B7527F1C90623673B36A26618C005CC3BE35FBD69BDE01A78' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of backupper-standard was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\backupper-standard\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - backupper-standard (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\backupper-standard\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by bcurran3** [comment]
I just added eugb as a maintainer today. He'll be updating it going forward.
