### ISSUE TITLE
Please update XTU to 7.4.0.26 version

### ISSUE THREAD

**Issue by jeansagi** [bcurran3/ChocolateyPackages_CCR#266]
Hi,

Chocolatey currently reports intel-xtu to be on 7.3.0.33.

However, it is on version **7.4.0.26** on Intel site:
https://downloadcenter.intel.com/download/29183/Intel-Extreme-Tuning-Utility-Intel-XTU-?wapkw=xtu

So, please, if possible, upgrade Chocolatey package to Intel's latest version of XTU.

Kind regards.

J.

**Comment by bcurran3** [comment]
Sorry. I refuse, because I just pushed v7.5.3.3 instead. :)
