### ISSUE TITLE
choco-upgrade-all-at | DeleteNewDesktopIcons, "Cannot bind argument to parameter 'ReferenceObject' because it is null." when set to true

### ISSUE THREAD

**Issue by tordenflesk** [bcurran3/ChocolateyPackages_CCR#267]
```
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\tools\bcurran3\choco-upgrade-all.ps1:77 char:48
+ ... sNew = Compare-Object -ReferenceObject ($UserDesktopIconsPre) -Differ ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

**Comment by kdistin** [comment]
I have this problem too.
It appears that if there are no shortcuts already on the user's desktop, $UserDesktopIconsPre is empty/null and therefore cannot be used in the comparison.
A similar error occurs if there are no shortcuts in the Public Desktop folder.

**Comment by bcurran3** [comment]
Thanks for finding that. Easy enough to fix.

**Comment by bcurran3** [comment]
I think this is hammered out. Can you test please?

This is the changed part:

```
# Delete new Desktop icons if configured to do so
if ($DeleteNewDesktopIcons -eq 'True'){
	if ($UserDesktopIconsPre.count -ne '0' -and $UserDesktopIconsPost.count -ne '0'){
       $IconsNew = Compare-Object -ReferenceObject ($UserDesktopIconsPre) -DifferenceObject ($UserDesktopIconsPost) -PassThru
       if ($IconsNew -ne $null) { del $IconsNew.fullname }
	   }
	if ($PublicDesktopIconsPre.count -ne '0' -and $PublicDesktopIconsPost.count -ne '0'){
       $IconsNew = Compare-Object -ReferenceObject ($PublicDesktopIconsPre) -DifferenceObject ($PublicDesktopIconsPost) -PassThru
       if ($IconsNew -ne $null) { del $IconsNew.fullname }
       }
  }
# Delete new Start Menu icons if configured to do so
if ($DeleteNewStartMenuIcons -eq 'True'){
	if ($UserStartMenuIconsPre.count -ne '0' -and $UserStartMenuIconsPost.count -ne '0'){
       $IconsNew = Compare-Object -ReferenceObject ($UserStartMenuIconsPre) -DifferenceObject ($UserStartMenuIconsPost) -PassThru
       if ($IconsNew -ne $null) { del $IconsNew.fullname }
	   }
	if ($PublicStartMenuIconsPre.count -ne '0' -and $PublicStartMenuIconsPost.count -ne '0'){
       $IconsNew = Compare-Object -ReferenceObject ($PublicStartMenuIconsPre) -DifferenceObject ($PublicStartMenuIconsPost) -PassThru
       if ($IconsNew -ne $null) { del $IconsNew.fullname }
       }
  }
```

I'm going to push it into GH too so you can get the whole file there if you wish. https://github.com/bcurran3/ChocolateyPackages/commit/93adffd722b3d8b54a27ccb3a82b73ba7e223172

**Comment by kdistin** [comment]
I've not been able to test this yet, but I'm not sure it will work.
If there are no icons on the user desktop, $UserDesktopIconsPre will be null, so $UserDesktopIconsPre.count will fail.
Furthermore, if this did work and returned 0 (for no icons), your if() test will fail and the new icons will not be deleted.

I think it needs to be something like: 
if($UserDesktopIconsPre -eq $null -and $UserDesktopIconsPost.count -ne '0'){
del $UserDesktopIconsPost.fullname}
else {
$IconsNew = Compare-Object -ReferenceObject ($UserDesktopIconsPre) -DifferenceObject ($UserDesktopIconsPost) -PassThru
       if ($IconsNew -ne $null) { del $IconsNew.fullname }}
}

Forgive me if that code is not correct, I'm not a PowerShell user!

**Comment by kdistin** [comment]
On reflection, that's not right either!
If there are no new icons $UserDesktopIconsPost will also be null ...

**Comment by kdistin** [comment]
The answer may be here:
https://stackoverflow.com/questions/13504346/powershell-compare-object-on-empty-folder

**Comment by wrecklass** [comment]
> The answer may be here:
> https://stackoverflow.com/questions/13504346/powershell-compare-object-on-empty-folder

Indeed, that does resolve the problem here. It eliminates the issue with the variables being set to $null. Simple fix.

**Comment by wrecklass** [comment]
I have tested and can verify that the solution from the StackOverflow article found by @kdistin above does resolve this issue. 

I made these simple changes to my scripts as:

Original:
``` powershell
if (Test-Path "$env:USERPROFILE\Desktop") {$UserDesktopIconsPre = Get-ChildItem -Path "$env:USERPROFILE\Desktop\*.lnk"}
```

New Line:
``` powershell
if (Test-Path "$env:USERPROFILE\Desktop") {$UserDesktopIconsPre = @(Get-ChildItem -Path "$env:USERPROFILE\Desktop\*.lnk")}
```

I did the same for each line where the `Get-ChildItem` is being used to gather the list of links for comparison. The `Compare-Object` process works fine on an empty array but fails when comparing strings that are null.

I can do a PR if that is useful.

**Comment by wrecklass** [comment]
This turned out to be a bit more complex than I had thought. As pointed out in the config file, when running the script "`AS System`" when `TaskSchd.msc` runs will not find the default Desktop because the script doesn't know who that is. So I find to even get the _DeleteUserDesktopIcons_ feature to work I had to enter my username so that the script would always find my "C:\Users\wrecklass\Desktop" folder when run this way. This probably should be documented and pointed out when a user installs the scripts.

In addition it turns out that on some newer systems that location may not exist at all, which causes the script to fail. On one of my systems my personal desktop is in "C:\Users\wrecklass\OneDrive\Desktop". The easy work-around is to create a Junction (NTFS Soft Link) from "C:\Users\wrecklass\Desktop -> C:\Users\wrecklass\OneDrive\Desktop" but a new bug should probably be entered to resolve this issue in a more general way.

**Comment by bcurran3** [comment]
Did you read the notes in the config file? Specifically:
`# * DefaultUserProfile - Default user profile to use when running as scheduled task; e.g. William, Robert, Benjamin (Look at C:\Users)`

**Comment by bcurran3** [comment]
p.s. Thanks for the testing and verification. You an do a PR but my repo is out of sync. It will be a while before I pull in any PRs. I'll most likely test, push a new package and the repo will still be behind for awhile.

**Comment by wrecklass** [comment]
Yes, I read the notes in the config file, this was my clue to what part of the problem was. My note was simply pointing out that if someone installs _choco-upgrade-all-at_, they are not made aware of this issue. Though, of course, if they want to delete icons post-upgrade, they will have to edit that file.

For now I'm just letting the script leave desktop icons on while I test. At least it flags the user that updates were installed.

**Comment by bcurran3** [comment]
Now that I have time to look into this properly...

I just fixed it. Actually easy as all I had to do is check each of the pre upgrade icon count variables for null and set to 0 if so. Tested and works fine now. Also added detailed logging and some other minor stuff.

choco install choco-upgrade-all-at --version=0.0.7
