### ISSUE TITLE
Request: Roboto Font Family as a Choco Package.

### ISSUE THREAD

**Issue by khernandezbtx** [bcurran3/ChocolateyPackages_CCR#269]
As requested from your email:

Would it be possible for you to create a Roboto font package? 
Your Awesome Font package seems to work the best on my machines!
https://fonts.google.com/specimen/Roboto

Thanks!

**Comment by bcurran3** [comment]
Ha! Easy enough. I just don't have much time right now, but I'll be glad to keep it on the TDL.

**Comment by bcurran3** [comment]
You do know these packages exist right?:
roboto.font 2.136 [Approved]
RobotoFonts 4.0.0.1 [Approved]
