### ISSUE TITLE
Update TeamSpeak Server install to version 3.13.6

### ISSUE THREAD

**Issue by TheFatalHalfInch** [bcurran3/ChocolateyPackages_CCR#271]
I used your package to install a teamspeak server the other day. While it did install as expected, the server fails to launch properly since it is an outdated version. 

If you could update to 3.13.6, i (and the 2 other people on earth that still use teamspeak) would greatly appreciate it!

Here are the links and checksums that you should need to update the install package:
`$url          = 'https://files.teamspeak-services.com/releases/server/3.13.6/teamspeak3-server_win32-3.13.6.zip'
$checksum     = 'f52cddfd2f1297756afa12d758718b3ee34b88c0e7962fb75985877f480e0d71'
$url64        = 'https://files.teamspeak-services.com/releases/server/3.13.6/teamspeak3-server_win64-3.13.6.zip'
$checksum64   = '6ffe2fad26cd68cbd8c23f7361469f7eaba9b267f320daf9cce90ed28e4b3bca'`

Thank you!

**Comment by bcurran3** [comment]
@TheFatalHalfInch - done.

 I don't use this and have no interest in it. Would you like to maintain it?
