### ISSUE TITLE
Support Box Drive in choco-package-list-backup

### ISSUE THREAD

**Issue by t1m0thyj** [bcurran3/ChocolateyPackages_CCR#277]
Now that Box Sync has been deprecated in favor of Box Drive, the default Box folder is `~/Box` instead of `~/Box Sync`:
https://github.com/bcurran3/ChocolateyPackages/blob/632aab9c1fe4879ee64e2cdb71e5e295d9a40c8e/choco-package-list-backup/tools/choco-package-list-backup.ps1#L332-L336

**Comment by bcurran3** [comment]
Thanks. Please verify below looks correct:

```
# Backup Chocolatey package names on local computer to packages.config file in Box (Drive) directory if it exists
if ($UseBox -Match "True" -and (Test-Path "$env:USERPROFILE\Box"))
   {
    $SavePath = "$env:USERPROFILE\Box\$SaveFolderName\$env:COMPUTERNAME"
    Write-PackagesConfig
   }  
```

**Comment by t1m0thyj** [comment]
@bcurran3 Yes, I modified the PowerShell script on my machine to use the snippet you posted and now it works without needing to set a custom path. 🙂

**Comment by bcurran3** [comment]
Thanks for the info and verification - I'll push out an update now.
