### ISSUE TITLE
Winaero Tweaker 1.31.0.0 installation fails

### ISSUE THREAD

**Issue by wb7664** [bcurran3/ChocolateyPackages_CCR#278]
As instructed in the comments, when the hash fails, here is an issue, but I'm not sure the problem is, or is only, an updated version with different hash, because installation still fails with the --ignore-checksums switch.

_Here is what happened first try:_
---
`PS C:\Windows\system32> choco upgrade winaero-tweaker.install -y
Chocolatey v0.11.2
Upgrading the following packages:
winaero-tweaker.install
By upgrading, you accept licenses for the packages.
winaero-tweaker.install is not installed. Installing...
Progress: Downloading winaero-tweaker.install 1.31.0.0... 100%
Progress: Downloading winaero-tweaker.install 1.31.0.0... 100%

winaero-tweaker.install v1.31.0.0 [Approved]
winaero-tweaker.install package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'AFF82AE47D93DA0CA329D560A2B76FDBC47077B5DCA5B1BC840979AFBA5EE270'.
Downloading winaero-tweaker.install
  from 'https://winaero.com/downloads/winaerotweaker.zip'
Progress: 100% - Completed download of C:\temp\wslboyer\chocolatey\winaero-tweaker.install\1.31.0.0\winaerotweaker.zip (2.43 MB).
Download of winaerotweaker.zip (2.43 MB) completed.
Error - hashes do not match. Actual value was 'AFF82AE47D93DA0CA329D560A2B76FDBC47077B5DCA5B1BC840979AFBA5EE270'.
ERROR: Checksum for 'C:\temp\wslboyer\chocolatey\winaero-tweaker.install\1.31.0.0\winaerotweaker.zip' did not meet '175604C25B8650A83E0A0B42031172FC38E5C1BBDCE17D48CA0964EF2F2F6A7D' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of winaero-tweaker.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winaero-tweaker.install (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools\chocolateyinstall.ps1'.
 See log for details.`
---

_Here is what happens with ignore hash switch_
---
`PS C:\Windows\system32> choco upgrade winaero-tweaker.install -y --ignore-checksums
Chocolatey v0.11.2
Upgrading the following packages:
winaero-tweaker.install
By upgrading, you accept licenses for the packages.
winaero-tweaker.install is not installed. Installing...
Progress: Downloading winaero-tweaker.install 1.31.0.0... 100%
Progress: Downloading winaero-tweaker.install 1.31.0.0... 100%

winaero-tweaker.install v1.31.0.0 [Approved]
winaero-tweaker.install package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
Extracting C:\temp\chocolatey\winaero-tweaker.install\1.31.0.0\winaerotweaker.zip to C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools...
C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools
Installing winaero-tweaker.install...
WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools\WinaeroTweaker-1.31.0.0-setup.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The upgrade of winaero-tweaker.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winaero-tweaker.install (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools\chocolateyinstall.ps1'.
 See log for details.`
---

When I manually extracted the .zip from
C:\temp\chocolatey\winaero-tweaker.install\1.31.0.0\winaerotweaker.zip 
to 
C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools
**Note, had to run unzip program as administrator to do it.**

Then, when ran the .cmd in C:\ProgramData\chocolatey\lib\winaero-tweaker.install\tools, installation was successful.

**Comment by bcurran3** [comment]
Hi. I'm no longer maintaining this package, dgalbraith is. Please send a message through Chocolatey's contact maintainer's link so he'll get notified.
