### ISSUE TITLE
hp-universal-print-driver-pcl/ps packages need updating

### ISSUE THREAD

**Issue by serrc-techops** [bcurran3/ChocolateyPackages_CCR#282]
It appears that the ftp download links are no longer active.

Using
https://ftp.hp.com/pub/softlib/software13/COL40842/ds-99375-23/upd-ps-x32-7.0.0.24832.exe
and 
https://ftp.hp.com/pub/softlib/software13/COL40842/ds-99376-23/upd-ps-x64-7.0.0.24832.exe
both result in 404 errors.

**Comment by bcurran3** [comment]
What package is this for? I'm guessing HP Universal printer drivers?

**Comment by serrc-techops** [comment]
Yes that is correct. These are the two packages that I noticed having the issue:

- https://community.chocolatey.org/packages/hp-universal-print-driver-ps
- https://community.chocolatey.org/packages/hp-universal-print-driver-pcl

**Comment by bcurran3** [comment]
I'm handing this over to someone else to maintain soon. I may or may not update in the meantime.

**Comment by bcurran3** [comment]
Ashertoo is updating this package now.
