### ISSUE TITLE
Plexamp 3.8.2 verification test failed

### ISSUE THREAD

**Issue by IndrekHaav** [bcurran3/ChocolateyPackages_CCR#284]
[Plexamp 3.8.2](https://community.chocolatey.org/packages/plexamp/3.8.2) package is failing verification tests.

From the gist, it looks like the installer timed out:

```
2021-11-12 20:44:33,275 2200 [DEBUG] - Elevating permissions and running ["C:\ProgramData\chocolatey\lib\plexamp\tools\Plexamp Setup 3.8.2.exe" /S ]. This may take a while, depending on the statements.
2021-11-12 21:29:31,778 2200 [WARN ] - Chocolatey timed out waiting for the command to finish. The timeout 
 specified (or the default value) was '2700' seconds. Perhaps try a 
 higher `--execution-timeout`? See `choco -h` for details.
```

**Comment by bcurran3** [comment]
Yeah. This has been happening the last three or four releases. There must be some new dependency or an incompatibility with the testing environment as all versions pass in my local machines. I need to test in my 2012 dev server but haven't had a chance yet.

**Comment by bcurran3** [comment]
p.s. if you're anxious you can just force the install passing the --version parameter.

**Comment by IndrekHaav** [comment]
I'm in no hurry, I have 3.8.2 manually installed. I was looking to switch it over to Chocolatey, but noticed the package was out of date.

Anyway, I set up a Windows Server 2012 eval VM, and the installer worked fine, no extra prompts or anything.

**Comment by bcurran3** [comment]
Thanks for the info. Does your 2012 eval VM have ANY updates installed or any runtimes such as VisualC... those could make it work. The Chocolatey test environment is completely bare bones.

You can still install with Chocolatey - cinst plexamp --version=3.8.2

**Comment by bcurran3** [comment]
OK. You made me get off my but and test...

Worked fine for me. I have no idea why this fails on Chocolatey's servers!

![image](https://user-images.githubusercontent.com/14026600/146264643-5699e1e8-6889-4f1f-b2b7-6dbc55cc7353.png)

**Comment by bcurran3** [comment]
Testing a theory...
Pushed a new package version which stops PlexAmp if running post install.

**Comment by IndrekHaav** [comment]
> Does your 2012 eval VM have ANY updates installed or any runtimes such as VisualC... those could make it work.

No, I just downloaded the ISO from MS, installed and then downloaded and installed Plexamp. No updates or anything.

Maybe it's a Server Core thing? I tested with a GUI install, not sure how the Chocolatey verifier service is set up.

Edit: and looks like Chocolatey actually tests on 2012 R2.

**Comment by bcurran3** [comment]
It's a stock 2012, no core versions back then.

**Comment by bcurran3** [comment]
My hunch was right. Don't know why it has a problem in the CTE, but it doesn't now...

'plexamp' is Approved.
chocolatey-ops left the following comment(s):
plexamp has passed automated virus scanning.
The package was approved by chocolatey-ops on 15 Dec 2021.
