### ISSUE TITLE
23 Intel Chipset Device Software (Install) 10.1.18716.8265 (From Chocolatey)

### ISSUE THREAD

**Issue by ikehersh92** [bcurran3/ChocolateyPackages_CCR#290]
Whenever I try to execute this command choco install intel-chipset-device-software. It fails I think that it needs to be updated please let me know if you need more information

**Comment by bcurran3** [comment]
If you provide the error messages it should provide the details to know the problem instead of guess.

**Comment by bcurran3** [comment]
I just checked and it appears there is a new version out. I'll update the package.

**Comment by bcurran3** [comment]
Updated.
https://community.chocolatey.org/packages/intel-chipset-device-software/10.1.18793.8276
