### ISSUE TITLE
Logitech Options: Proper silent install available

### ISSUE THREAD

**Issue by j10k** [bcurran3/ChocolateyPackages_CCR#293]
Hi,
it seems from https://prosupport.logi.com/hc/en-us/articles/1500002995241-Mass-installation-and-configuration-of-Logitech-Options that a proper silent install is now possible, which could replace the current autoHotkey hack. Supported parameters are
```
/quiet
/analytics
/flow
/sso
/update
```
All the best and thanks for maintaining this repo

**Comment by bcurran3** [comment]
That's good news. I'll test and use for the next release. Thanks.

**Comment by bcurran3** [comment]
Just tested and verified these options work, they do. Yay! Nice to have Logitech's devs putting out a "normal" (cough cough) installer again. 

I just updated the package with this and the new version...so nice to get rid of AHK and seriously hope I don't need it again in the future.

Thanks.
