### ISSUE TITLE
`chocolatey-preinstaller-checks.extension` is incompatible with chocolatey 1.0.1

### ISSUE THREAD

**Issue by brian6932** [bcurran3/ChocolateyPackages_CCR#294]
![image_188](https://user-images.githubusercontent.com/18603393/160045487-3fea8653-1044-43bc-99c0-854e6db2c5f9.png)

**Comment by bcurran3** [comment]
Yeah it has a dependency on Chocolatey being less than v1.0.  Choco v1.0 had a milestone of being multi-instance aware. Pretty sure that didn't happen. I'll have to investigate if the milestone got updated or push a new ver without the dependency (most likely).

**Comment by yohudood** [comment]
nice to see you are working on it

**Comment by DragRedSim** [comment]
Same thing occurs with choco-protocol-support (also multi-instance issues, based on the comment to only install one package at a time before chocolatey v1.0. Though it allows install of the update to v1.0, anything newer is blocked, such as the 1.0.1 and 1.1.0 point releases we've since had.

**Comment by brian6932** [comment]
Resolved
