### ISSUE TITLE
VNC Server

### ISSUE THREAD

**Issue by user4302** [bcurran3/ChocolateyPackages_CCR#298]
hi, not really an issue, more of a clarification that i seek.

why is VNC server not a chocolatey package?
will i get in trouble if i try to make one and upload it to chocolatey?

**Comment by bcurran3** [comment]
VNC server is now called VNC Connect and is available via Chocolatey at:
https://community.chocolatey.org/packages/vnc-connect

**Comment by user4302** [comment]
Thank you so much.
