### ISSUE TITLE
(choco-cleaner) Adding to path environment variable really necessary?

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [bcurran3/ChocolateyPackages_CCR#308]
Is it really necessary to add your tools folder to the system path environment variable?

As you already shim `choco-cleaner` to `chocolatey\bin` folder, which is included by chocolatey in the path variable, your chocolateytools subfolder BCURRAN3 looks too much.

I would suggest to remove that line from [chocolateyinstall.ps1](https://github.com/bcurran3/ChocolateyPackages/blob/master/choco-cleaner/tools/chocolateyinstall.ps1):
```powershell
if ($ENV:Path -NotMatch "BCURRAN3"){ Install-ChocolateyPath "$scriptDir" "Machine" ; refreshenv }
```

**Comment by gs71** [comment]
I agree: system path environment variable should not be "polluted" with the BCURRAN3 folder

**Comment by bcurran3** [comment]
It was necessary at one time. It is not necessary any more.
It was removed in v0.0.9.0.
(Now I've got to remember to pull it from other scripts that no longer need it....)

choco install choco-cleaner --pre 

Glad you like and use the script even with the one "polluted" line. You're welcome BTW.
