### ISSUE TITLE
add Logi Options+ package

### ISSUE THREAD

**Issue by CWempe** [bcurran3/ChocolateyPackages_CCR#312]
There is a new Logitech Software that replaces the older Logitech Options software.

old: https://community.chocolatey.org/packages/logitech-options

new: https://www.logitech.com/de-de/software/logi-options-plus.html

**Comment by bcurran3** [comment]
Great suggestion. I did this awhile ago and someone else beat me to creating the package by three days. Oh well. One less headache to worry about. :-)
