### ISSUE TITLE
Drivermax fails hash check

### ISSUE THREAD

**Issue by moomoohk** [bcurran3/ChocolateyPackages_CCR#313]
Package appears to need updating. Thanks.

**Comment by bcurran3** [comment]
It was updated but the current version went over the virus testing limit. So It’s stuck in moderation. 

 

I’m running it.

 

If you want cinstall drivermax –version=14.15.0.12

 

From: moomoohk ***@***.***> 
Sent: Sunday, November 27, 2022 12:25 PM
To: bcurran3/ChocolateyPackages ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bcurran3/ChocolateyPackages] Drivermax fails hash check (Issue #313)

 

Package appears to need updating. Thanks.
