### ISSUE TITLE
show   message  via   code in powershell

### ISSUE THREAD

**Issue by samantrader** [bcurran3/ChocolateyPackages_CCR#316]
Hi
how can  show  message  with  code  via   powershell 
  example :

ps  c:\\  show-sticky   "my  message "

**Comment by bcurran3** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-7.3

@samantrader - not appropriate. Microsoft makes PowerShell, please go to them for support.

**Comment by samantrader** [comment]
I  mean    use  your  package    "simple-sticky-notes"  with   powershell  code  and   show  some  text

**Comment by bcurran3** [comment]
I don't make the Simple Sticky Notes program or the PowerShell program. I package the Simple Sticky Notes program for Chocolatey using PowerShell.  I don't support the other programs. It's not clear to me what you really want, but it is clear to me that the answer lies elsewhere.
