### ISSUE TITLE
seatools - Upgrade is not silent

### ISSUE THREAD

**Issue by brogers5** [bcurran3/ChocolateyPackages_CCR#317]
I just upgraded to v5.1.176 from v5.0.171 and got the following prompt, which required me to manually confirm:

![Seatools Question Dialog](https://user-images.githubusercontent.com/6869577/219216374-772a0c19-ce98-4045-a85d-166f6c4ee5e6.png)

Guessing the install script may need to uninstall the current version as a workaround, or ideally get Seagate to fix this upstream and honor the "unattended" mode preference...

**Comment by bcurran3** [comment]
Yeah. Irony is I noticed that the day after I updated the package and did a cup all on another machine.

It'll need an AutoHotKey script in an update. 

AutoHotKey is an issue for me as 2.0 is incompatible with 1.x.... not sure if everyone has migrated and I haven't learned the diff yet. On the TDL.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
