### ISSUE TITLE
choco-cleaner: Get-Content : Cannot find path 'C:\config\chocolatey.config' because it does not exist. (choco `1.3.1`)

### ISSUE THREAD

**Issue by brian6932** [bcurran3/ChocolateyPackages_CCR#320]
```pwsh
Get-Content : Cannot find path 'C:\config\chocolatey.config' because it does not exist.
At C:\tools\bcurran3\choco-cleaner.ps1:72 char:25
+ ... onfigFile = Get-Content "$ENV:ChocolateyInstall\config\chocolatey.con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\config\chocolatey.config:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```
Seems like `1.3.1` moved dirs

**Comment by bcurran3** [comment]
Something's off here. Maybe you're running a super old version? Or a modified version? Choco-Cleaner shouldn't ever be looking there.

This is what it should be trying to read:
$ChocoConfigFile = Get-Content "$ENV:ChocolateyInstall\config\chocolatey.config"

Simply uninstall and re-install please.

**Comment by bcurran3** [comment]
p.s. New pre-release today you can test out (not related to this problem)

choco install choco-cleaner --pre

**Comment by brian6932** [comment]
Yea this issue for me was solved, I just forgot to close this, my bad
