### ISSUE TITLE
please update the 6.11.0 old version download url 

### ISSUE THREAD

**Issue by gad3r** [bcurran3/ChocolateyPackages_CCR#324]
Please please update: 
https://community.chocolatey.org/packages/vnc-connect/6.11.0
i need install this version 6.11.0 in many pc's 

Please change the download URL from: https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.11.0-Windows-msi.zip to https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.11.0-Windows-msi.zip in tools\chocolateyinstall.ps1

¡Thanks!

**Comment by bcurran3** [comment]
Done.

choco install vnc-connect --version=6.11.0.20230422

**Comment by gad3r** [comment]
¡¡ thank you very very much !!

**Comment by bcurran3** [comment]
YW. Yeah, I downgraded too.
![image](https://user-images.githubusercontent.com/14026600/235291826-3661f09e-013c-43da-ba3f-dd7f3c7aa90f.png)
