### ISSUE TITLE
Use ISO 8601 date in revision string

### ISSUE THREAD

**Issue by drdcd** [bcurran3/ChocolateyPackages_CCR#326]
... in order to disambiguate "Choco-Cleaner.ps1 v0.0.9.0 (05/03/2023)".

There is, after all, a good reason why ISO made that choice.

**Comment by bcurran3** [comment]
Hey! Not disambiguous as long as you know I'm American and we... um, ignore international standards of units and measurements. :-)

With that said... I do version some of my other packages using ISO 8601 date format. So it does seem reasonable to keep to that standard across all scripts.

Consider it done in v1.0 (please feel free to try the pre-release and provide feedback).

EDIT: Now:
`Write-Host "Choco-Cleaner.ps1 v1.0-pre4 (2023-05-07) - deletes unnecessary residual Chocolatey files to free up disk space" -Foreground White`
