### ISSUE TITLE
chocolatey-fastanswers.extension - Get-IsWin8 needs minor version qualifier

### ISSUE THREAD

**Issue by brogers5** [bcurran3/ChocolateyPackages_CCR#331]
`Get-IsWin8`'s implementation only checks against the Windows NT kernel's major version (6), which is also shared with Windows Vista and 7. This causes a false positive:

![False Positive screenshot](https://github.com/bcurran3/ChocolateyPackages/assets/6869577/a6ac2a7c-fb00-415c-ab3c-9e60f922f18d)

The minor version should be 2 for Windows 8, and 3 for Windows 8.1.

**Comment by bcurran3** [comment]
Thanks. It's nice to see someone actually using this!

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
