### ISSUE TITLE
chocolatey-fastanswers.extension - Get-IsWin7's minor version comparison is incorrect

### ISSUE THREAD

**Issue by brogers5** [bcurran3/ChocolateyPackages_CCR#332]
`Get-IsWin7`'s minor version comparison uses a less-than check against Windows 7's actual minor version (1). This should be an equivalency check instead.

This would cause a false positive in Windows Vista, and a false negative in Windows 7:
![image](https://github.com/bcurran3/ChocolateyPackages/assets/6869577/a2c1cd9c-e346-4a88-a673-405e801e8e03)

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
