### ISSUE TITLE
choco-optimize-at not installing anymore.

### ISSUE THREAD

**Issue by NekoJonez** [bcurran3/ChocolateyPackages_CCR#333]
Chocolatey license file NOT found. You need to be a Chocolatey Pro or Business customer to use this package. See https://chocolatey.org/pricing for more information.
ERROR: ScriptHalted
The install of choco-optimize-at was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\choco-optimize-at\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - choco-optimize-at (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\choco-optimize-at\tools\ChocolateyInstall.ps1'.
 See log for details.

-> Is this not a free package anymore?
Running Chocolatey v2.0.0-beta-20230426 and Powershell 7

**Comment by bcurran3** [comment]
The package hasn't changed in 5 years. Chocolatey has.

Do you have "$env:ChocolateyInstall\license\chocolatey.license.xml"? Maybe Chocolatey v2 doesn't use this anymore?

**Comment by NekoJonez** [comment]
I feel like Choco v2.0 doesn't use that anymore.
It that's the check for Choco installed or not... I usually do that differently. 

![image](https://github.com/bcurran3/ChocolateyPackages/assets/4569581/5de5e17f-05fe-4d0c-8db2-74701d03eace)

**Comment by bcurran3** [comment]
chocolatey.license.xml is (was?) the file that determines your Chocolatey paid license.
If it's no longer used in v2, I just need to know how Chocolatey assigns/determines licenses in current versions. I don't have a license. If you can provide a link or some information I'll be happy to update the package.

**Comment by NekoJonez** [comment]
The question is, do we need that license file? Why is that file needed in the package?

**Comment by bcurran3** [comment]
Again I know nothing about how the license check works for Chocolatey v2, if or when it may have changed. If you can go over the steps of how you installed your license or point me to the docs for the current process then I can modify as necessary.
