### ISSUE TITLE
hikvision imvs 4200

### ISSUE THREAD

**Issue by weedy** [bcurran3/ChocolateyPackages_CCR#339]
I saw you made a package for sadp.
Could you make one for ivms 4200?

Thanks

**Comment by bcurran3** [comment]
Switched to Unifi a few years ago…

 

If you want, I can create a starter package for you and teach you how to update it. Don’t expect it soon, but could look into it in the future.

 

 

 

From: weedy ***@***.***> 
Sent: Wednesday, July 19, 2023 12:10 PM
To: bcurran3/ChocolateyPackages ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bcurran3/ChocolateyPackages] hikvision imvs 4200 (Issue #339)

 

I saw you made a package for sadp.
Could you make one for ivms 4200?

Thanks

**Comment by bcurran3** [comment]
p.s. You should supply some links for me so I don't have to hunt down the software.

**Comment by bcurran3** [comment]
No response. 

I have no interest in making or maintaining a package for this. 

Closing.
