### ISSUE TITLE
Open for Netgear ProSAFE Plus Utility?

### ISSUE THREAD

**Issue by cfoellmann** [bcurran3/ChocolateyPackages_CCR#34]
Would be open to `Netgear ProSAFE Plus Utility` (prosafe-plus-utility)?

**Comment by bcurran3** [comment]
Do you mean this:
https://www.netgear.com/support/product/ProSafe%20Plus%20Utility 
?
I could look into it.

**Comment by cfoellmann** [comment]
Yes. I have never used autokey so it might be hard for me to config this but I will look into sending you a PR.

**Comment by bcurran3** [comment]
AHK can sometimes be easy and sometimes be a big PITA.

I'll look into it soon as I have time.

**Comment by bcurran3** [comment]
Just a quick update. I did download and look at it. No silent install as expected. Will need to use AutoHotKey. So still on radar, but the AHK means it will take me hours of creation and testing. It's a PITA. So when I have spare time. :(

**Comment by cfoellmann** [comment]
no problem. take your time.
No way to know how many people would use this package. So just put it on the list for when you are bored 😁

**Comment by bcurran3** [comment]
Surprise!

https://chocolatey.org/packages/prosafe-plus-utility/2.7.2

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***

**Comment by bcurran3** [comment]
p.s. I still need to finalize the AHK script. It's almost there. Will do soon.

**Comment by bcurran3** [comment]
Not so much as a "Thank you?"
