### ISSUE TITLE
Regen Config File

### ISSUE THREAD

**Issue by DeadlyDad** [bcurran3/ChocolateyPackages_CCR#343]
One handy feature would be the ability to list {Title}: {Details} for each discovered package in the original config file, allow users to uncheck each one that they don't want, backup the old config file, then output a _new_ config file with only the selected packages.  (Useful if you have installed **WAY** more packages than you want for a fresh install of Windows.)

**Comment by bcurran3** [comment]
Are you talking about choco-package-list-backup? or?

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
