### ISSUE TITLE
intel-arc-graphics-driver 31.0.101.4577 correction

### ISSUE THREAD

**Issue by thedarave** [bcurran3/ChocolateyPackages_CCR#345]
31.0.101.4577 -- Download attempt comes back with 403: Forbidden.

Correction to make it work:
tools\ChocolateyInstall.ps1 --

IntelPackageNumber = '785925'
url64 = "[https://downloadmirror.inte...](https://disq.us/url?url=https%3A%2F%2Fdownloadmirror.intel.com%2F%24IntelPackageNumber%2Fgfx_win_%3AsyEVPMklyOWauDYvxfm64QwvA-M&cuid=2163236)"+"$TodaysVersion"+".exe"

No change in SHA256.

**Comment by bcurran3** [comment]
This has been superseded by v31.0.101.4644 on 08/24/23, it may still be in moderation.
