### ISSUE TITLE
[HFSExplorer] depending on a version of Java that is now paid for most people

### ISSUE THREAD

**Issue by zippydan** [bcurran3/ChocolateyPackages_CCR#346]
This seems to be an old package, and is therefore based on old wisdom, i.e. that Oracle's JRE is best.

However, Oracle JRE has long since moved to a paid subscription for commercial use. Is that really the best option for automatically installing dependencies? I myself have moved to the Microsoft OpenJDK, and this program seemed to launch just fine with only that installed.

I actually found it quite annoying that this automatically installed Oracle JRE on my machine and I then had to manually remove it afterwards.

The best option imo would be to have install switch for selecting your preferred JRE (Oracle, Microsoft, AdoptOpenJDK, Libericaetc.) or to not install any JRE at all.

If that is too much work, I'd default to Microsoft's OpenJDK as a dependency over Oracle's, or just drop the dependencies altogether and inform the user that they'll need to install a JRE to get this program working.

**Comment by bcurran3** [comment]
Hi Dan,

PREFACE: You're downloading and installing a package from the FOSS Chocolatey Community Repository; i.e. it's not recommended for business use. You can read the official diatribe on chocolatey.org.

With that said, Oracle JRE is completely free for non-commercial use AFAIK and, AFAIK still the single most popular JRE. (TBH, it's been awhile.) Our conversation really shouldn't be happening. :-)

This is a discussion that I've had a couple times in this repo's issues. (Search for "java" in the closed section and you'll see my disagreements/arguments there.) SUMMARY: I'm dammed no matter what I choose if I choose one particular JRE as there will always be someone who has a different preference.

![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/0f3f216b-9372-4f98-9d50-fd1584682d74)


Now it may seem that I'm in disagreement with you, but I've already decided that the Java world is too splintered now and any future Java dependent packages will just have a warning/disclaimer that Java is necessary and to pick your own preferred variant. Basically, I'm behind you/agree with you on your last sentence/proposal.

Feel free to watch my packages and make sure I stick to this and don't forget! For the record - I have no plans to update old Java dependent packages to remove the dependency.

**Comment by zippydan** [comment]
I don't mean to reopen this issue but rather to provide a RTFM solution in case anyone else has the same or similar problem.

Installing **HFSExplorer** - _or any package_ - with the `--ignore-dependencies` switch will make **chocolatey** skip over the installation of any prescribed dependencies (just like it says on the tin).

So, 

`choco install HFSExplorer --ignore-dependencies` or
`choco install --ignore-dependencies HFSExplorer`  

Find all this and more with `choco install -h` 
(or https://docs.chocolatey.org/en-us/choco/commands/install)

More discussion:

https://stackoverflow.com/questions/45187854/manage-chocolatey-package-dependencies

**Comment by bcurran3** [comment]
Good info to know. Thanks for following up!
(You might want to mention the choco version you're using as reference as well.)

**Comment by zippydan** [comment]
Choco Version 2.2.2

And I removed the bit about the switch coming before or after the package name.  I realized I made an insidious typo.
