### ISSUE TITLE
Tux paint stamps failing to install

### ISSUE THREAD

**Issue by mavhc** [bcurran3/ChocolateyPackages_CCR#348]
The file is named tuxpaint-stamps-2023-05-19-windows-installer.exe but the code to run it assumes it's tuxpaint-stamps-2023-5-19-windows-installer.exe with the missing leading 0

**Comment by bcurran3** [comment]
Yeah, the new Chocolaty v2 version standardization bites me again.
I'll update it sometime in the future (while hoping for a new version that forces me to do it)

**Comment by bcurran3** [comment]
Just pushed an udpate that fixes the problem:
https://community.chocolatey.org/packages/tux-paint-stamps/2023.5.19.20231025
