### ISSUE TITLE
(choco-upgrade-all-at) Shift default scheduled time away from the top of the hour

### ISSUE THREAD

**Issue by Windos** [bcurran3/ChocolateyPackages_CCR#349]
The Chocolatey Community Repository gets a lot of traffic at the top of the hour, every hour throughout the day, due to scheduled automatic updates.

To help spread out that load, it would be great if this package's default start time was either shifted by 15 to 30 minutes, or otherwise randomized.

To avoid confusion, current installs shouldn't change when upgrading this package.

**Comment by bcurran3** [comment]
@Windos 

I'll try to randomize upgrade kick off time by 15 minute intervals in a future update; i.e. default to running at xx:00, xx:15, xx:30, or xx:45. 

FYI: Over time I expect a large percentage of users will migrate to using my new  [choco-continuous-upgrader](https://community.chocolatey.org/packages/choco-continuous-upgrader) / https://github.com/bcurran3/ChocolateyPackages/issues/243 which will also spread the load out.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
