### ISSUE TITLE
[request] Please update resilio-sync-home package

### ISSUE THREAD

**Issue by fxjkhr** [bcurran3/ChocolateyPackages_CCR#35]
Hi! Installation of resilio-sync-home package is throwing a checksum error.  Please update the package per https://github.com/bcurran3/ChocolateyPackages/blob/master/resilio-sync-home/readme.md :)

**Comment by bcurran3** [comment]
Its funny 'cause I just checked it a few days ago...

About to push the new version now.

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***

https://chocolatey.org/packages/resilio-sync-home/2.6.0.1317
