### ISSUE TITLE
[Enhancement] Icon for CNC

### ISSUE THREAD

**Issue by asheroto** [bcurran3/ChocolateyPackages_CCR#352]
[CNC](https://community.chocolatey.org/packages/choco-nuspec-checker) is naked! Ha. Cosmetic comment here...

Noticed it doesn't have an icon... I know... I know... trivial. but could give it some personality.

In searching 'Check' on [IconFinder](https://iconfinder.com) I found some good looking checks...
https://www.iconfinder.com/search?q=check&price=free&license=gte__2

![image](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/26bf31ba-7312-47d8-869b-5347c1a480ca)

One cool thing about [Icons8](https://icons8.com) (different from IconFinder) is that on many of icons you can actually change the color before you download the icon. So when checking the Chocolatey background blue...

https://icons8.com/icons/set/check
![image](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/cea50ddf-7961-4aaa-985f-f7576c006854)

Or [this icon](https://icons8.com/icon/VFaz7MkjAiu0/done) with both the background and foreground colors! Note that on some icons you have to set multiple colors which is what I'm clicking through...

https://github.com/bcurran3/ChocolateyPackages/assets/49938263/aabfad28-d009-43f5-9c04-5958c36c4d56

SVG...

![cnc](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/01e2bd3a-bbab-43c7-8523-2d8efa8efde0)

PNG...
![cnc](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/34da259b-bbc0-4bf1-8bd7-d41f7ea631e0)

Won't hurt my feelings if you decide against the idea but just thought it would be a good addition! One of the icons might give it some spunk.

---

Side note, if you don't use [PowerToys](https://community.chocolatey.org/packages/powertoys) you're missing out! One of the features it has is the color picker tool...
![image](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/65a1f1fd-a18a-4c03-abf9-cbe17cda1448)

This demo is from their [repo](https://github.com/microsoft/PowerToys)...
![PowerToys Settings Dashboard WIP](https://github.com/microsoft/PowerToys/assets/26118718/938a5715-0a9b-4fe9-9e15-adfec92da694)

**Comment by bcurran3** [comment]
It's naked, but not supposed to be. It has an assigned icon but the CDN link is broken. 

The icon is supposed to show my inside joke funny icon for Chocolatey utils:

![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/3328e869-6acd-463e-9ce0-31c995b0bdb4)

A year or two or three ago @teknowledgist volunteered an icon for one of my packages and I then convinced him to make a few more. This is now my icon template:

![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/0785588a-fb88-447b-8206-46c479320c81)

I'm not against a new icon. I think it's a good idea to change it to my new house style. Maybe you want to put the checking inside the template for me?

Thinking a little more about this, I like the idea of the word ".nuspec" in Chocolatey brown with the checkmark through it. I think that would look cool!

Or maybe better to have the word ".nuspec" in [nuget blue](https://raw.githubusercontent.com/NuGet/Home/dev/meta/resources/nuget.png) with the Chocolatey brown for the check mark. 

I'm as artistically inclined as an upside down turtle. I can't draw a straight line for a stick figure. I'm hoping you're artistic as enthusiastic and can put this together. :-)

**Comment by teknowledgist** [comment]
Here is my 10-minute attempt:  https://cdn.jsdelivr.net/gh/teknowledgist/Chocolatey-packages@1135f92b543a01320ddaacb9e444e7798c9eb0e4/Icons/CNC_icon.png

**Comment by bcurran3** [comment]
@teknowledgist , hahahha, you're still awesome.

Ideally though it shouldn't have the nuget logo or word, just the color as a nod to it. I'm thinking .nuspec in nuget blue with a chocolatey brown checkmark superimposed and center over it.

**Comment by asheroto** [comment]
I have an idea for the design.

Do either of you have the full resolution PNG, or preferably SVG?

SVG is preferred because it's a vector format, but PNG can work and I can convert it, but need a high resolution version.

**Comment by teknowledgist** [comment]
I dunno.  I'm certainly no artist, but I made a revision:

![CNC_icon2](https://github.com/bcurran3/ChocolateyPackages/assets/3977744/6c12c0a7-a13b-4d04-bd7c-a101eb3fafac)

**Comment by bcurran3** [comment]
You're more of an artist than me. I dig it!

I would consider moving ".nuspec" lower to see how it looked. I'm sure you already took that into consideration. I would think centered in the blue space would be best but maybe the check would interfere too much? IDK.  I do know I like the overall design now; tweaked more or not.

**Comment by asheroto** [comment]
I think you will have a difficult time seeing the ".nuspec" or any text with icons. With icons usually 1 or 2 characters are okay but anything more cannot be easily read.

I grabbed the official Chocolatey logo and modified it. Thoughts?

Without check:
![cnc](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/d0c65fff-124e-4f64-bde1-ecbb473f4ae7)

With check:
![cnc-with-check](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/fbb68dc4-3690-4cc1-a8cd-4d29c7f0ff64)

Photoshop PSD file:
[cnc.zip](https://github.com/bcurran3/ChocolateyPackages/files/13370380/cnc.zip)

**Comment by asheroto** [comment]
I do like that chocolatey bar being big as you have it though @teknowledgist ... hmm..

**Comment by bcurran3** [comment]
I do like it. And I do appreciate the effort. But I do have a pattern:

![choco-cleaner-rt_icon](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/ec3eaf37-e7f9-4b6a-a4a4-31bb995fb8dd)
![chocolateypowershell_icon](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/c6c4ff8b-974e-4363-81bd-5a7fb9717153)

![choco-sandbox_icon](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/e0544e69-c76c-49fc-9c6a-517058d98ce5)
<img width="63" alt="choco-toast-notifications hook_icon" src="https://github.com/bcurran3/ChocolateyPackages/assets/14026600/72523e07-8ed0-4395-a3ac-743a11d0cbc0">

![mychocohooks_icon](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/5b509c8a-4b20-40b5-b070-1259d6a396f9)

(Yeah I shouldn't have downsized those last two)

**Comment by asheroto** [comment]
No worries.

I like the 1st blue PowerShell one, but the brush makes more sense.

**Comment by bcurran3** [comment]
All of these icons are already in use by my packages.
The brush is a broom and from Choco-Cleaner and the Choco-Cleaner-RT series of hooks. :-)

You might never have seen them because cdn.staticaly.com sucks balls!

**Comment by asheroto** [comment]
Oh I see what you mean. You meant pattern like pattern of icons, rather than design pattern. 🤣

Maybe we could just replace the icon then with a check? Similar to this? Could find a good looking check from the sites I mentioned in my op?

![cnc2-check](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/c504f8a9-4d4d-4539-b9c9-9e6cbbb28bb5)

**Comment by bcurran3** [comment]
Since it's choco-**nuspec**-checker, I'd like "nuspec" (or some representation of it) to be under the checkmark.

**Comment by asheroto** [comment]
I'll do that, but I don't think you'll be able to see it when it's on the exe because the text will be too small. lol.

I guess at least it will look good on the Chocolatey website? 😊

one sec I'll publish

**Comment by asheroto** [comment]
Here are four different versions and the Photoshop file, 512x512 px, 72 dpi, transparent background (which Choco supports). I like the second one personally.

![cnc2-v1](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/152833ca-1975-4087-8d6f-9a1529c9a04a)

![cnc2-v2](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/9868f0f5-5c65-4a89-94d1-b50a9ded6845)

![cnc2-v3](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/76c7e647-8bf9-499b-b659-b4f8b43d3d64)

![cnc2-v4](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/585558aa-f7e3-4bca-97d0-45f851070b4c)

![299110_check_sign_icon](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/1eca6b44-7291-4f15-9813-8b2b2e57bc0f)

[cnc2.zip](https://github.com/bcurran3/ChocolateyPackages/files/13372706/cnc2.zip)

**Comment by teknowledgist** [comment]
One last entry in this silly discussion (from me).  As requested, this one has:

* NuGet blue lettering
* Chocolatey brown check
* ".nuspec"
* text is actually readable in icon form

![CNC_icon3](https://github.com/bcurran3/ChocolateyPackages/assets/3977744/038cd0a9-1d3a-4e7a-8432-fd5a3331713f)

Now, where did I put that bourbon?

**Comment by bcurran3** [comment]
@teknowledgist - Pass the Booker's!
@asheroto - looks great! Thank you. I think I'm going to go with the last one by @teknowledgist though. (Sorry!)

**Comment by bcurran3** [comment]
OFF SUBJECT / ON SUBJECT:

As you know I'm working Chocolatey Continuous Updater (https://github.com/bcurran3/ChocolateyPackages/issues/243)
https://github.com/bcurran3/ChocolateyPackages/tree/master/choco-continuous-upgrader

I've sent you both requests to test it out and give feedback, you can do it in e-mail or at the issue (https://github.com/bcurran3/ChocolateyPackages/issues/243)....

I STARTED this icon for it last week...
<img width="255" alt="choco-continuous-upgrader_icon" src="https://github.com/bcurran3/ChocolateyPackages/assets/14026600/8d0c6613-c00c-4be4-8fc8-abc79530c2a4">

...but didn't finish it. My idea was an infinity symbol and an up arrow to represent upgrades. Yeah, not really obvious... I like the infinity symbol but not sure how to really represent "choco ugprade all" - if you've got suggestions, I'm all eyes.

**Comment by asheroto** [comment]
> @teknowledgist - Pass the Booker's! @asheroto - looks great! Thank you. I think I'm going to go with the last one by @teknowledgist though. (Sorry!)

That works!

> I've sent you both requests to test it out and give feedback, you can do it in e-mail or at the issue (#243)....

You you please add me as an assignee on that issue? Is that where we are discussing it?

**Comment by bcurran3** [comment]
Um, honestly I was just expecting some useability feedback via e-mail on choco-continuous-upgrades. I don't want any external code changes as 1> I'm not expecting it 2> it's in flux locally 3> I suck at GH project management. If you want to play with/make changes to the code just give me a heads up/warning... and I'll be glad to let you better it.

**Comment by teknowledgist** [comment]
I haven't tested the actual package yet, sorry, but I made this:
![CCU_icon](https://github.com/bcurran3/ChocolateyPackages/assets/3977744/789c0d59-2718-49ef-9ba4-fe7d6b08b7d3)

**Comment by bcurran3** [comment]
![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/00ee8a1e-30de-4f49-9d5a-0f7a230a59c3)

**Comment by bcurran3** [comment]
@teknowledgist 

Next time you're in L.A. come visit me for:

![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/a14cb6e9-2a66-4946-a4a2-e72f3e6057be)

If I'm feeling especially generous...

![image](https://github.com/bcurran3/ChocolateyPackages/assets/14026600/ba0cb5c3-e392-420c-8940-0bacd4ed2014)

**Comment by asheroto** [comment]
> I haven't tested the actual package yet, sorry, but I made this: ![CCU_icon](https://user-images.githubusercontent.com/3977744/283908163-789c0d59-2718-49ef-9ba4-fe7d6b08b7d3.png)

nice!
