### ISSUE TITLE
CNC - invalid Markdown heading syntax found - when using a # inside of a hyperlink

### ISSUE THREAD

**Issue by asheroto** [bcurran3/ChocolateyPackages_CCR#355]
If you run CNC against a nuspec file that has a hyperlink in the description with a `#` character such as

```
please refer to [issue #16](https://github.com/coreybutler/nvm-windows/issues/16).
```

Then it will say

```
WARNING:   ** <description> - invalid Markdown heading syntax found. This will trigger a message from the verifier
```

For example, the end of this line will cause CNC to produce the message below
https://github.com/asheroto/ChocolateyPackages/blob/7dbbebc7cdb89a4b28ea811827101c5d2b97b276/nvm.install/nvm.install.nuspec#L48

![image](https://github.com/bcurran3/ChocolateyPackages/assets/49938263/eb26ae34-52d2-42c5-a6fb-c121d6e6f1d0)

But if you remove the `#` character then it works. I think CNC thinks it's a heading and does not detect the `#` character is text for a hypeerlink. 😊

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)

**Comment by asheroto** [comment]
Well wait! what if somebody else takes over the repo?

**Comment by bcurran3** [comment]
No one can take over it, anyone can fork it. Chocolatey Team members already have. I'm sure they will deal out the package maintainership to anyone who's interested, probably in the Google Groups.
