### ISSUE TITLE
[Feature Request] CNC - Open Package URL

### ISSUE THREAD

**Issue by asheroto** [bcurran3/ChocolateyPackages_CCR#356]
It would be handy if CNC would be able to open the URL for a package on the community repository.

For example, while in this folder...

```powershell
C:\Projects\ChocolateyPackages\intel-rst-driver
```

Typing this...

```powershell
cnc -OpenPackageUrl
```

Would open this:
https://community.chocolatey.org/packages/intel-rst-driver

There could also be a `-version` tag such as

```powershell
cnc -OpenPackageUrl -Version 1.2.3
```

**Comment by bcurran3** [comment]
Hey @asheroto  buddy, just seeing this.

Good idea.

Here's what I currently use. You might find it useful, add to your PS profile script:

```
function cweb {param ([string]$package ) 
if (($package -eq '') -or ($package -eq '.')) {$package=(Split-Path -Leaf $(Get-Location).Path)}
start https://community.chocolatey.org/packages/$package
}
```
You might find this useful too, modify for your repo:
```
function gweb {param ([string]$package ) 
if (($package -eq '') -or ($package -eq '.')) {$package=(Split-Path -Leaf $(Get-Location).Path)}
start https://github.com/bcurran3/ChocolateyPackages/tree/master/$package
}
```
---------------------------
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
