### ISSUE TITLE
[intel-dsa] wrong checksum in chocolateyinstall.ps1

### ISSUE THREAD

**Issue by carlottostromstedt** [bcurran3/ChocolateyPackages_CCR#357]
In the chocolateyinstall.ps1 the checksum for the binary is set to 2F7F1A48DF71CB0672AB5D77B38874E473156E11AD3E92292C14A342BCD5EDD5 but the actual checksum is `62aff28065a0a558dd55050940d164cf6eff58d895d5d5b43f8a1e9937ec1691`

This generates an error on installation.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
