### ISSUE TITLE
Weird result with choco-cleaner V 1.1.1 from chocolatey repo

### ISSUE THREAD

**Issue by jmckean52** [bcurran3/ChocolateyPackages_CCR#359]
Just DLed the choco-cleaner v 1.1.1 package from Chocolatey and had prob installing - which was surprised me since I had installed a couple of months ago.  When I unzipped the nupkg and looked at chocolateyinstall.ps1, it is different from the one in your repo and different from the one shown in the "Files" section of the Choco page.  It is about 3000 lines long and seems to have about 4 iterations of the actual cleaner script.  I grabbed the install file from your report and recompiled. Everything worked fine. I suspect either my unarchiving technique or some corruption of the choco repo. But I repeated it this AM and its the same. Thought you might like to check it out.

**Comment by bcurran3** [comment]
I'm guessing some sort of CDN file corruption. (Best guess, no real clue.)

You should check the checksum of the download nupkg file.

<img width="525" alt="image" src="https://github.com/bcurran3/ChocolateyPackages/assets/14026600/1d87aef3-2e1f-463b-a367-a9c407b06d6c">

PS C:\Users\bcurran\downloads> cs .\choco-cleaner.1.1.1.nupkg
B6E8A5879B258D0CD5BE2622268E74988FE62B60213457F63C66B03722A9720E
^^ SHA256 checksum

The one I just downloaded from chocolatey.org matches my local one that I uploaded there back in June 2023.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)

**Comment by jmckean52** [comment]
Thanks for the great work.


--

Jim McKean
[cid:aea6b6f7-b96b-4bdb-81a9-9b9b179a2d66]
[cid:67d592a6-8b9f-42a2-9d34-f771d6dbe078][cid:4380a205-6779-44f3-a7c1-7662be20d6f2][cid:38717ca7-f0be-4ef7-a645-7ed8debac299][cid:1d0dfb42-5d45-474b-b4b8-2f0e4206227f][cid:b0e2f0c8-f4d0-4a6f-bf91-000527a2ab89]

  Operations Design
  Principal Consultant
  812-327-5534<http://voice.google.com/calls?a=nc,%2B18123275534>


________________________________
