### ISSUE TITLE
Request maintainer access to Dokany package

### ISSUE THREAD

**Issue by Liryna** [bcurran3/ChocolateyPackages_CCR#360]
Hi @bcurran3 ,

Thank you for maintaining so many choco packages!
I am the maintainer of [Dokany](https://github.com/dokan-dev/dokany) project.
I am happy to take over the [Dokany](https://community.chocolatey.org/packages/dokany) package. We have our package scripts already [here](https://github.com/dokan-dev/dokany/tree/master/chocolatey) but it is publishing to [dokany2](https://community.chocolatey.org/packages/dokany2).
Do mind making [dokan-dev](https://community.chocolatey.org/profiles/dokan-dev) a maintainer of the original (your) dokany package ?

**Comment by bcurran3** [comment]
Hi @Liryna,

Long time no talk! You're welcome.

Sorry but I no longer have any control over it. You'll have to contact a Chocolatey moderator. They have a GH issues page with package requests, that would probably be a good place say you're willing to do it. [It's here](https://github.com/chocolatey-community/chocolatey-package-requests)
