### ISSUE TITLE
CNC moved to asheroto's repo

### ISSUE THREAD

**Issue by asheroto** [bcurran3/ChocolateyPackages_CCR#361]
Hey Bill,

Since you are no longer working on Chocolatey projects, I wanted to give you a heads-up that I cloned the CNC project over to my repo:
https://github.com/asheroto/choco-nuspec-checker

The main reasons for this:
1. Since you aren't active, I wanted to provide an area where the project could be actively developed.
2. I fixed an issue with `-Update` where it would not save `.nuspec` files w/o BOM and kept giving the same suggestion to run `-Update`.
3. I fixed some extra whitespaces and other minor issues.
4. I formatted the file.

I did let the current package maintainer know about these changes. Requested to be added as an additional maintainer.

https://community.chocolatey.org/packages/choco-nuspec-checker/

Of course, your copyright is still there giving you credit. 😊

**Comment by bcurran3** [comment]
You have my blessing of course!
