### ISSUE TITLE
[request] Please update backupper-standard

### ISSUE THREAD

**Issue by Caleb9** [bcurran3/ChocolateyPackages_CCR#38]
Currently the newest version is 4.5.1 while the choco package is 4.1.0, so the checksums don't match.

**Comment by bcurran3** [comment]
Sure thing. Thanks for letting me know.

**Comment by bcurran3** [comment]
Funny, the website https://www.aomeitech.com/ab/standard.html shows 4.1. I downloaded the file and the details do display 4.5.1.0

**Comment by bcurran3** [comment]
Done!
https://chocolatey.org/packages/backupper-standard/4.5.1.0

***
**Click here to become a [Patron](https://www.patreon.com/bcurran3).**
***
