### ISSUE TITLE
choco-upgrade-all-at & choco-upgrade-all-at-startup: add logs

### ISSUE THREAD

**Issue by nagromc** [bcurran3/ChocolateyPackages_CCR#41]
I've just discovered these packages, and this is an awesome idea.

It would be great to have some logs to check what packages have been upgraded recently (or to know if a package have problems to upgrade). Just the `choco upgrade all` output should be enough.

**Comment by bcurran3** [comment]
Thanks.

These packages just create the scheduled tasks to run choco upgrade all. Chocolatey already creates logs of these actions. You can find them in C:\ProgramData\chocolatey\logs

I'm going to close this. If I missed the point or you want something different logged, let me know.
