### ISSUE TITLE
[request] Please update backupper-standard to 4.5.2

### ISSUE THREAD

**Issue by Caleb9** [bcurran3/ChocolateyPackages_CCR#42]
Currently the newest version is 4.5.2 while the choco package is 4.5.1, so the checksums don't match. Thanks in advance :).

**Comment by bcurran3** [comment]
Sure thing.

Done.

choco install backupper-standard --version 4.5.2.0

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***
