### ISSUE TITLE
Visual BCD URL

### ISSUE THREAD

**Issue by kain** [bcurran3/ChocolateyPackages_CCR#43]
Hello!

Visual BCD developer changed download URL for MSI package or maybe there is a typo. Please update chocolateyinstall.ps1:
```
- $url = 'https://www.boyans.net/VisualBcd5/VisualBcd_0.9.3.1.msi'
+ $url = 'https://www.boyans.net/VisualBcd4/VisualBcd_0.9.3.1.msi'
```

**Comment by bcurran3** [comment]
Thanks.

Actually https://www.boyans.net/VisualBcd4/VisualBcd_0.9.3.1.msi doesn't work either. Works directly from the site but not elsewhere. I'm guessing it needs  a referral link. I'll look into it.

**Comment by bcurran3** [comment]
Duh! I already had the referral info when I looked. I guess the URL changed.

Done!

choco install visualbcd --version 0.9.3.1020181009

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***
