### ISSUE TITLE
(intel-xtu) Failing Checksum

### ISSUE THREAD

**Issue by ajpotato214** [bcurran3/ChocolateyPackages_CCR#45]
The latest XTUSetup.exe from https://downloadmirror.intel.com/24075/eng/ is failing sha256 checksum when installing via Chocolately.

"Error - hashes do not match."

**Comment by bcurran3** [comment]
Thanks for letting me know. I just pushed the new version.

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***
