### ISSUE TITLE
[choco-cleaner & choco-package-list-backup] set execution time by packageParameters

### ISSUE THREAD

**Issue by DJCrashdummy** [bcurran3/ChocolateyPackages_CCR#46]
it would be a nice feature to set the execution time also for `choco-cleaner` and `choco-package-list-backup` like you can for `choco-upgrade-all-at` via `packageParameters=` resp. `--params=`.

so you can create a `packages.config`-file once with all the times in it and don't have to rework the tasks every time after installing.

**Comment by bcurran3** [comment]
I understand the first part. I'll add it to a future release.

> so you can create a packages.config-file once with all the times in it 

I don't understand why you would want times inside a packages.config file.

**Comment by DJCrashdummy** [comment]
> I'll add it to a future release.

thank you very much for considering this!

> I don't understand why you would want times inside a packages.config file.

i'm setting up windows machines every now and then, so i like [the capability to install all software i need in nearly one swoop](https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfig) (like i do it on linux). and with the possibility to "pre-configure" the execution-times by `packageParameters=` in the `packages.config` i don't have to rework them every time after executing `choco install -y C:\Users\USERNAME\packages.config`.

**Comment by soredake** [comment]
Any progress on this?

**Comment by bcurran3** [comment]
Not yet. Eventually. Low priority as it's easy for someone to run Task Scheduler to manually change it to their preferred time. (Thinking on a one machine basis.)

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
