### ISSUE TITLE
automatically end execution of tasks

### ISSUE THREAD

**Issue by DJCrashdummy** [bcurran3/ChocolateyPackages_CCR#47]
why is for all tasks created by your scripts the setting activated to _"end the task, if its execution takes longer than **3 days**"_?
wouldn't it make more sense to set it to something like **2 hours**?

**Comment by bcurran3** [comment]
If you're referring to the packages below, you read something very wrong.

https://chocolatey.org/packages/choco-persistent-packages

> A NOTE ON DEFAULTS:
> If you don't specify any parameters, choco-persistent-packages defaults to running daily at midnight and aborting at 1 AM. (My preference!)
> Not specifying a TIME will always default to midnight. Not specifying an ABORTTIME will always default to 1 AM. If you're setting a TIME, be sure to also set the ABORTTIME.

https://chocolatey.org/packages/choco-upgrade-all-at

> A NOTE ON DEFAULTS:
> If you don't specify any parameters, choco-upgrade-all-at defaults to running daily at 2AM and aborting at 4 AM. (My preference!)
> Not specifying a TIME will always default to 2 AM. Not specifying an ABORTTIME will always default to 4 AM. If you're setting a TIME, be sure to also set the ABORTTIME.

**Comment by bcurran3** [comment]
I think I figured out what you are talking about:

![image](https://user-images.githubusercontent.com/14026600/47608289-f79d0f80-d9df-11e8-8049-4bfdc6a8f078.png)

What you see above are Window's DEFAULTS for tasks. There's no need to change the defaults for minor tasks. If you experience/d some sort of problem related to these defaults, re-open the issue and we can discuss it more.

**Comment by DJCrashdummy** [comment]
i already thought it is some kind of defaults or something.
no, i'm not experiencing any problem. i was just thinking about the settings for the tasks... but why not using a more reasonable setting?

**Comment by bcurran3** [comment]
"Reasonable" is a very subjective word.

What settings do you believe are unreasonable and what do you think those settings should be set at?

**Comment by DJCrashdummy** [comment]
you are right, but at the latest in the case a task is executed daily, the option *"Stop the task if it runs longer than:"* set to *"**3 days**"* is completely senseless, even it is the system default. - i would either set it to something much more reasonable like *"**2 hours**"* (like you did it with some of your abort-tasks) or deactivate it completely (if it isn't needed resp. useless).

these are just my thoughts, but i'm not a windows-expert (any more since ~15 years).

**Comment by bcurran3** [comment]
I'm not sure of Microsoft's decision to set the default to 3 days but I believe it's a very long standing default decision. I tend to agree with you that 3 days sounds ridiculous when I think in the scope of my Chocolatey utility tasks. 

I decided to do a quick check to see how often tasks deviate from the "norm" (default). Looking through my tasks created by Adobe, Dropbox, Google, Intuit, Microsoft, Nvidia, Opera, and Zoolz, all are set to the default 3 day task run with the exception of Microsoft's OneDrive which is set to one day. (This doesn't include the 100 or so tasks for the various Windows default programs which include a mishmash of default times for 10 minutes to 4 days.)

This sounds like a cop out but it seems to me if default is good enough for those big players, then the default should be good enough for little old me and little old me's tasks as well. :-) 

Now let me point out the key reasoning behind my accompanying abort tasks in some packages. Those packages set tasks to upgrade packages and, though Chocolatey is a great package manager, not all programs in packages behave well. The best example is programs that open up some sort of sales pitch in the default browser after install or uninstall. When this happens from a scheduled task running under the SYSTEM account that browser window gets stuck in limbo taking up some memory and no way to interact with it or close it. So I created the abort tasks to not particularly kill choco.exe tasks, but to kill child tasks created by Chocolatey to get rid of those left over nag screens. (AutoHotKey scripts not written to handle ALL conditions also sometimes hang leaving an installer awaiting input. I've got a few packages that need different AHK scripts based on OS.)

I understand what you're saying, I just don't see the need to check every possible box available and set it to something of my choosing unless something has a purpose deemed necessary to deviate from default.

Hopefully that gives you some insight.

...and understand I do appreciate you inputting suggestions on trying to make things even better!

**Comment by DJCrashdummy** [comment]
> [...] I believe it's a very long standing default decision.

i'm pretty sure it is so.

> [...] the exception of Microsoft's OneDrive which is set to one day.

i always find it funny when a manufacturer overrides his defaults for his own products... :stuck_out_tongue_winking_eye: 

thanks for your time and explaining some details to me.
