### ISSUE TITLE
[choco-cleaner & choco-package-list-backup] execution of (short) tasks after a missed appointment

### ISSUE THREAD

**Issue by DJCrashdummy** [bcurran3/ChocolateyPackages_CCR#48]
i totally got the idea behind the pseudo-supersession of `choco-upgrade-all-at-startup` by `choco-upgrade-all-at` (because of a possible slowdown of the boot/reboot), but wouldn't it make sense to activate the setting _"execute task as soon as possible after a missed appointment"_ at least in tasks with relatively short execution-time like `choco-cleaner` and `choco-package-list-backup`?

**Comment by bcurran3** [comment]
Both of these are stand-alone scripts that can be executed manually at any time.

I'll look into making choco-cleaner and choco-package-list-backup run when missed. 

> i totally got the idea behind the pseudo-supersession of choco-upgrade-all-at-startup by choco-upgrade-all-at

Those two packages are mutually exclusive and there is nothing in one that knows about the other; there is no "pseudo-supersession"

**Comment by DJCrashdummy** [comment]
> Both of these are stand-alone scripts that can be executed manually at any time.

i'm aware of this, hence the shortcuts in the start-menu... but i'm rather thinking about automation for causal users who wouldn't run them manually or don't even have a clue about it.
so you may set an execution time for the task and don't really have to think about it if the user is ever running his machine at this time.

---

> Those two packages are mutually exclusive and there is nothing in one that knows about the other; there is no "pseudo-supersession"

i'm just citing https://chocolatey.org/packages/choco-upgrade-all-at-startup:

> [...] Because of this choco-upgrade-all-at-startup is pseudo-deprecated and pseudo-superseded by [choco-upgrade-all-at](https://chocolatey.org/packages/choco-upgrade-all-at) [...]

...and had the possible slowdown of the boot/reboot in mind. sorry for not mentioning this (edited the first comment)!

**Comment by bcurran3** [comment]
I think I read "supersession" as "suppression" the first time I read it.

> Because of this choco-upgrade-all-at-startup is pseudo-deprecated and pseudo-superseded by choco-upgrade-all-at [...]

In other words: The package is stable and nothing more can really be done with it... and I recommend choco-upgrade-all-at over it due to daily updates versus whenever a user happens to reboot.

But I'm on-board with your request!

**Comment by DJCrashdummy** [comment]
> I think I read "supersession" as "suppression" the first time I read it.

ahh... ok, funny. :wink: 

> The package is stable and nothing more can really be done [...]

yep, it looks to be the case. i want to emphasize that it's a good decision to keep providing (probably maintaining) `choco-upgrade-all-at-startup`, as it may be interesting for several people. although `choco-upgrade-all-at` is more advanced... perhaps some people are using both of them together to play it safe.

**Comment by soredake** [comment]
Any progress on this?

**Comment by bcurran3** [comment]
None yet. Honestly, it's very low priority. 

It will probably come along with the option added to all my related scripts at once.

**Comment by bcurran3** [comment]
@DJCrashdummy @soredake 

I just added support to run on batteries and to run when available after a missed schedule to choco-package-list-backup. It's a beta for you to try. Should work fine. Please get back to me with feedback.

choco install choco-package-list-backup --version=2023.05.13-pre --pre 

I'll do same to choco-cleaner after this is "signed off"

BTW: IMHO the best way to run choco-cleaner is the PostProcessScript feature of choco-upgrade-all-at or choco-upgrade-all-at-startup. That way it cleans up immediately after all your updates.

**Comment by soredake** [comment]
@bcurran3 hi! I've tested installed the new version with `sudo choco install -y choco-package-list-backup --pre`, `-StartWhenAvailable` option is corretly applied to task so i think this option can be added to choco-cleaner now.

**Comment by soredake** [comment]
@bcurran3 I've decided to do the change myself https://github.com/bcurran3/ChocolateyPackages/pull/358

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)
