### ISSUE TITLE
[Choco - openHAB2.3] Do not deploy openhab-addons-2.3.0.kar

### ISSUE THREAD

**Issue by AngelosF** [bcurran3/ChocolateyPackages_CCR#50]
Please remove from tools\ChocolateyInstall.ps1 the steps to download and deploy the addons file (openhab-addons-2.3.0.kar) since there are issues with the Karaf FeatureInstaller (it installs ALL addons auto-magically) causing massive errors.

Ref: https://github.com/openhab/openhab-distro/issues/729

Thanx!
Angelos

**Comment by bcurran3** [comment]
Done.

Thanks for the PR and changes. Please just cancel as they're already done in my latest commit.

I'm having problems pushing the package (Chocolatey server errors) but the addons have been removed and I've upped it one by now also including the binary ZIP file. I'll continue to try to get the new version published to Chocolatey.

The irony is I had it originally split out with the addons as a separate package, then aborted it and made it all one. SMH

Please let me know if it's worthwhile to push the addons as a separate package or not.

**Comment by AngelosF** [comment]
> Please let me know if it's worthwhile to push the addons as a separate package or not.

No, it's not worthwhile.
There is a critical bug with them so they are useless (for now).

Thanks for the update!

**Comment by bcurran3** [comment]
Thanks.

I could also use a new link to a nice screenshot. :)

**Comment by AngelosF** [comment]
for https://chocolatey.org/packages/openhab ?

what about the openHAB2 logo?

https://www.openhab.org/openhab-logo-square.png

**Comment by AngelosF** [comment]
btw, if you are going to update the page on choco, maybe you can fix a broken link also :)

At the Clients section, the link to the Microsoft Windows App client is broken.
From: `https://www.microsoft.com/de-de/store/p/openhab/9nmq39ctwxgt0`
It should be: `https://www.microsoft.com/en-us/p/openhab/9nmq39ctwxgt`

there are some screenshots in the MS store that you may find useful

**Comment by AngelosF** [comment]
Here is a better screenshot (from the demo of BasicUI): https://www.openhab.org/faa4c619ae9c16f8e98ef67151476221.png

**Comment by bcurran3** [comment]
Done. Done. Done.

Still having problems pushing the package. Will be updated when it can be updated:
https://groups.google.com/forum/#!topic/chocolatey/sGT1BZFBGwM

**Comment by bcurran3** [comment]
chocolatey.org is accepting pushes normally again.

I had to make a few minor modifications.

I'm guessing this will be through moderation tomorrow.
