### ISSUE TITLE
Publish new Chocolatey Package for 2.4.0 Stable

### ISSUE THREAD

**Issue by AngelosF** [bcurran3/ChocolateyPackages_CCR#54]
Hi,

Please update the Chocolatey package to include a new version for openHAB 2.4.0 Stable (without addons :))

The issue with the addons has been fixed, so it's also ok to include them back into the package if you want but they have 174MB size and they are not really needed.

Thanx and Happy Holidays!

**Comment by bcurran3** [comment]
Done!

https://chocolatey.org/packages/openhab/2.4.0

Can I eat dinner now? :)
