### ISSUE TITLE
Checksum is failing

### ISSUE THREAD

**Issue by regexaurus** [bcurran3/ChocolateyPackages_CCR#55]
Please update with current/correct checksum. Thank you!

**Comment by bcurran3** [comment]
I have no idea which package you are talking about. Please let me know.

**Comment by regexaurus** [comment]
Oh, sorry. I thought I submitted this for a specific package. I was referring to _Gsuite-Migration-Outlook_.

**Comment by bcurran3** [comment]
Thanks.  This issues page is for all of my 450+ packages!

I will get to it soon.

**Comment by bcurran3** [comment]
I'm kind of confused as it looks like they pulled a version and regressed.

I just pushed this in hopes its good, you'll probably have to install with --version
https://chocolatey.org/packages/gsuite-migration-outlook/4.0.117.0
