### ISSUE TITLE
choco-package-list-backup - add extra package details (title, URL, summary, etc) to packages.config

### ISSUE THREAD

**Issue by JohnStefanko** [bcurran3/ChocolateyPackages_CCR#56]
First, thanks for the great tool. I used your backup tool to create a packages.config file which came in very handy when I set up my new PC. However, I have a couple packages installed that I couldn't tell/remember what they were by looking at the ID. So I looked them up in Chocolatey-gui, and in addition to the package ID, I could also see that Title, Summary, and other package details were displayed. This got me poking around, and I found the other info in the .nuspec files for each package. I decided it would be nice to have some of this extra info in the packages.config.

I started by trying to load the packages.config file created by your tool as XML, thinking I would just append the extra attributes, but it seems that there must be some bad XML in your output (I got an "invalid character" error). So I decided to create my own using the .Net XmlWriter class and looping through the choco list -lo output and adding the desired info from each .nuspec to the file. Then I decided it would be nice to have this in a more readable format, so  I used the .Net XslCompiledTransform class to generate the HTML for a "pretty" doc of installed packages. 

My script and .xslt file are here:

[https://github.com/JohnStefanko/chocolatey](https://github.com/JohnStefanko/chocolatey)

If you like my ideas, feel free to use anything from my Chocolatey repository in your backup tool.

**Comment by bcurran3** [comment]
Hey John. I looked at this yesterday. Neat idea, thanks. I'm going to think on it some more.

**Comment by bcurran3** [comment]
Thanks for pointing out the encoding problem.

I found that the packages.config XML file was NOT being written out as UTF-8. (I think it was defaulting to UCS-2 BE BOM.) I would have never noticed if you didn't point it out!

This has been fixed in the v2019.01.24 release.

**Comment by bcurran3** [comment]
John,

Call me slow...

I just looked at your HTML outputted page and love it!

I plan to incorporate it into CPLB in the future.

Thanks for sharing!

**Comment by sara3d** [comment]
Could those extra attributes be used to save pinned packages version? Currently pinned packages are backed up without version information, so there is a need to either remove them from config file before restoring packages from backup or downgrade manually later.

**Comment by bcurran3** [comment]
@sara3d saving package versions along with the pin info isn't useful as you pin after you install. You want to save the package version info in the packages.config.

**Comment by bcurran3** [comment]
Started working on this...

**Comment by bcurran3** [comment]
@JohnStefanko 

I've made some progress on this. Current output with title and summary looks like this:

```
   <package id="waybackmachine-chrome" title="Wayback Machine for Chrome" summary="Wayback Machine is a Chrome extension to check Internet Archive for archived versions of web pages."/>
   <package id="weather-chrome" title="Weather for Chrome" summary="Weather extension for Chrome - The best way to see the weather right in your browser. Easier than looking outside!"/>
   <package id="Wget" title="GNU Wget" summary="A command-line utility for retrieving files using HTTP, HTTPS and FTP protocols."/>
   <package id="whocrashed" title="Who Crashed" summary="Analyzes existing crash dumps and tries to determine and state the root cause in easy to understand language."/>
   <package id="windows-10-update-assistant" title="Windows 10 Update Assistant (Portable)" summary="Windows 10 Update Assistant downloads and starts the setup for Windows 10 version 1903"/>
   <package id="winrar" title="WinRAR" summary="A powerful archive manager"/>
   <package id="wireshark" title="Wireshark" summary="Wireshark"/>
   <package id="wot-chrome" title="Web of Trust for Chrome" summary="The official Web of Trust Chrome Extension."/>
   <package id="wot-firefox" title="Web of Trust for Firefox" summary="Find out which websites you can trust. WOT adds intuitive traffic light-style icons next to search results and URLs so you can decide whether to visit a site: Green â€“ The site is trusted, Yellow â€“ Be cautious, Red â€“ Online threats detected"/>
   <package id="wsl" title="Windows Subsystem for Linux (Install)" summary="Installs Windows Subsystem for Linux"/>
```

Obviously version info is important, just not sure if any other info is important and should be added. 

Looking for feedback.

**Comment by jeff9315** [comment]
I wonder if the ProjectURL would be useful to help when you REALLY don't remember the SW or have several similar pieces of SW and your'e trying to identify which one it is.

So for whocrashed it would be url="https://www.resplendence.com/whocrashed"

**Comment by bcurran3** [comment]
I think maybe the Chocolatey product page might be a better idea as it then has all the relevant info such as the link to the product page, but then again that's as simple as chocolatey.org/packages/packagename for someone to figure out or just search for...not like you can click it from the packages.config file.

Keep thinking and let me know the results. :)

**Comment by jeff9315** [comment]
Hmmm, your last line about not being able to click it a link the packages.config file ... This is probably a stupid idea, but if it were a markdown file with an .md extension, then we could click on it once we installed our markdown editor of choice. Definitely an out-of-the-box idea, but maybe not practical or useful :-)

**Comment by bcurran3** [comment]
@jeff9315 you really should look at @JohnStefanko's https://github.com/JohnStefanko/chocolatey script.

**Comment by jeff9315** [comment]
Thanks Bill. That was EXACTLY what I was looking for!

**Comment by bcurran3** [comment]
Title and Summary info has been added as an option to save to packages.config.

https://chocolatey.org/packages/choco-package-list-backup/2019.08.27
