### ISSUE TITLE
(choco-package-list-backup) Writes to wrong Documents

### ISSUE THREAD

**Issue by SharpSeeEr** [bcurran3/ChocolateyPackages_CCR#57]
choco-package-list-backup determines the location of the users Documents folder using the `$env:UserProfile` variable.  If the user has moved his Documents folder to another location, like I have, then the backup files are written to the wrong location.  Using `[Environment]::GetFolderPath("MyDocuments")` resolves the actual location of the folder.

**Comment by bcurran3** [comment]
This has been merged, and pushed out as https://chocolatey.org/packages/choco-package-list-backup/2019.01.02

Thanks again Aaron.
