### ISSUE TITLE
wsl-ubuntu-1804 Tools missing

### ISSUE THREAD

**Issue by ejohb** [bcurran3/ChocolateyPackages_CCR#59]
Hi. The install works for me but the associated tools (e.g. `wslpath.exe`, `ubuntu.exe`) are missing.

**Comment by bcurran3** [comment]
There should be a Chocolatey shim to run it as ubuntu1804 (so you can have 1604 installed as well). Otherwise you can run direct from C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\unzipped.

Try that and let me know if I need to delve deeper.

**Comment by ejohb** [comment]
TFTQR!

Not sure how to use shims, but I found the `ubuntu1804.exe` (albeit not `wslpath.exe`) in said location. But when I run it I get:

`Error: 0x80040305
Press any key to continue...`

**Comment by bcurran3** [comment]
YW.

Shims are just tiny binary shortcuts to programs that Chocolatey makes for easy running of programs from anywhere.

RE: The error - corrupt. Most likely from multiple installs.

From the PACKAGE NOTES:
If you encounter errors such as Error: 0x80070005 Press any key to continue... it usually means that WSL has lost track of the distro files (they might have moved or been deleted.) You should uninstall the package. If the package is missing you can list your installed distros with wslconfig /list, remove the distro with wslconfig /unregister distroname, then simply reinstall the package.

I bet ya a donut that will get you working.

**Comment by bcurran3** [comment]
p.s. ubuntu.exe is for the 1604 version; i.e. you can have both installed. I know nothing about wslpath.exe. I checked my installation and don't have it either, it must not come with the distro .zip file.
