### ISSUE TITLE
wsl-ubuntu-1804: wsl not working under non-Administrator Command Prompt

### ISSUE THREAD

**Issue by ejohb** [bcurran3/ChocolateyPackages_CCR#62]
I think you might owe me a jammy?

Following on from https://github.com/bcurran3/ChocolateyPackages/issues/59 - after some messing around, I found everything works fine *as long as I'm under an Adminstrator Command Prompt*. If I use any wsl-related command (e.g. `wsl`, `bash`, `ubuntu1804`) from my normal user account, I still get:

`Error: 0x80040305 Press any key to continue...`

I've tried using the Admin prompt to create a new wsl account and setting it as default (i.e. `ubuntu1804 config --default-user <new_user>`) - thinking the non-Admin account couldn't log in as wsl `root`. But it doesn't help.

Note: I was confused about `wslpath.exe`. Turns out it's wsl-side in `/bin/wslpath`.

**Comment by bcurran3** [comment]
No, but I'll take a Cronut. :)

Sorry, this is in the PACKAGE NOTES for the other WSL distros (or some?) and I forgot to put it in this one, I'm going to go update the PACKAGE NOTES now. Thanks for pointing it out.

This package unpacks the files to C:\ProgramData\chocolatey\lib<wsl-distro>\tools\unzipped. Files in C:\ProgramData require admin privileges by default. If you want the ability to run under a non-admin account, change the file permissions.

**Comment by bcurran3** [comment]
Updated: https://github.com/bcurran3/ChocolateyPackages/tree/master/wsl-ubuntu-1804

p.s. I could take this as a feature request to update the package to change the permissions. I would have to do some testing on making sure an update doesn't wipe out an existing configuration and then if so make changes to avoid that.
