### ISSUE TITLE
Error when updating vnc-viewer

### ISSUE THREAD

**Issue by lefte** [bcurran3/ChocolateyPackages_CCR#64]
The following error is thrown when upgrading the `vnc-viewer` package to 6.19.107 using Chocolatey:

`ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot create a file when that file already exists.`

Log file available at: https://gist.github.com/lefte/3628702a97aaf63c06150755da9138b0

**Comment by bcurran3** [comment]
Hi lefte. Thanks. Uninstall and reinstall and you'll be OK. 

Here's my comment from DISCUSS:
~~Simon.~~ Thanks for letting me know about this. Uninstall and reinstall to fix the problem. I tested this on upgrade and didn't have this problem, not sure why it's happening to you but basically you already have the .EXE from the last version and it didn't get deleted to be replaced by the new version. Please click the Package Source link and open an issue for me. I'll add some extra stuff to make sure the old version gets deleted first.

**Comment by bcurran3** [comment]
Fixed with this updated release: 
https://chocolatey.org/packages/vnc-viewer/6.19.107.20190123
