### ISSUE TITLE
(choco-package-list-backup) - backup list of pinned packages

### ISSUE THREAD

**Issue by musm** [bcurran3/ChocolateyPackages_CCR#65]
This is useful for packages like dropbox, that *already* implement automatic upgrades.

Running `choco upgrade` for these packages is useless. So they should be pinned.

**Comment by bcurran3** [comment]
Theoretically:

* run "choco pin list" to get a list of pinned packages 
* parse results 
* save the file as a .BAT that could be run to re-pin packages

@musm How does that sound?

--------------------------

p.s. We could have a big discussion about the upgrade of Dropbox. There are two sides. You could disable Dropbox automatic upgrades and let Chocolatey do the upgrades. :) There's a choco issue where I expounded on this.

If interested:
https://github.com/chocolatey/choco/issues/1607

**Comment by musm** [comment]
> p.s. We could have a big discussion about the upgrade of Dropbox. There are two sides. You could disable Dropbox automatic upgrades and let Chocolatey do the upgrades. :) There's a choco issue where I expounded on this.

> If interested:
> chocolatey/choco#1607


I feel like for packages with auto-updaters, we should let the package take care of upgrade and not chocloatey. The auto-updaters are typically seamless, as opposed to the obtrusive choco upgrades that require admin privileges and manual invocation. 


I much rather prefer the auto-pin approach. I read some of your replies and understand where you are coming from and why you may prefer choco managing it all, but at least from my user perspective, I quite enjoy how dropbox silently auto-update and would be frustrated if I had to do it in chocolatey instead. 



> run "choco pin list" to get a list of pinned packages
parse results
save the file as a .BAT that could be run to re-pin packages


This is probably the easiest way to go about this.  Couldn't this be more seamlessly integrated with the backups. I.e. everytime you run choco-package-list-backup  it also exports the list?

**Comment by bcurran3** [comment]
> This is probably the easiest way to go about this. Couldn't this be more seamlessly integrated with the backups. I.e. everytime you run choco-package-list-backup it also exports the list?

Yes. That is the plan. I threw it your way to see if it seemed like a desirable method and result to you. :)

**Comment by bcurran3** [comment]
Done. I think you'll like the results.

https://chocolatey.org/packages/choco-package-list-backup/2019.01.24

**If you find choco-package-list-backup useful, and I suspect you will, please consider donating: https://www.paypal.me/bcurran3donations or become a patron at https://www.patreon.com/bcurran3**
