### ISSUE TITLE
ChocolateyPackageListBackup - $UseiCloudDrive variable typo

### ISSUE THREAD

**Issue by sandscap-sc** [bcurran3/ChocolateyPackages_CCR#68]
Hi, awesome choco packages BTW!

It looks like the variable [$UseiCloudDrive](https://github.com/bcurran3/ChocolateyPackages/blob/master/choco-package-list-backup/tools/choco-package-list-backup.ps1#L29) is set but never used because [$iCloudDrive](https://github.com/bcurran3/ChocolateyPackages/blob/master/choco-package-list-backup/tools/choco-package-list-backup.ps1#L210) is used below.

**Comment by bcurran3** [comment]
Thanks for catching that!

I'll have it fixed today or tomorrow.

**Comment by bcurran3** [comment]
Maybe I'm OCD:
https://chocolatey.org/packages/choco-package-list-backup/2019.01.29

___
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
___
