### ISSUE TITLE
[choco-persistent-packages & choco-package-list-backup] some minor issues

### ISSUE THREAD

**Issue by DJCrashdummy** [bcurran3/ChocolateyPackages_CCR#72]
i have no idea, if these things are bugs which (eventually) effect the execution of your scripts or the purpose of the files created by them, or just little inconsistencies. i haven't tested them, but want to point them out because i just stumbled across this observations.

#### `choco-persistent-packages`
all points are referring to `\ProgramData\Chocolatey\config\persistentpackages.config`:
- [ ] although claiming `encoding="utf-8"` at the first line, the encoding is UCS-2.
- [ ] the URL https://chocolatey.github.io/usage.html#the-packagesconfig-file is outdated and redirects to not really useful resources. - some months ago i found a doc which explains the `packages.config`, but a quick search now gave me unfortunately nothing.
- [ ] a closing `</xml>` tag at the end...?

#### `choco-package-list-backup`
- [ ] the line ending of `packages.config` is just `<LF>` (Unix) and not `<CR><LF>` (Windows).

**Comment by bcurran3** [comment]
Hey @DJCrashdummy,

**choco-persistent-packages**
> * although claiming `encoding="utf-8"` at the first line, the encoding is UCS-2.

You're right. It should be corrected. Alas it doesn't effect it from working.

>  the URL https://chocolatey.github.io/usage.html#the-packagesconfig-file is outdated and redirects to not really useful resources. - some months ago i found a doc which explains the packages.config, but a quick search now gave me unfortunately nothing.

That's a Chocolatey issue, not mine. :) Or do I reference it somewhere?

> * a closing `</xml>` tag at the end...?

I don't understand what you're trying to get across but... yes, that should be at the end of all XML files to close them out. peristentpackages.config has it. 

If/when choco-persistent-packages ever gets updated again, these tweaks will be addressed.

**choco-package-list-backup**
> * the line ending of `packages.config` is just `<LF>` (Unix) and not `<CR><LF>` (Windows).

You're most likely correct, but it has no effect on it working or not. It works perfectly fine.

choco-package-list-backup's latest version got a re-write of the file writing routines. I'll update the next version to add the CR to the EOF.

(This really should be two issues as there will probably be a big gap in time between each one being addressed.)

**Comment by DJCrashdummy** [comment]
>> URL https://chocolatey.github.io/usage.html#the-packagesconfig-file is outdated [...]
>
> [...] do I reference it somewhere?

yes, you link it in the comment for more information about a `packages.config`.
i know there is/was such a doc somewhere, but sadly the redirect (by chocolatey) is useless. - looking for and linking the current URL would be useful.

> > * a closing `</xml>` tag at the end...?
>
> I don't understand what you're trying to get across but... yes, that should be at the end of all XML files to close them out.

no, `<?xml ... ?>` is not a usual tag! the placement in the first line and the "**?**" (*<**?** xml ... **?**>*) makes it a declaration according to SGML. - pretty good explanation on point: https://stackoverflow.com/a/45382829/2351568
so... closing a never opened `<xml>`-tag does not makes sense at all.

> (This really should be two issues as there will probably be a big gap in time between each one being addressed.)

sorry, i wasn't even sure about opening any issue about such minor things at all... so i packed them all into one to justify the creation of an issue. :confused:

**Comment by bcurran3** [comment]
> yes, you link it in the comment for more information about a packages.config.
> i know there is/was such a doc somewhere, but sadly the redirect (by chocolatey) is useless. - looking for and linking the current URL would be useful.

I just checked choco-package-list-backup and choco-persistent-packages and don't see it. Most likely removed awhile ago to save description space.

> no, <?xml ... ?> is not a usual tag! the placement in the first line and the "?" (<? xml ... ?>) makes it a declaration according to SGML. - pretty good explanation on point: https://stackoverflow.com/a/45382829/2351568
> so... closing a never opened <xml>-tag does not makes sense at all.

I finally went and looked at the file and saw the problem. I fixed it and it's pushed to GitHub for any possible future releases. The encoding was fixed as well.
