### ISSUE TITLE
(choco-package-list-backup) Scheduled task running as SYSTEM doesn't save to user profiles 

### ISSUE THREAD

**Issue by fms615** [bcurran3/ChocolateyPackages_CCR#73]
When running choco-package-list-backup.ps1 by command line - the scripts saves successfully to 3 locations -> Documents, CustomPath, and Google Drive.

When running the task schedule . . . only CustomPath is being saved.

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command %ChocolateyInstall%\bin\choco-package-list-backup.ps1

**Comment by bcurran3** [comment]
Hi @fms615 

That's right. When it runs as a task it's running as SYSTEM, not your user account. Those other locations don't exist to the SYSTEM user account. When you run as a user, those locations exist for your user account.

One place you missed though is in C:\Users\Public which was just recently added (latest version). 

There are plans to possibly implement a /user=username parameter in the future. Some testing needs to be done. (I believe that when set up that way it will require you to enter your password and that would stop the automation of the script - so it's on hold until I have time to fully investigate and take into consideration multiple user accounts on the system.)

I suggest you make good use of that custom location.
