### ISSUE TITLE
ntlite-free: checksum out of date

### ISSUE THREAD

**Issue by wjk** [bcurran3/ChocolateyPackages_CCR#8]
Just what it says in the title, really. The actual checksum of the downloaded file (as of 9/5/2017) was ` 6FC3C5ACD8E002485619C29B3E160AE7E8AAD298E7142BC3E16550F7EE4BD299`.

**Comment by bcurran3** [comment]
Thanks. I just pushed .1.4.0.5537.

Please be sure to read the PACKAGE NOTES.
