### ISSUE TITLE
New Version of PDQ Deploy is Available

### ISSUE THREAD

**Issue by gyamada619** [bcurran3/ChocolateyPackages_CCR#81]
See [link here](https://link.pdq.com/DownloadLatest?Product=pdqdeploy) for v17.1.0.0.

I can submit a pull request for this if desired.

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/pdq-deploy/17.2.0.0

Thanks - I think finding the DL URLs are the issue with keeping this up to date.

___

Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.
___

**Comment by gyamada619** [comment]
Leaving comment because the updated package indicates it failed automated tests on chocolately.org - if you are already addressing this, please feel free to ignore. 

Appreciate your time and effort for the community!

**Comment by bcurran3** [comment]
Yeah, I think there's a pop up under WS2012 but works fine on Win10. I'll address soon.
