### ISSUE TITLE
(wsl-fedoraremix) Chocolatey Error during install.

### ISSUE THREAD

**Issue by russdb** [bcurran3/ChocolateyPackages_CCR#82]
Hi there! Thanks for maintaining all of these packages! I am attempting to install the fedora remix via chocolatey on an Enterprise LTSB build of Windows 10 as a single user. I get this error when attempting to install after the download occurs:  

Added C:\ProgramData\chocolatey\bin\fedoraremix.exe shim pointed to '..\lib\wsl-fedoraremix\tools\distro\fedoraremix.exe'.
ERROR: The term 'wslconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The install of wsl-fedoraremix was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\wsl-fedoraremix\tools\ChocolateyInstall.ps1'.
 See log for details.  

Is there  a work around for this?

**Comment by bcurran3** [comment]
YW.

I'm guessing you didn't reboot after WSL installed. 

Reboot and then try to run WSLCONFIG manually; it's part of WSL. If it doesn't work, it means WSL wasn't installed.

BTW: There is an update, but it's been stuck in moderation for two weeks...
https://chocolatey.org/packages/wsl-fedoraremix/1.0.28.0

**Comment by russdb** [comment]
It must be something with this particular version of LTSB N windows, as I can't seem to get wsl to install. I will have to do more investigating. 

edit- yep I think even though the wsl option is in windows 10 features, the fact its 2016 LTSB is playing a role I think. Guess Ill have to update to 2019 LTSC in an upcoming weekend project!

**Comment by bcurran3** [comment]
Thanks for the update.

Fill me/us back in if you think it will be of use to the community.

Good luck!
