### ISSUE TITLE
IrfanView - language packages

### ISSUE THREAD

**Issue by sara3d** [bcurran3/ChocolateyPackages_CCR#84]
This is an enhancement proposal (as discussed here https://chocolatey.org/packages/IrfanView#comment-4464584361)

It would be nice to have an option to install selected language pack:
https://www.irfanview.com/languages.htm

**Comment by mmikeww** [comment]
also, IrFanvIew 4.53 is out. Chocolatey still has 4.52

**Comment by bcurran3** [comment]
Yeah. I saw it. Thanks. I'm putting it on hold until I can get the language packs done or I won't have another chance to do it for 6 months to a year. :)

**Comment by bcurran3** [comment]
So I changed my mind. :)

Originally I was going to add a package parameter to the irfanview package to add languages. Since the new version came out unexpectedly,  I scrapped that idea as I didn't have time to do that (requires a lot of time testing) and I didn't want to hold up the arguably more important main program update. So I decided I'll just make a new languages add on package when I have the time.

**Comment by bcurran3** [comment]
REF: https://www.irfanview.com/languages.htm

Was about to do this tonight, but requires some thinking.

There are 31 language packs. Each has an installer and a zip. The installer doesn't appear to take /silent like the main program. So using the ZIPs and unZIPping them seems to be the way to go.

Real question is how best to handle (implement) this. 

1. I could add a switch to the main package to pick a language and then download that one language and install it. Seems like a good idea except the IrfanView package is self-contained and doesn't download the binaries, so it would be a shame to have to download the binaries in that package. (EDIT: Not good, see option 3!)

2. As a separate package, I could include all binaries (pain in the but to download and package them, but IrfanView isn't updated THAT frequently...), a switch to install one language and then delete all the zips. This is probably the way I will go.

3. Could also make a package that takes a language switch and then goes and downloads just that one language. Seems nice, but it means downloading all 31 files and doing checksums for them every release which makes the choice above easier to maintain.

Unless anything else hits me, I guess I'll run with option number 2.

**Comment by bcurran3** [comment]
Created to install all languages.
https://community.chocolatey.org/packages/irfanview-languages

I'll probably add a switch to install a single language in the future. With all the languages installed it's only about 40MB of diskspace, so not a high priority.

**Comment by sara3d** [comment]
Awesome, thank you!
