### ISSUE TITLE
[choco-package-list-backup] Include pins.bat in files saved with date appended

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#86]
Current behavior-
With `AppendDate` set to `true` in the `.xml`, `packages.config` and `allprograms.txt` have two versions saved, one with the date appended. But `pins.bat` has only one version saved without the date.

Expected/desired behavior- 
With `AppendDate` set to `true` in the `.xml`, all three files have a version with date appended.

**Comment by bcurran3** [comment]
Just so I understand you clearly, you'd like a historical snapshot in time backup of the pins.bat file as well correct?

**Comment by bcurran3** [comment]
OK. I see the commit. Thanks. Will test and run with it if all is OK.

**Comment by bcurran3** [comment]
Sorry I completely forgot about the commit and added this today with the config backup https://github.com/bcurran3/ChocolateyPackages/issues/91

___

Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.
___
