### ISSUE TITLE
choco-package-list-backup - Do not save to OneDrive if OneDrive is disabled

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#88]
When OneDrive is disabled via Group Policy or directly in the registry, the user OneDrive folder(s) do not get deleted(at least on Windows 10). Therefore, during the backup script, it will still backup to the OneDrive folder even though it is disabled in Windows.

I would suggest that the script checks if OneDrive is disabled before saving to the OneDrive folder. 

Keys in question-
`HKLM\Software\Policies\Microsoft\Windows\OneDrive\DisableFileSync`
`HKLM\Software\Policies\Microsoft\Windows\OneDrive\DisableFileSyncNGSC`
Both are Dwords, and a value of 1 is OneDrive sync disabled, 0 is enabled, and no key is not configured. It should be `or` logic since they both do the same thing, just for different Windows versions.

If you do not have any issues with this idea or want to implement it in a particular way, I could make a PR for it.

**Comment by bcurran3** [comment]
I think this is better handled by editing the choco-package-list-backup.xml file and setting:

` <UseOneDrive>false</UseOneDrive>`

It's there by design for such reasons.

If you feel that's not adequate enough and want to do a PR to check if OneDrive is disabled or not, go right ahead.

**Comment by TheCakeIsNaOH** [comment]
Alrighty, PR is submitted. Thanks for being open to changes like this.

I ended up only checking for the second key since that is the one that effects windows 7 through 10. I think I got the formatting ok, but feel free to fix.

**Comment by TheCakeIsNaOH** [comment]
Closing, see #89
