### ISSUE TITLE
adblockpluschrome - out of date

### ISSUE THREAD

**Issue by NickJackson525** [bcurran3/ChocolateyPackages_CCR#9]
The newest version is 1.13.3

**Comment by bcurran3** [comment]
Please read the PACKAGING NOTE: and let me know if this issue is still relevant.

**Comment by NickJackson525** [comment]
What PACKAGING NOTE are you referring to? I looked in the package and all I saw was one that said you personally use and endorse it. Thanks for the quick response.

**Comment by bcurran3** [comment]
PACKAGING NOTE is part of the package description for:
https://chocolatey.org/packages/adblockpluschrome 
found right above the install command, it's in **bold**.

Let me know that you've read the PACKAGING NOTE and that you are bringing up some other issue that I'm not aware of. I need clarity as to the problem.

**Comment by NickJackson525** [comment]
Okay. I was assuming that the version was the issue for me, since when I try to install this it doesn't seem to work. Other installs work fine, but this one doesn't seem to do anything and it is stating that adblock is already installed when it isn't. 
![cmdresult1](https://user-images.githubusercontent.com/22222848/30385268-e2ddd9b2-9863-11e7-9e74-7212e70df53a.png)

**Comment by bcurran3** [comment]
Great! Now we're getting somewhere. The extension should be installed then. I'm guessing it's installed but disabled. Check your extensions and hopefully it's as easy as clicking enable to fix the problem.

Also - you could delete it in the list of extensions and then install it via Chocolatey to make it work.

**Comment by bcurran3** [comment]
Just noticed it was installed by Chocolatey....
- Quit Chrome (shouldn't be necessary but good to do)
- uninstall adblockpluschrome via chocolatey
- install adblockpluschrome via chocolatey
- run chrome
- allow adblock plus to be enabled when asked

....should do the trick.
