### ISSUE TITLE
google-backup-and-sync needs updating (Checksum Mismatch)

### ISSUE THREAD

**Issue by kthejoker** [bcurran3/ChocolateyPackages_CCR#90]
Hey Bill,

The Google DRive Backup and Sync has released a new version and the checksums for the Chocolatey package no longer match. Thanks!

**Comment by bcurran3** [comment]
Thanks.

Done.
https://chocolatey.org/packages/google-backup-and-sync/3.44.4943.6229

NOTE: The package version is +0.0.0.0001 over the program version. Seems Google updated their installers again without updating the program.
