### ISSUE TITLE
plexmediaplayer - AU script

### ISSUE THREAD

**Issue by AeliusSaionji** [bcurran3/ChocolateyPackages_CCR#92]
Hey- I'm in the process of writing a PR for you- it's an AU automatic update script for plexmediaplayer. But I'm looking through your repository and I'm wondering if you use AU?

**Comment by bcurran3** [comment]
Have AU installed on about three computers but am currently not over the hurdle of creating the update scripts.

It's been on hold a long time because of this. 

If you supply one, I will be glad to start using it.

**Comment by AeliusSaionji** [comment]
https://github.com/bcurran3/ChocolateyPackages/pull/93

Again, I'd be happy to help maintain it.

**Comment by bcurran3** [comment]
Life's busy for me at the moment so I welcome it. Let me know your Chocolatey username and I'll add you.

**Comment by bcurran3** [comment]
And I just pushed the latest version:
https://chocolatey.org/packages/plexmediaplayer/2.36.0.988

**Comment by AeliusSaionji** [comment]
I'm LinkSatonaka on chocolatey :D

**Comment by bcurran3** [comment]
Great. I just added you as a maintainer.

**Comment by AeliusSaionji** [comment]
btw- the version I submitted was not a version mistake, it's just a duplicate.

You never did comment on the change in version- I intentionally cut off the fourth digit because of the many places in which they officially use 3 digits: https://i.imgur.com/yfPAsNf.png , and because the version is never represented with a fourth digit but without the following git hash, and chocolatey commonly uses the fourth digit for package fixes.

Is this something you disagree with?

**Comment by bcurran3** [comment]
I prefer the full version number. Package fixes can be done easily but just incrementing the build number +1, looking at the history there's always a few builds between releases.

Seem fair?

REF: https://github.com/bcurran3/ChocolateyPackages/issues/90

**Comment by AeliusSaionji** [comment]
OK- corrected my update script https://github.com/AeliusSaionji/chocopkgs/commit/f7dad076f8fe8c10c30a772ecda9e226f774eeaa
