### ISSUE TITLE
choco-package-list-backup - Multiple custom locations

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#97]
Multiple custom locations isn't crucial, but I think it would be nice in choco-package-list-backup.

**Comment by bcurran3** [comment]
So almost a year later...

Hey @jeff9315 can you give me your use case for this?

**Comment by fabiorzfreitas** [comment]
I can think of a few: I have a folder called "Installers" for everything not on Chocolatey and I use that as my custom location, but I may also want to put it in more than one drive, as well as put it in some other folder I include in my backups.

Not crucial, as mentioned above, but it would indeed be a nice touch.

**Comment by bcurran3** [comment]
I added a 2nd custom path save location for the next release.
I ALMOST added 4, but I didn't want to go overboard.
I did add pre and post processing script support, if you needed to save to 100 different places you can do so now by creating your own script and telling CPLB to run it in post processing. :)

REF: https://github.com/bcurran3/ChocolateyPackages/commit/8ad04fcb55b85f7fad1907063d5610106a9d982c
