### ISSUE TITLE
winaero tweaker failed checksum

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#99]
winaero tweaker failed checksum. I also read the package notes so I'll install ignoring the checksums for now. Also the following errors afeter I specified ` choco install winaero-tweaker --ignore-checksums`

> Attempt to get headers for https://winaero.com/e107_files/downloads/winaerotweaker.zip failed.
>   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://winaero.com/e107_files/downloads/winaerotweaker.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
> File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
> WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
> WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
> Extracting L:\Temp\Environ-Temp\Users\SYSTEM\chocolatey\winaero-tweaker\0.14.0.0\winaero-tweakerInstall.zip to C:\ProgramData\chocolatey\lib\winaero-tweaker\tools...
> C:\ProgramData\chocolatey\lib\winaero-tweaker\tools
> Installing winaero-tweaker...
> WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\winaero-tweaker\tools\WinaeroTweaker-0.14.0.0-setup.exe'. Please use full path for executables.
> ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
> The install of winaero-tweaker was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker\tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - winaero-tweaker (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\winaero-tweaker\tools\chocolateyinstall.ps1'.
>  See log for details.

**Comment by bcurran3** [comment]
Done.

https://chocolatey.org/packages/winaero-tweaker/0.15.1.0

___

Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.
___
